<?php
/**
 * @brief Cryptographer french dictionnary
 * @details Engine / Dictionnary
 * @file engine/locale/cryptographer/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Apr 2019
 * @date Modification: Apr 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['cryptographer_error_none'] = 'Aucune erreur.';
$this->trads['cryptographer_error_unknownengine'] = 'Moteur d\'encryption inconnu.';
$this->trads['cryptographer_error_enginenotavailable'] = 'Moteur d\'encryption indisponible.';
$this->trads['cryptographer_error_unknowncipher'] = 'M&eacute;thode de chiffrement inconnue.';
$this->trads['cryptographer_error_keyisempty'] = 'Cl&eacute; de chiffrement vide.';
$this->trads['cryptographer_error_ivisempty'] = 'Vecteur d\'initialisation vide.';
$this->trads['cryptographer_error_alteredmessage'] = 'Le message a &eacute;t&eacute; alt&eacute;r&eacute; et ne peut &ecirc;tre retrouv&eacute;.';
$this->trads['cryptographer_error_unknownmcryptmode'] = 'Mode de chiffrement inconnu.';
$this->trads['cryptographer_error_unknownerror'] = 'Erreur inconnue.';
?>
