<?php
/**
 * @brief Admin_GenericSearchEngineManager module, french dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Sep 2026
 * @date Modification: Sep 2026
 * @copyright 2026 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_genericsearchenginemanager_title'] = 'Moteur de recherche ';
$this->trads['mod_admin_genericsearchenginemanager_desc'] = 'G&eacute;rer le moteur de recherche';

/* Mark: Admin main configuration tab */
$this->trads['mod_admin_genericsearchenginemanager_excluded_words'] = 'Mots exclus';
$this->trads['mod_admin_genericsearchenginemanager_none'] = 'Aucun';

/* Mark: Admin main - statistics tab */
$this->trads['mod_admin_genericsearchenginemanager_tabindexedcontent'] = 'Contenu index&eacute;';
$this->trads['mod_admin_genericsearchenginemanager_formtitle_types'] = 'Types d\'objets';
$this->trads['mod_admin_genericsearchenginemanager_formtitle_objects'] = 'Objets';

/* Mark: Admin main - search tab */
$this->trads['mod_admin_genericsearchenginemanager_tabsearch'] = 'Recherche';
$this->trads['mod_admin_genericsearchenginemanager_search_execute'] = 'Rechercher';
$this->trads['mod_admin_genericsearchenginemanager_search_0result'] = 'Aucun r&eacute;sultat pour cette recherche';
$this->trads['mod_admin_genericsearchenginemanager_search_1result'] = '1 r&eacute;sultat pour cette recherche';
$this->trads['mod_admin_genericsearchenginemanager_search_xresults'] = '%s r&eacute;sultats pour cette recherche';

/* Mark: Admin configuration */
$this->trads['mod_admin_genericsearchenginemanager_formtitle_indexing'] = 'Indexation';
$this->trads['mod_admin_genericsearchenginemanager_formitem_excludedwords'] = 'Mots exclus : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_minwordlength'] = 'Longueur minimum : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_wordkeptchars'] = 'Caract&egrave;res autoris&eacute;s : ';
$this->trads['mod_admin_genericsearchenginemanager_formtitle_maxwords'] = 'Nombre de mots maximum';
$this->trads['mod_admin_genericsearchenginemanager_formtitle_weights'] = 'Pond&eacute;ration';
$this->trads['mod_admin_genericsearchenginemanager_formitem_n1'] = 'Niveau 1 : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_n2'] = 'Niveau 2 : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_n3'] = 'Niveau 3 : ';
$this->trads['mod_admin_genericsearchenginemanager_formtitle_results'] = 'R&eacute;sultats';
$this->trads['mod_admin_genericsearchenginemanager_formitem_maximumcount'] = 'Maximum retourn&eacute;s : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_countperpage'] = 'Nombre par page : ';
$this->trads['mod_admin_genericsearchenginemanager_formtitle_logging'] = 'Journalisation &amp; statistiques';
$this->trads['mod_admin_genericsearchenginemanager_formitem_logqueries'] = 'Enregistrer les requ&ecirc;tes : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_statqueries'] = 'Enregistrer les statistiques : ';
$this->trads['mod_admin_genericsearchenginemanager_formtitle_opensearchxml'] = 'OpenSearch.xml';
$this->trads['mod_admin_genericsearchenginemanager_formitem_status'] = '&Eacute;tat : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_name'] = 'Nom : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_description'] = 'Description : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_tags'] = 'Tags : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_page'] = 'Page : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_param'] = 'Nom du param&egrave;tre : ';
$this->trads['mod_admin_genericsearchenginemanager_formitem_example'] = 'Exemple : ';

/* Mark: Statistics */
$this->trads['mod_admin_genericsearchenginemanager_stat_isearches'] = 'Recherches';
$this->trads['mod_admin_genericsearchenginemanager_stat_searchresult'] = 'Recherche : "%2$s"; r&eacute;sultats : %1$s';

/* Mark: OpenSearch.xml */
$this->trads['mod_admin_genericsearchenginemanager_xmltitle'] = 'Rechercher sur %s.';
?>
