<?php
/**
 * @brief Content_GenericNews Module french dictionnary.
 * @details Plugin, Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Mar 2007
 * @date Modification: May 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericnews_title'] = 'News';
$this->trads['mod_content_genericnews_desc'] = 'Affiche des actualit&eacute;s au format texte.';

/* message */
$this->trads['mod_content_genericnews_newslistsaved'] = 'Les propri&eacute;t&eacute;s de la liste de news ont &eacute;t&eacute; sauvegard&eacute;es.';
$this->trads['mod_content_genericnews_newsitemsaved'] = 'La news a &eacute;t&eacute; sauvegard&eacute;e.';
$this->trads['mod_content_genericnews_newslistnotsaved'] = 'Les propri&eacute;t&eacute;s de la liste de news n\'ont pas &eacute;t&eacute; sauvegard&eacute;es.';
$this->trads['mod_content_genericnews_newsitemnotsaved'] = 'La news n\'a pas &eacute;t&eacute; sauvegard&eacute;e.';

/* admin : edit list / tabs */
$this->trads['mod_content_genericnews_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericnews_tabnewsitems'] = 'News';

/* admin : edit list / list form */
$this->trads['mod_content_genericnews_name'] = 'Nom';
$this->trads['mod_content_genericnews_count_list'] = 'Nombre de news affich&eacute;es';
$this->trads['mod_content_genericnews_layout_list'] = 'Layout pour la liste';
$this->trads['mod_content_genericnews_layout_item'] = 'Layout pour une news';
$this->trads['mod_content_genericnews_box_list_titleonly'] = 'Cadre - Titre seulement';
$this->trads['mod_content_genericnews_box_list_short'] = 'Cadre - Affichage court';
$this->trads['mod_content_genericnews_box_list_complete'] = 'Cadre - Affichage complet';
$this->trads['mod_content_genericnews_box_list_completebyyear'] = 'Cadre - Affichage complet s&eacute;par&eacute; par an';
$this->trads['mod_content_genericnews_box_list_completebymonth'] = 'Cadre - Affichage complet s&eacute;par&eacute; par mois';
$this->trads['mod_content_genericnews_box_list_completebyday'] = 'Cadre - Affichage complet s&eacute;par&eacute; par jour';
$this->trads['mod_content_genericnews_box_item_complete'] = 'Affichage complet';
$this->trads['mod_content_genericnews_custom'] = 'Custom';
$this->trads['mod_content_genericnews_title_title'] = 'Titre';

/* admin : edit list / list news */
$this->trads['mod_content_genericnews_newnews'] = 'Cr&eacute;er une nouvelle news';
$this->trads['mod_content_genericnews_date'] = 'Date';
$this->trads['mod_content_genericnews_status'] = 'Etat';
$this->trads['mod_content_genericnews_newstitle'] = 'Titre';
$this->trads['mod_content_genericnews_language'] = 'Langue';
$this->trads['mod_content_genericnews_author'] = 'Auteur';
$this->trads['mod_content_genericnews_previous'] = '&lt;&lt; Plus r&eacute;centes';
$this->trads['mod_content_genericnews_next'] = 'Plus anciennes &gt;&gt;';
$this->trads['mod_content_genericnews_newscount'] = '%s news';

/* admin : edit item / list form */
$this->trads['mod_content_genericnews_editanews'] = 'Editer une news';
$this->trads['mod_content_genericnews_content'] = 'Texte';
$this->trads['mod_content_genericnews_source_title'] = 'Source(titre)';
$this->trads['mod_content_genericnews_source_url'] = 'Source(url)';
$this->trads['mod_content_genericnews_inedition'] = 'En cours d\'&eacute;dition';
$this->trads['mod_content_genericnews_inline'] = 'En ligne';
$this->trads['mod_content_genericnews_edit'] = 'Modifier';

/* site : display */
$this->trads['mod_content_genericnews_site_title'] = 'Actualit&eacute;s';
$this->trads['mod_content_genericnews_infos'] = 'Par %s le %s';
$this->trads['mod_content_genericnews_infos2'] = 'Par %s &agrave; %s';
$this->trads['mod_content_genericnews_sourcelnk'] = 'Source : ';
$this->trads['mod_content_genericnews_previousnews'] = 'News pr&eacute;c&eacute;dentes';
$this->trads['mod_content_genericnews_nextnews'] = 'News suivantes';
$this->trads['mod_content_genericnews_page'] = 'Page %s';
$this->trads['mod_content_genericnews_back'] = 'Retour';
$this->trads['mod_content_genericnews_site_shareon'] = 'Partager sur :&nbsp;';
?>
