<?php
/*
 * CaMykS Engine
 * Developed by	       	: camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version       : 1.0
 * Object Type          : Plugin / Input Dictionnary
 * Create Date		: Jun 2007
 * Last Modif Date	: Jun 2008
 *
 * FileManager language dictionnary : English
 */

$this->trads['input_filemanager_defaultfoldertitle'] = 'Website documents';
$this->trads['input_filemanager_filesize'] = 'Size';
$this->trads['input_filemanager_filemodification'] = 'Modified';
$this->trads['input_filemanager_fileselection'] = 'File';
$this->trads['input_filemanager_filedimensions'] = 'Dimensions';
$this->trads['input_filemanager_selectobject'] = 'Select';
$this->trads['input_filemanager_folder'] = 'Folder';

/* view title */
$this->trads['input_filemanager_view_columns'] = 'Columns view';
$this->trads['input_filemanager_view_list'] = 'List view';
$this->trads['input_filemanager_view_bigicons'] = 'Large icon view';
$this->trads['input_filemanager_view_smallicons'] = 'Small icon view';
$this->trads['input_filemanager_view_slider'] = 'Slide view';

/* action title */
$this->trads['input_filemanager_action_file'] = 'Upload a file';
$this->trads['input_filemanager_action_folder'] = 'New folder';
$this->trads['input_filemanager_action_trash'] = 'Delete';
$this->trads['input_filemanager_action_reload'] = 'Reload interface';
$this->trads['input_filemanager_action_download'] = 'Download';
$this->trads['input_filemanager_action_rename'] = 'Rename';

/* generic popup */
$this->trads['input_filemanager_intofolder'] = 'Into';

/* folder popup */
$this->trads['input_filemanager_folderpopuptitle'] = 'New folder';

/* file popup */
$this->trads['input_filemanager_filepopuptitle'] = 'Upload a file';
$this->trads['input_filemanager_fileloadingpopuptitle'] = 'File upload in progress...';
$this->trads['input_filemanager_maxfilesize'] = 'Max size: %s ';

/* trash popup */
$this->trads['input_filemanager_trashpopuptitle'] = 'Delete a file or a folder';
$this->trads['input_filemanager_trashfile'] = 'Do you confirm the deletion of this item?';

/* rename popup */
$this->trads['input_filemanager_renamepopuptitle'] = 'Rename a file or a folder';
$this->trads['input_filemanager_renamefile'] = 'Rename a file or a folder may broke some link. Rename an item only if you are sure.';

/* list view */
$this->trads['input_filemanager_listname'] = 'Name';
$this->trads['input_filemanager_listtype'] = 'Type';
$this->trads['input_filemanager_listsize'] = 'Size';
$this->trads['input_filemanager_listdate'] = 'Modification date';
$this->trads['input_filemanager_xelements'] = '%s items';
$this->trads['input_filemanager_xelement'] = '%s item';
?>
