<?php
/**
 * @brief Admin_ToDoList Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Apr 2007
 * @date Modification: Jan 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_todolist_title'] = 'Liste To-Do';
$this->trads['mod_admin_todolist_desc'] = 'Conserve les id&eacute;es.';
$this->trads['mod_admin_todolist_desc_'] = 'Conserve %s id&eacute;e(s).';

/* tabs */
$this->trads['mod_admin_todolist_tablist'] = 'Liste';
$this->trads['mod_admin_todolist_tabedit'] = 'Editer un object';
$this->trads['mod_admin_todolist_tabnew'] = 'Nouvel objet';
$this->trads['mod_admin_todolist_tabview'] = 'To Do : %s';
$this->trads['mod_admin_todolist_tabcomments'] = '%s Commentaire(s)';

/* list */
$this->trads['mod_admin_todolist_new_item'] = 'Ajouter un nouvel objet';
$this->trads['mod_admin_todolist_none'] = 'Aucune';
$this->trads['mod_admin_todolist_user'] = 'Administrateur';

/* edit */
$this->trads['mod_admin_todolist_to_user'] = 'Destinataire';
$this->trads['mod_admin_todolist_all'] = 'Tous';
$this->trads['mod_admin_todolist_ititle'] = 'Titre';
$this->trads['mod_admin_todolist_content'] = 'Contenu';
$this->trads['mod_admin_todolist_closed'] = 'Termin&eacute;';
$this->trads['mod_admin_todolist_validobject'] = 'Valider l\'objet';
$this->trads['mod_admin_todolist_limitdateform'] = 'Date limite';

/* view */
$this->trads['mod_admin_todolist_objectaddedbyxony'] = 'Objet ajout&eacute; par %s le %s.';
$this->trads['mod_admin_todolist_validcomment'] = 'Ajouter ce commentaire';
$this->trads['mod_admin_todolist_limitdate'] = 'Date limite : %s';
$this->trads['mod_admin_todolist_nocomment'] = 'Aucun commentaire';
$this->trads['mod_admin_todolist_commentsaved'] = 'Commentaire ajout&eacute;...';
$this->trads['mod_admin_todolist_commentnotsaved'] = 'Le commentaire n\'a pas &eacute;t&eacute; ajout&eacute;.';
$this->trads['mod_admin_todolist_commentfrom'] = 'Commentaire de %s le %s.';
$this->trads['mod_admin_todolist_deleteconfirmation'] = 'Etes vous sur de vouloir effacer cet objet?';
?>
