<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0b
 * Object Version	: 1.0
 * Object Type		: Plugin / Module Dictionnary
 * Create Date		: Sep 2009
 * Last Modif Date	: Apr 2010
 *
 * Content_GenericPageRedirector english dictionnary 
*/
$this->trads['mod_content_genericpageredirector_title'] = 'Page redirector';
$this->trads['mod_content_genericpageredirector_desc'] = 'Redirects the visitor to another page.';

/* redirection method values */
$this->trads['mod_content_genericpageredirector_method_jsmeta'] = 'Client side (delayed)';
$this->trads['mod_content_genericpageredirector_method_js'] = 'Javascript';
$this->trads['mod_content_genericpageredirector_method_meta'] = 'Meta';
$this->trads['mod_content_genericpageredirector_method_header'] = 'Server site (immediate)';

/* layout values */
$this->trads['mod_content_genericpageredirector_layout_framed1'] = 'Framed 1';
$this->trads['mod_content_genericpageredirector_layout_framed2'] = 'Framed 2';
$this->trads['mod_content_genericpageredirector_layout_noframe'] = 'Without frame';

/* admin */
$this->trads['mod_content_genericpageredirector_tabproperties'] = 'Properties';
$this->trads['mod_content_genericpageredirector_formitem_layout'] = 'Layout: ';
$this->trads['mod_content_genericpageredirector_formitem_url'] = 'URL or website page: ';
$this->trads['mod_content_genericpageredirector_formitem_delay'] = 'Delay before redirection: ';
$this->trads['mod_content_genericpageredirector_formitem_method'] = 'Redirection method: ';
$this->trads['mod_content_genericpageredirector_formitem_delay_desc'] = ' second(s)  (Maximum value : 255 seconds)';

?>