<?php
/**
 * @brief GenericSitemapGenerator Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/GenericSitemapGenerator/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Feb 2019
 * @date Modification: Feb 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['input_genericsitemapgenerator_title'] = 'G&eacute;n&eacute;rateur de sitemap';

/* configuration update methods */
$this->trads['input_genericsitemapgenerator_updatemethod_modulereadingwithcache'] = 'Lecture des modules (avec cache)';
$this->trads['input_genericsitemapgenerator_updatemethod_modulereadingondemand'] = 'Lecture des modules (sur demande)';
$this->trads['input_genericsitemapgenerator_updatemethod_websitecrawling'] = 'Parcours du site internet';

/* configuration update modes */
$this->trads['input_genericsitemapgenerator_updatemode_manually'] = 'Manuellement';
$this->trads['input_genericsitemapgenerator_updatemode_automatically'] = 'Automatiquement';

/* configuration layouts */
$this->trads['input_genericsitemapgenerator_formtitle_update'] = 'Mise &agrave; jour';
$this->trads['input_genericsitemapgenerator_formitem_method'] = 'M&eacute;thode : ';
$this->trads['input_genericsitemapgenerator_formitem_mode'] = 'Mode : ';
$this->trads['input_genericsitemapgenerator_formitem_delay'] = 'D&eacute;lai : ';
$this->trads['input_genericsitemapgenerator_update_now'] = 'Mettre &agrave; jour maintenant';

$this->trads['input_genericsitemapgenerator_formtitle_lastupdate'] = 'Derni&egrave;re mise &agrave; jour';
$this->trads['input_genericsitemapgenerator_formitem_pages'] = 'Pages : ';
$this->trads['input_genericsitemapgenerator_formitem_duration'] = 'Dur&eacute;e : ';

/* Messages */
$this->trads['input_genericsitemapgenerator_sitemapfile_created'] = 'Fichier sitemap cr&eacute;&eacute;.';
$this->trads['input_genericsitemapgenerator_sitemapfile_notcreated'] = 'Une erreur est survenue lors de la cr&eacute;ation du fichier sitemap.';
?>
