<?php
/**
 * @brief GoogleAnalytics Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/GoogleAnalytics/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Sep 2018
 * @date Modification: Sep 2018
 * @copyright 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* configuration */
$this->trads['input_googleanalytics_formtitle_googleparams'] = 'Param&egrave;tres de Google Analytics';
$this->trads['input_googleanalytics_formitem_trackingcode'] = 'Code de suivi : ';
$this->trads['input_googleanalytics_formitem_trackingparams'] = 'Param&egrave;tres : ';
$this->trads['input_googleanalytics_formtitle_internalparams'] = 'Param&egrave;tres internes';
$this->trads['input_googleanalytics_formitem_enableforadmin'] = 'Activer pour les admins : ';
?>
