<?php
/**
 * @brief Tool_InfoBar Module english dictionnary
 * @details Plugin / Module Dictionnary
 * @file plugin/module/Tool_InfoBar/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Oct 2005
 * @date Modification: May 2019
 * @copyright 2005 - 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_tool_infobar_title'] = 'Info bar';
$this->trads['mod_tool_infobar_desc'] = 'Info bar of the admin section';

$this->trads['mod_tool_infobar_admin'] = 'Admin';
?>
