<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a
 * Object Version	: 1.0
 * Object Type	        : Plugin / Module Dictionnary
 * Create Date	       	: Oct 2005
 * Last Modif Date	: Mar 2007
 *
 * Admin_InfoBar french dictionnary
*/
$this->trads['mod_tool_infobar_title'] = 'Barre d\'information';
$this->trads['mod_tool_infobar_desc'] = 'Barre d\'information pour la partie administrative du site';

$this->trads['mod_tool_infobar_admin'] = 'Admin';
$this->trads['mod_tool_infobar_file'] = 'Fichier';
$this->trads['mod_tool_infobar_edition'] = 'Edition';
?>
