<?php
/*
 * CaMykS Engine
 * Developed by	       	: camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version       : 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: May 2008
 * Last Modif Date	: Oct 2008
 *
 * Content_GenericHTMLContent french dictionnary 
 */
$this->trads['mod_content_generichtmlcontent_title'] = 'Contenu HTML';
$this->trads['mod_content_generichtmlcontent_desc'] = 'Affiche un contenu HTML &eacute;ditable';

/* admin locales */
$this->trads['mod_content_generichtmlcontent_tabgeneral'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_generichtmlcontent_itemname'] = 'Nom : ';
$this->trads['mod_content_generichtmlcontent_itemlayout'] = 'Affichage : ';
$this->trads['mod_content_generichtmlcontent_layout_largebox'] = 'Encadr&eacute;';
$this->trads['mod_content_generichtmlcontent_layout_nobox'] = 'Sans cadre';
?>