<?php
/**
 * @brief Content_GenericHTMLContent Module english dictionary.
 * @details Plugin, Module dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: May 2008
 * @date Modification: May 2021
 * @copyright 2008 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_generichtmlcontent_title'] = 'HTML Content';
$this->trads['mod_content_generichtmlcontent_desc'] = 'Display an editable HTML content';

/* admin locales */
$this->trads['mod_content_generichtmlcontent_itemname'] = 'Name: ';
$this->trads['mod_content_generichtmlcontent_itemlayout'] = 'Layout: ';
$this->trads['mod_content_generichtmlcontent_layout_largebox'] = 'With box';
$this->trads['mod_content_generichtmlcontent_layout_nobox'] = 'Without box';
?>
