<?php
/**
 * @brief IPGeolocator Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Dec 2020
 * @date Modification: Dec 2020
 * @copyright 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* Configuration */
$this->trads['input_ipgeolocator_formtitle_params'] = 'Parameters';
$this->trads['input_ipgeolocator_formitem_service'] = 'Service: ';
$this->trads['input_ipgeolocator_formtitle_apikeysforservices'] = 'API keys for services';
$this->trads['input_ipgeolocator_noapikey'] = 'No key';
$this->trads['input_ipgeolocator_getakey'] = 'Get a key';
$this->trads['input_ipgeolocator_ispremium'] = 'Premium';
$this->trads['input_ipgeolocator_limitedservice'] = 'Limited services';
?>
