<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author           : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Module Dictionnary
 * Creation Date    : Sep 2010
 * Last Modif Date  : Sep 2010
 *
 * Content_GenericPetitionViewer french dictionnary
*/
$this->trads['mod_content_genericpetitionviewer_title'] = 'Affichage des p&eacute;titions';
$this->trads['mod_content_genericpetitionviewer_desc'] = '';

/* layout list */
$this->trads['mod_content_genericpetitionviewer_layout_nobox'] = 'Sans cadre';

/* admin */
$this->trads['mod_content_genericpetitionviewer_formitem_layout'] = 'Affichage : ';
$this->trads['mod_content_genericpetitionviewer_formitem_petition'] = 'P&eacute;tition : ';
$this->trads['mod_content_genericpetitionviewer_formitem_signbypage'] = 'Signatures par page : ';

/* save */
$this->trads['mod_content_genericpetitionviewer_savedone'] = 'Sauvegarde en cours...';

/* site */
$this->trads['mod_content_genericpetitionviewer_xsignsposted'] = 'La p&eacute;tition rassemble <span class="eContent2"> %s signatures</span>!';
$this->trads['mod_content_genericpetitionviewer_signnow'] = 'Signer la p&eacute;tition';
$this->trads['mod_content_genericpetitionviewer_theyhavealreadysigned'] = 'Ils ont d&eacute;j&agrave; sign&eacute; : ';
$this->trads['mod_content_genericpetitionviewer_petitionclosed'] = 'La p&eacute;tition est d&eacute;sormais ferm&eacute;e.';
$this->trads['mod_content_genericpetitionviewer_thxmessage'] = 'Votre signature a &eacute;t&eacute; enregistr&eacute;e. Merci pour votre participation.';

$this->trads['mod_content_genericpetitionviewer_formitem_birthdate'] = 'Date de naissance : ';
$this->trads['mod_content_genericpetitionviewer_signpopup_title'] = 'Signer la p&eacute;tition';
$this->trads['mod_content_genericpetitionviewer_signpopup_confirm'] = 'Je certifie &ecirc;tre le signataire et confirme ma signature.';
$this->trads['mod_content_genericpetitionviewer_signpopup_valid'] = 'Valider ma signature';
$this->trads['mod_content_genericpetitionviewer_signpopup_desc'] = 'Tous les champs sont obligatoires. Les champs "adresse", "date de naissance" et "e-mail" sont r&eacute;serv&eacute;s &agrave; l\'administrateur de la p&eacute;tition.';
?>