<?php
/**
 * @brief Admin_MyShortcuts Module english dictionnary.
 * @details Plugin / Module Dictionnary
 * @file plugin/module/Admin_MyShortcuts/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jun 2008
 * @date Modification: Jan 2019
 * @copyright 2008 - 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_myshortcuts_title'] = 'My shortcuts';
$this->trads['mod_admin_myshortcuts_desc'] = 'Edit my shortcuts';

/* admin menu */
$this->trads['mod_admin_myshortcuts_menutitle'] = 'Shortcuts';
$this->trads['mod_admin_myshortcuts_add_newshortcut'] = 'Add this page as shortcuts';
$this->trads['mod_admin_myshortcuts_edit_shortcuts'] = 'Modify my shortcuts';

/* admin popup */
$this->trads['mod_admin_myshortcuts_addpopuptitle'] = 'Add a shortcuts';
$this->trads['mod_admin_myshortcuts_addpopupname'] = 'Shortcut\'s name: ';

/* admin js message */
$this->trads['mod_admin_myshortcuts_deleteshortcutmessage'] = 'Are you sure to want to delete this shortcut? This action can\'t be undone.';

/* admin main */
$this->trads['mod_admin_myshortcuts_adddate'] = 'Added on ';
$this->trads['mod_admin_myshortcuts_editshortcut'] = 'Edit this shortcut';
$this->trads['mod_admin_myshortcuts_openshortcut'] = 'Open this shortcut';
$this->trads['mod_admin_myshortcuts_deleteshortcut'] = 'Delete this shortcut';

/* admin edit shortcut */
$this->trads['mod_admin_myshortcuts_formitem_url'] = 'URL : ';

/* admin error */
$this->trads['mod_admin_myshortcuts_accessdenied'] = 'Access denied. You can only edit your own shortcuts.';
?>
