<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a
 * Object Version	: 1.0
 * Object Type	        : Plugin / Module Dictionnary
 * Create Date		: May 2007
 * Last Modif Date	: May 2007
 *
 * Admin_MyShortcuts module french dictionnary
 */

$this->trads['mod_admin_myshortcuts_title'] = 'Mes Raccourcis';
$this->trads['mod_admin_myshortcuts_desc'] = 'Editer mes raccourcis';

/* admin menu */
$this->trads['mod_admin_myshortcuts_menutitle'] = 'Raccourcis';
$this->trads['mod_admin_myshortcuts_add_newshortcut'] = 'Ajouter cette page en raccourci';
$this->trads['mod_admin_myshortcuts_edit_shortcuts'] = 'Modifier mes raccourcis';

/* admin popup */
$this->trads['mod_admin_myshortcuts_addpopuptitle'] = 'Ajouter un raccourci';
$this->trads['mod_admin_myshortcuts_addpopupname'] = 'Nom du raccourci : ';

/* admin js message */
$this->trads['mod_admin_myshortcuts_js_deletemessage'] = 'Etes vous s&ucirc;r de vouloir supprimer ce raccourci?';

/* main */
$this->trads['mod_admin_myshortcuts_adddate'] = 'Ajout&eacute; le';
$this->trads['mod_admin_myshortcuts_edit_shortcut'] = 'Editer ce raccourci';
$this->trads['mod_admin_myshortcuts_open_shortcut'] = 'Ouvrir ce raccourci';
$this->trads['mod_admin_myshortcuts_delete_shortcut'] = 'Supprimer ce raccourci';
?>