<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	    	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type	    : Plugin / Module Dictionnary
 * Creation Date    : Jan 2015
 * Last Modif Date  : Jan 2015
 *
 * Admin_SystemUniqueIDManager french dictionnary
*/
$this->trads['mod_admin_systemuniqueidmanager_title'] = 'ID Uniques';
$this->trads['mod_admin_systemuniqueidmanager_desc'] = 'Gestion des ID Uniques';

/* object titles */
$this->trads['mod_admin_systemuniqueidmanager_key'] = 'ID unique';
$this->trads['mod_admin_systemuniqueidmanager_keys'] = 'ID uniques';
$this->trads['mod_admin_systemuniqueidmanager_keys_all'] = 'Tous';

/* admin uniqueid status value */
$this->trads['mod_admin_systemuniqueidmanager_keystatus_free'] = 'Libre';
$this->trads['mod_admin_systemuniqueidmanager_keystatus_used'] = 'Utilis&eacute;e';

/* admin uniqueids status values */
$this->trads['mod_admin_systemuniqueidmanager_keysstatus_free'] = 'Libres';
$this->trads['mod_admin_systemuniqueidmanager_keysstatus_used'] = 'Utilis&eacute;es';

/* key generating method values */
$this->trads['mod_admin_systemuniqueidmanager_keygeneratingmethod_md5'] = 'MD5';
$this->trads['mod_admin_systemuniqueidmanager_keygeneratingmethod_crc32'] = 'CRC32';
$this->trads['mod_admin_systemuniqueidmanager_keygeneratingmethod_sha'] = 'SHA1';
$this->trads['mod_admin_systemuniqueidmanager_keygeneratingmethod_uniqid'] = 'UniqId (internal method)';

/* configuration and summary */
$this->trads['mod_admin_systemuniqueidmanager_formtitle_configuration'] = 'Configuration';
$this->trads['mod_admin_systemuniqueidmanager_formtitle_generating'] = 'Cr&eacute;ation';
$this->trads['mod_admin_systemuniqueidmanager_formitem_method'] = 'M&eacute;thode : ';
$this->trads['mod_admin_systemuniqueidmanager_formitem_keylength'] = 'Longueur de cl&eacute; : ';
$this->trads['mod_admin_systemuniqueidmanager_formitem_maxattempts'] = 'Essais maximum : ';

$this->trads['mod_admin_systemuniqueidmanager_formtitle_summary'] = 'R&eacute;sum&eacute;';
$this->trads['mod_admin_systemuniqueidmanager_formitem_generatedkeys'] = 'Cl&eacute;s g&eacute;n&eacute;r&eacute;es : ';
$this->trads['mod_admin_systemuniqueidmanager_formitem_freegeneratedkeys'] = 'Cl&eacute;s g&eacute;n&eacute;r&eacute;es libres : ';
$this->trads['mod_admin_systemuniqueidmanager_generate_freekeys'] = 'G&eacute;n&eacute;rer des cl&eacute;s libres';

/* admin main */
$this->trads['mod_admin_systemuniqueidmanager_deletekey'] = 'Supprimer cette cl&eacute;';
$this->trads['mod_admin_systemuniqueidmanager_deletekeymessage'] = 'Etes-vous s&ucirc;r de vouloir supprimer cette cl&eacute; ? Cette action est irr&eacute;versible.';
$this->trads['mod_admin_systemuniqueidmanager_addnewuniqueid'] = 'Ajouter une cl&eacute; ID unique';
$this->trads['mod_admin_systemuniqueidmanager_key'] = 'Cl&eacute;';
$this->trads['mod_admin_systemuniqueidmanager_plugin'] = 'Plugin';
$this->trads['mod_admin_systemuniqueidmanager_object'] = 'Objet';

/* save config messages */
$this->trads['mod_admin_systemuniqueidmanager_config_saved'] = 'Configuration enregistr&eacute;e.';
$this->trads['mod_admin_systemuniqueidmanager_config_notsaved'] = 'Une erreur est survenue lors de l\'enregistrement de la configuration.';

/* save key messages */
$this->trads['mod_admin_systemuniqueidmanager_key_created'] = 'Cl&eacute; ID unique cr&eacute;&eacute;e.';
$this->trads['mod_admin_systemuniqueidmanager_key_notcreated'] = 'Une erreur est survenue lors de l\'enregistrement de cette cl&eacute;.';

/* delete key messages */
$this->trads['mod_admin_systemuniqueidmanager_key_deleted'] = 'Cl&eacute; ID unique supprim&eacute;e.';
$this->trads['mod_admin_systemuniqueidmanager_key_notdeleted'] = 'Une erreur est survenue lors de la suppression de cette cl&eacute;.';
?>