<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Help File
 * Creation Date	: May 2008
 * Last Modif Date	: May 2008
 *
 * Admin_ContentPage module help
*/
$this->help = array('main'=>array('html'=>'main.html.inc'),
		    'page_tree'=>array('html'=>'page_tree.html.inc',
				       'title'=>'Architecture des pages'),
		    'page_editor'=>array('html'=>'page_editor.html.inc',
					 'title'=>'Edition d\'une page'),
		    'page_model'=>array('html'=>'page_model.html.inc',
					'title'=>'Gestion des mod&egrave;les'));
?>