<?php
/**
 * @brief Admin_ContentPage Module help french page
 * @details Plugin / Module layout
 * @file plugin/module/Admin_ContentPage/help/fr/page_editor.html.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: May 2008
 * @date Modification: Sep 2018
 * @copyright 2008 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * @cond Exclude
 */
?>
<h2 class="eTitle2">
  Edition d&apos;une page
</h2>

<p class="eContent1">
  Une page est constitu&eacute;e de plusieurs param&egrave;tres, r&eacute;partie sous forme d&apos;onglets.
</p>

<p class="eContent1">
  &nbsp;
</p>

<h3 class="eTitle3">
  &gt; L&apos;onglet Propri&eacute;t&eacute;s
</h3>

<p class="eContent1">
  Correspond aux informations administratives de la page
</p>

<ul>
  <li>
    <p class="eContent2">
      Nom :
    </p>
    <p class="eContent1">
      Nom symbolique de la page. <br/>
      C&apos;est celui qui permettra aux administrateurs du site de retrouver la page dans l&apos;arborescence.
    </p>
  </li>
  <li>
    <p class="eContent2">
      Activ&eacute;e :
    </p>
    <p class="eContent1">
      La page est visible sur le site.
    </p>
  </li>
  <li>
    <p class="eContent2">
      Page d&apos;accueil du site :
    </p>
    <p class="eContent1">
      Par d&eacute;faut, c&apos;est la page que le visiteur visualisera lorsqu&apos;il entrera l&apos;adresse de votre site. <br />
      La page active la plus ancienne sera automatiquement choisie parmi les pages d&eacute;finies comme "Page d&apos;accueil". <br />
      La page active la plus ancienne sera automatiquement choisie si aucune page n&apos;est d&eacute;finie comme "Page d&apos;accueil".
    </p>
  </li>
  <li>
    <p class="eContent2">
      Propri&eacute;taire :
    </p>
    <p class="eContent1">
      Il s&apos;agit de l&apos;administrateur qui a cr&eacute;&eacute; la page. Cette donn&eacute;e n&apos;est pas modifiable.
    </p>
  </li>
  <li>
    <p class="eContent2">
      Groupe &eacute;diteur :
    </p>
    <p class="eContent1">
      Il s&apos;agit du groupe autoris&eacute; &agrave; modifier cette page. <br />
      Si aucun groupe n&apos;a &eacute;t&eacute; s&eacute;lectionn&eacute;, seul le propri&eacute;taire a les droits pour modifier la page.
    </p>
  </li>
</ul>

<p class="eContent1">
  &nbsp;
</p>

<h3 class="eTitle3">
  &gt; L&apos;onglet Metas
</h3>

<p class="eContent1">
  Principalement d&eacute;di&eacute;s aux d&eacute;veloppeurs, ils permettent d&apos;ajouter des informations &agrave; la page.
</p>

<p class="eContent1">
&nbsp;
</p>

<h3 class="eTitle3">
  &gt; L&apos;onglet Contenu
</h3>

<p class="eContent1">
  Le syst&egrave;me vous permet de modifier 3 &eacute;l&eacute;ments constituant la page :
</p>

<ul>
  <li>
    <p class="eContent2">
      Le th&egrave;me :
    </p>
    <p class="eContent1">
      Il d&eacute;finit l&apos;aspect graphique de votre page. Par d&eacute;faut, c&apos;est le th&egrave;me du site qui est utilis&eacute;.
    </p>
  </li>

  <li>
    <p class="eContent2">
      Le template :
    </p>
    <p class="eContent1">
      Il d&eacute;finit la structure de votre page. Par d&eacute;faut, c&apos;est le template du site qui est utilis&eacute;.
    </p>
  </li>

  <li>
    <p class="eContent2">
      Les modules :
    </p>
    <p class="eContent1">
      Ils d&eacute;finissent le contenu de votre page. Le syst&egrave;me propose autant de modules que le permet le template de la page.<br />
      L&apos;aperu permet de visualiser l&apos;emplacement des modules dans la page.
    </p>
  </li>
</ul>

<p class="eContent1">
  Pour chacun des emplacements, il faut choisir le module &agrave; ins&eacute;rer. <br />
  Ce module peut met de cr&eacute;er un nouveau contenu ou de r&eacute;utiliser un contenu d&eacute;j&agrave; existant.  <br />
  Par d&eacute;faut, chaque module utilise le th&egrave;me d&eacute;fini par la page. Cependant, il est possible d&apos;utiliser un autre th&egrave;me pour l&apos;un des modules.
</p>

<p class="eContent1">
  &nbsp;
</p>

<h3 class="eTitle3">
  &gt; Les onglets d&apos;informations localis&eacute;es (FR, EN, DE, etc.)
</h3>

<p class="eContent1">
  Pour chacune des langues activ&eacute;es en &eacute;dition, un onglet d&apos;informations est disponible. Il permet d&apos;ins&eacute;rer le titre de la page, son titre court (utilis&eacute; pour les menus par exemple), une description et des mots cl&eacute;s associ&eacute;s &agrave; la page.
</p>

<p class="eContent1">
  &nbsp;
</p>

<?php
/**
 * @endcond Exclude
 */
?>
