<?php
/**
 * @brief Admin_ThemeChecker Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jul 2007
 * @date Modification: Jan 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_themechecker_title'] = 'V&eacute;rificateur de th&egrave;me';
$this->trads['mod_admin_themechecker_desc'] = 'Permet de v&eacute;rifier les th&egrave;mes';

/* tabs titles */
$this->trads['mod_admin_themechecker_tabitems'] = 'El&eacute;ments graphiques';
$this->trads['mod_admin_themechecker_tabpicts'] = 'Pictos';
$this->trads['mod_admin_themechecker_tabdemo'] = 'Exemples';

/* check interface */
$this->trads['mod_admin_themechecker_check_informations'] = 'Informations';
$this->trads['mod_admin_themechecker_check_content'] = 'Fichiers';

$this->trads['mod_admin_themechecker_present'] = 'Pr&eacute;sent';
$this->trads['mod_admin_themechecker_missing'] = 'Manquant';

/* items */
$this->trads['mod_admin_themechecker_item_bar'] = 'Barre';
$this->trads['mod_admin_themechecker_item_barleft'] = 'Partie gauche';
$this->trads['mod_admin_themechecker_item_barright'] = 'Partie droite';
$this->trads['mod_admin_themechecker_item_barbutton'] = 'Bouton';
$this->trads['mod_admin_themechecker_item_baritem'] = 'Objet';

$this->trads['mod_admin_themechecker_item_box'] = 'Boite';
$this->trads['mod_admin_themechecker_item_boxheader'] = 'En-t&ecirc;te de boite';
$this->trads['mod_admin_themechecker_item_boxtitlebar'] = 'Barre de titre';
$this->trads['mod_admin_themechecker_item_boxtabsbarheader'] = 'En-t&ecirc;te de barre d\'onglets';
$this->trads['mod_admin_themechecker_item_boxtab'] = 'Onglet';
$this->trads['mod_admin_themechecker_item_boxtabselected'] = 'Onglet s&eacute;lectionn&eacute;';
$this->trads['mod_admin_themechecker_item_boxtabcssstandart'] = 'Style de l\'onglet';
$this->trads['mod_admin_themechecker_item_boxtabcssselected'] = 'Style de l\'onglet s&eacute;lectionn&eacute;';
$this->trads['mod_admin_themechecker_item_boxtabcssrollover'] = 'Style de l\'onglet en survol de souris';
$this->trads['mod_admin_themechecker_item_boxtabsbarfooter'] = 'Pied de barre d\'onglet';
$this->trads['mod_admin_themechecker_item_boxbuttonsbarheader'] = 'En-t&ecirc;te de barre de boutons';
$this->trads['mod_admin_themechecker_item_boxbuttonwithlink'] = 'Bouton sans lien';
$this->trads['mod_admin_themechecker_item_boxbuttonwithoutlink'] = 'Bouton avec lien';
$this->trads['mod_admin_themechecker_item_boxbuttonsbarfooter'] = 'Pied de barre de boutons';
$this->trads['mod_admin_themechecker_item_boxcontent1header'] = 'En-t&ecirc;te de contenu de type 1';
$this->trads['mod_admin_themechecker_item_boxcontent1footer'] = 'Pied de contenu de type 1';
$this->trads['mod_admin_themechecker_item_boxcontent2header'] = 'En-t&ecirc;te de contenu de type 2';
$this->trads['mod_admin_themechecker_item_boxcontent2footer'] = 'Pied de contenu de type 2';
$this->trads['mod_admin_themechecker_item_boxfooter'] = 'Pied de boite';

$this->trads['mod_admin_themechecker_item_button'] = 'Bouton';

$this->trads['mod_admin_themechecker_item_layeredmenu'] = 'Menu "Popup"';
$this->trads['mod_admin_themechecker_item_layeredmenuheader'] = 'En-t&ecirc;te';
$this->trads['mod_admin_themechecker_item_layeredmenuseparator'] = 'Ligne s&eacute;paratrice';
$this->trads['mod_admin_themechecker_item_layeredmenunolinkitem'] = 'Ligne sans lien';
$this->trads['mod_admin_themechecker_item_layeredmenulinkitem'] = 'Ligne avec lien';
$this->trads['mod_admin_themechecker_item_layeredmenufooter'] = 'Pied';

/* picts */
$this->trads['mod_admin_themechecker_pict_pos_std'] = 'Normal';
$this->trads['mod_admin_themechecker_pict_pos_ovr'] = 'Survol';
$this->trads['mod_admin_themechecker_pict_size'] = 'Taille %s pixels';

/* demo */
$this->trads['mod_admin_themechecker_demo_tab'] = 'Onglet %s ';
$this->trads['mod_admin_themechecker_demo_button'] = 'Bouton %s ';
$this->trads['mod_admin_themechecker_demo_tabcontenttext'] = 'Texte de d&eacute;monstration pour l\'onglet %s';
$this->trads['mod_admin_themechecker_demo_globalcontenttext'] = 'Texte de d&eacute;monstration';
$this->trads['mod_admin_themechecker_demo_layeredmenu_line'] = 'Ligne de menu';
$this->trads['mod_admin_themechecker_demo_layeredmenu_nolink'] = 'Ligne sans lien';
$this->trads['mod_admin_themechecker_demo_layeredmenu_noicon'] = 'Ligne sans ic&ocirc;ne';
$this->trads['mod_admin_themechecker_demo_uncomplete'] = 'El&eacute;ment incomplet';
?>
