<?php
/**
 * @brief Admin_GoogleTools Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Sep 2007
 * @date Modification: Jan 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_googletools_title'] = 'Outils Google';
$this->trads['mod_admin_googletools_desc'] = 'Pages r&eacute;f&eacute;renc&eacute;es, liens, ...';

/* tabs */
$this->trads['mod_admin_googletools_tabreferred'] = 'Pages r&eacute;f&eacute;renc&eacute;es';
$this->trads['mod_admin_googletools_tablinked'] = 'Pages liantes';

/* referred pages interface */
$this->trads['mod_admin_googletools_referreddesc'] = 'Cette fonction vous permet d\'afficher les pages du site qui sont r&eacute;f&eacute;renc&eacute;es sur le moteur de recherche de Google.';
$this->trads['mod_admin_googletools_referredpagescountresult'] = 'Google r&eacute;f&eacute;rence actuellement %s page(s) de votre site.';
$this->trads['mod_admin_googletools_referredpageslistresult'] = 'Les pages actuellement r&eacute;f&eacute;renc&eacute;es par Google sont :';
$this->trads['mod_admin_googletools_referredpagesfirstresult'] = 'Les %s premi&egrave;res pages actuellement r&eacute;f&eacute;renc&eacute;es par Google sont :';

/* linked pages interface */
$this->trads['mod_admin_googletools_linkeddesc'] = 'Cette fonction vous permet d\'afficher les pages de sites ext&eacute;rieurs r&eacute;f&eacute;renc&eacute;es sur le moteur de recherche de Google et qui ont un ou plusieurs liens point&eacute;s sur votre site .';
$this->trads['mod_admin_googletools_linkedpagescountresult'] = 'Google r&eacute;f&eacute;rence actuellement %s page(s) poitant vers votre site.';
$this->trads['mod_admin_googletools_linkedpageslistresult'] = 'Ces pages sont :';
$this->trads['mod_admin_googletools_linkedpagesfirstresult'] = 'Les %s premi&egrave;res pages sont :';
?>
