<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		    : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a2
 * Object Version	: 1.0
 * Object Type	    : Plugin / Module Layout
 * Create Date	    : May 2007
 * Last Modif Date	: Mar 2009
 *
 * Admin_Statistics Module Admin part of Layout : no selected object
*/
global $camyks;
?>

<div class="adminContentPanel" style="margin:8px 0;">
  <div style="text-align:center;padding:30px;" class="eTitle3">
    <?= $this->get_translation('selectanobjecttoview'); ?>
  </div>
</div>
