<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		    : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0
 * Object Version	: 1.0
 * Object Type	    : Plugin / Module Layout
 * Creation Date   	: Sep 2007
 * Last Modif Date	: Apr 2017
 *
 * Admin_Statistics Module Admin part of Layout : colorpicker replacement
*/
?>
<div style="background-color:#<?=$this->colorPickerValue?>; border:solid 1px #666; width:30px; height:16px; float:left; margin-right:4px;">
&nbsp;
</div>
<div class="eContent1" style="">
#<?=$this->colorPickerValue?>
</div>
