<?php
/**
 * @brief Admin_GooglePoIMapManager Module french dictionary
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jun 2010
 * @date Modification: Feb 2021
 * @copyright 2010 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_googlepoimapmanager_title'] = 'Points d\'int&eacute;r&ecirc;t';
$this->trads['mod_admin_googlepoimapmanager_desc'] = 'Disposition sur une carte Google Map';

/* rights */
$this->trads['mod_admin_googlepoimapmanager_right_editpoint'] = 'Edition des points';
$this->trads['mod_admin_googlepoimapmanager_right_editdata'] = 'Edition des cat&eacute;gories et ic&ocirc;nes';
$this->trads['mod_admin_googlepoimapmanager_right_editconfig'] = 'Edition de la configuration';

/* admin single point status values */
$this->trads['mod_admin_googlepoimapmanager_pointstatus_active'] = 'Activ&eacute;';
$this->trads['mod_admin_googlepoimapmanager_pointstatus_inactive'] = 'D&eacute;sactiv&eacute;';

/* admin point status values */
$this->trads['mod_admin_googlepoimapmanager_pointsstatus_all'] = 'Tous';
$this->trads['mod_admin_googlepoimapmanager_pointsstatus_active'] = 'Activ&eacute;s';
$this->trads['mod_admin_googlepoimapmanager_pointsstatus_inactive'] = 'D&eacute;sactiv&eacute;s';

/* admin single category status values */
$this->trads['mod_admin_googlepoimapmanager_categorystatus_active'] = 'Activ&eacute;e';
$this->trads['mod_admin_googlepoimapmanager_categorystatus_inactive'] = 'D&eacute;sactiv&eacute;e';

/* admin categories status values */
$this->trads['mod_admin_googlepoimapmanager_categoriesstatus_all'] = 'Toutes';
$this->trads['mod_admin_googlepoimapmanager_categoriesstatus_active'] = 'Activ&eacute;es';
$this->trads['mod_admin_googlepoimapmanager_categoriesstatus_inactive'] = 'D&eacute;sactiv&eacute;es';

/* admin main : point tab */
$this->trads['mod_admin_googlepoimapmanager_tabpoints'] = 'Points d\'int&eacute;r&ecirc;t';
$this->trads['mod_admin_googlepoimapmanager_editpoint'] = 'Editer ce point';
$this->trads['mod_admin_googlepoimapmanager_deletepoint'] = 'Supprimer ce point';
$this->trads['mod_admin_googlepoimapmanager_deletepointmessage'] = 'Etes-vous s&ucirc;r de vouloir supprimer ce point? Cette action est irr&eacute;versible.';
$this->trads['mod_admin_googlepoimapmanager_addnewpoint'] = 'Ajouter un point d\'int&eacute;r&ecirc;t';
$this->trads['mod_admin_googlepoimapmanager_formitem_country'] = 'Pays : ';

/* admin main : category tab */
$this->trads['mod_admin_googlepoimapmanager_tabcategories'] = 'Cat&eacute;gories';
$this->trads['mod_admin_googlepoimapmanager_addnewcategory'] = 'Ajouter une cat&eacute;gorie';
$this->trads['mod_admin_googlepoimapmanager_editcategory'] = 'Editer cette cat&eacute;gorie';
$this->trads['mod_admin_googlepoimapmanager_deletecategory'] = 'Supprimer cette cat&eacute;gorie';
$this->trads['mod_admin_googlepoimapmanager_deletecategorymessage'] = 'Etes-vous s&ucirc;r de vouloir supprimer cette cat&eacute;gorie? Cette action est irr&eacute;versible.';
$this->trads['mod_admin_googlepoimapmanager_points'] = 'Points';

/* admin main : icon tab */
$this->trads['mod_admin_googlepoimapmanager_tabicons'] = 'Ic&ocirc;nes';
$this->trads['mod_admin_googlepoimapmanager_addnewicon'] = 'Ajouter une ic&ocirc;ne';
$this->trads['mod_admin_googlepoimapmanager_editicon'] = 'Editer cette ic&ocirc;ne';
$this->trads['mod_admin_googlepoimapmanager_deleteicon'] = 'Supprimer cette ic&ocirc;ne';
$this->trads['mod_admin_googlepoimapmanager_deleteiconmessage'] = 'Etes-vous s&ucirc;r de vouloir supprimer cette ic&ocirc;ne? Cette action est irr&eacute;versible.';
/* admin main : config tab */
$this->trads['mod_admin_googlepoimapmanager_tabconfig'] = 'Configuration';
$this->trads['mod_admin_googlepoimapmanager_formitem_googlemapapikey'] = 'Cl&eacute; Google Map API : ';
$this->trads['mod_admin_googlepoimapmanager_noapikey'] = 'Aucune cl&eacute; d&eacute;finie';

/* admin edit category */
$this->trads['mod_admin_googlepoimapmanager_catnew'] = 'Nouvelle cat&eacute;gorie';
$this->trads['mod_admin_googlepoimapmanager_catid'] = 'Cat&eacute;gorie n&deg;%s';

/* admin edit point */
$this->trads['mod_admin_googlepoimapmanager_pointnew'] = 'Nouveau point';
$this->trads['mod_admin_googlepoimapmanager_pointid'] = 'Point n&deg;%s';
$this->trads['mod_admin_googlepoimapmanager_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_admin_googlepoimapmanager_tabcontent'] = 'Contenu';

$this->trads['mod_admin_googlepoimapmanager_formtitle_location'] = 'Localisation';
$this->trads['mod_admin_googlepoimapmanager_formitem_latitude'] = 'Latitude : ';
$this->trads['mod_admin_googlepoimapmanager_formitem_longitude'] = 'Longitude : ';
$this->trads['mod_admin_googlepoimapmanager_refreshmapposition'] = 'Rafraichir la position sur la carte';
$this->trads['mod_admin_googlepoimapmanager_formitem_icon'] = 'Ic&ocirc;ne : ';
$this->trads['mod_admin_googlepoimapmanager_none'] = 'Aucune';

/* admin edit icon */
$this->trads['mod_admin_googlepoimapmanager_iconnew'] = 'Nouvelle ic&ocirc;ne';
$this->trads['mod_admin_googlepoimapmanager_iconid'] = 'Ic&ocirc;ne n&deg;%s';

$this->trads['mod_admin_googlepoimapmanager_formitem_mainimg'] = 'Image principale : ';
$this->trads['mod_admin_googlepoimapmanager_formitem_rollimg'] = 'Image en survol : ';
$this->trads['mod_admin_googlepoimapmanager_formitem_slctimg'] = 'Image en s&eacute;lection : ';
$this->trads['mod_admin_googlepoimapmanager_formitem_shdwimg'] = 'Image ombre : ';
$this->trads['mod_admin_googlepoimapmanager_formitem_anchorloc'] = 'Point d\'ancrage';
$this->trads['mod_admin_googlepoimapmanager_formitem_x'] = 'x : ';
$this->trads['mod_admin_googlepoimapmanager_formitem_y'] = 'y : ';

/* admin edit icon javascript locales */
$this->trads['mod_admin_googlepoimapmanager_js_address_undefined'] = 'Adresse incompl&egrave;te ou inexistante.';

/* admin edit config */
$this->trads['mod_admin_googlepoimapmanager_configuration'] = 'Configuration';

/* admin save point */
$this->trads['mod_admin_googlepoimapmanager_point_saved'] = 'Point enregistr&eacute;.';
$this->trads['mod_admin_googlepoimapmanager_point_notsaved'] = 'Une erreur est survenue lors de l\'enregistrement de ce point.';

/* admin delete point */
$this->trads['mod_admin_googlepoimapmanager_point_deleted'] = 'Point supprim&eacute;.';
$this->trads['mod_admin_googlepoimapmanager_point_notdeleted'] = 'Une erreur est survenue lors de la suppression de ce point.';

/* admin save category */
$this->trads['mod_admin_googlepoimapmanager_cat_saved'] = 'Cat&eacute;gorie enregistr&eacute;e.';
$this->trads['mod_admin_googlepoimapmanager_cat_notsaved'] = 'Une erreur est survenue lors de l\'enregistrement de cette cat&eacute;gorie.';

/* admin delete category */
$this->trads['mod_admin_googlepoimapmanager_cat_deleted'] = 'Cat&eacute;gorie supprim&eacute;e.';
$this->trads['mod_admin_googlepoimapmanager_cat_notdeleted'] = 'Une erreur est survenue lors de la suppression de cette cat&eacute;gorie.';

/* admin save config */
$this->trads['mod_admin_googlepoimapmanager_config_saved'] = 'Configuration enregistr&eacute;e.';
$this->trads['mod_admin_googlepoimapmanager_config_notsaved'] = 'Une erreur est survenue lors de l\'enregistrement de la configuration.';

/* admin save icon */
$this->trads['mod_admin_googlepoimapmanager_icon_saved'] = 'Ic&ocirc;ne enregistr&eacute;e.';
$this->trads['mod_admin_googlepoimapmanager_icon_notsaved'] = 'Une erreur est survenue lors de l\'enregistrement de cette ic&ocirc;ne.';

/* admin delete icon */
$this->trads['mod_admin_googlepoimapmanager_icon_deleted'] = 'Ic&ocirc;ne supprim&eacute;s.';
$this->trads['mod_admin_googlepoimapmanager_icon_notdeleted'] = 'Une erreur est survenue lors de la suppression de cette ic&ocirc;ne.';
?>
