<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	    			: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b1
 * Object Version   : 1.0
 * Object Type      : Engine / Global Dictionnary
 * Creation Date    : Dec 2010
 * Last Modif Date  : Dec 2010
 *
 * CaMykS engine german dictionnary
 */

$this->trads['yes'] = 'Ja';
$this->trads['no'] = 'Nein';
$this->trads['error'] = 'Fehler';
$this->trads['ok'] = 'OK';
$this->trads['unavailable'] = 'Nicht verf&uuml;gbar';
$this->trads['login'] = 'Login';
$this->trads['pwd'] = 'Passwort';
$this->trads['pwd_old'] = 'Altes passwort';
$this->trads['pwd_new'] = 'Neues passwort';
$this->trads['confirm'] = 'Best&auuml;tigen';
$this->trads['continue'] = 'Weitermachen';
$this->trads['email'] = 'E-Mail';
$this->trads['back'] = 'Zur&uuml;ck';
$this->trads['quit'] = 'Beenden';
$this->trads['configuration'] = 'Einrichten';
$this->trads['help'] = 'Hilfe';
$this->trads['valid'] = 'Pr&uuml;fen';
$this->trads['plugins'] = 'Plugins';
$this->trads['plugin'] = 'Plugin';
$this->trads['pluginx'] = 'Plugin "%s"';
$this->trads['modules'] = 'Module';
$this->trads['module'] = 'Modul';
$this->trads['modulex'] = 'Modul "%s"';
$this->trads['inputs'] = 'Eingaben';
$this->trads['input'] = 'Eingabe';
$this->trads['inputx'] = 'Eingabe "%s"';
$this->trads['templates'] = 'Templates';
$this->trads['template'] = 'Template';
$this->trads['templatex'] = 'Template "%s"';
$this->trads['themes'] = 'Themen';
$this->trads['theme'] = 'Thema';
$this->trads['themex'] = 'Thema "%s"';
$this->trads['content'] = 'Content';
$this->trads['module_type_admin'] = 'Admin';
$this->trads['module_type_content'] = 'Content';
$this->trads['module_type_tool'] = 'Tool';
$this->trads['administration'] = 'Admininistration';
$this->trads['installation'] = 'Installation';
$this->trads['site_admin'] = '%s\'s administration';
$this->trads['lastname'] = 'Nachname';
$this->trads['firstname'] = 'Vorname';
$this->trads['address'] = 'Adresse';
$this->trads['civility'] = 'Titel';
$this->trads['zipcode'] = 'Postleitzahl';
$this->trads['city'] = 'Stadt';
$this->trads['country'] = 'Land';
$this->trads['title'] = 'Titel';
$this->trads['subtitle'] = 'Undertitel';
$this->trads['active'] = 'Aktiv';
$this->trads['inactive'] = 'Inaktiv';
$this->trads['name'] = 'Name';
$this->trads['version'] = 'Version';
$this->trads['author'] = 'Author';
$this->trads['camyks'] = 'CaMykS';
$this->trads['site'] = 'Webseite';
$this->trads['module_generic_help'] = 'Info';
$this->trads['read'] = 'Lesen';
$this->trads['write'] = 'Schreiben';
$this->trads['shared'] = 'Teilen';
$this->trads['dedicated'] = 'Zuweisen';
$this->trads['type'] = 'Typ';
$this->trads['properties'] = 'Eigenschafter';

/* date */
$this->trads['date'] = 'Datum';
$this->trads['today'] = 'Heute';
$this->trads['yesterday'] = 'Gestern';
$this->trads['tomorrow'] = 'Morgen';
$this->trads['dayx'] = '%s'; 
$this->trads['thisweek'] = 'Diese Woche';
$this->trads['lastweek'] = 'Letzte Woche';
$this->trads['thismonth'] = 'Diesen Monat';
$this->trads['lastmonth'] = 'Letzten Monat';
$this->trads['thisyear'] = 'Dieses Jahr';
$this->trads['lastyear'] = 'Letztes Jahr';
$this->trads['fromxtoy'] = 'Von %s bis %s'; 
$this->trads['fromx'] = 'Von %s';
$this->trads['toy'] = ' bis %s';

/* some actions */
$this->trads['close'] = 'Schlien&#223;en';
$this->trads['open'] = '&Ouml;ffnen';
$this->trads['add'] = 'Hinzuf&uuml;gen';
$this->trads['remove'] = 'Entfernen';
$this->trads['delete'] = 'L&ouml;schen';
$this->trads['cut'] = 'Ausschneiden';
$this->trads['copy'] = 'Kopieren';
$this->trads['paste'] = 'Einf&uuml;gen';
$this->trads['cancel'] = 'Beesden';
$this->trads['select'] = 'Ausw&auml;hlen';
$this->trads['edit'] = 'Editieren';
$this->trads['modify'] = 'Modifizieren';
$this->trads['duplicate'] = 'Duplizieren';
$this->trads['preview'] = 'Vorschau';
$this->trads['update'] = 'Update';
$this->trads['reset'] = 'Neustart';
$this->trads['search'] = 'Suchen';
$this->trads['display'] = 'Anzeigen';
$this->trads['listen'] = 'H&ouml;ren';

/* module messages */
$this->trads['module_can_t_be_uninstalled'] = 'Dieses Modul kann nicht deinstalliert warden.';
$this->trads['module_access_denied'] = 'Sie haben keine Zugangsberechtigung.';
$this->trads['module_page_access_denied'] = 'Sie haben keine Berechtigung, diese Seite zu &auml;ndern.';
$this->trads['module_action_not_allowed'] = 'Sie haben keine Berechtigung, diese Aktion auszuf&uuml;hren.';
$this->trads['module_plugin_missing'] = 'Dieses Modul erfordert einen anderen Zugang, der zur Zeit nicht zur Verf&uuml;gung steht. Bitte kontaktieren Sie Ihren Administrator.';


/* module actions */
$this->trads['savedone'] = 'Speichern wird ausgef&uuml;hrt...';
$this->trads['savefailed'] = 'Beim Speichern ist ein Fehler aufgetreten.';
$this->trads['deletedone'] = 'L&ouml;schen wird ausgef&uuml;hrt...';
$this->trads['deletefailed'] = 'Beim L&ouml;schen ist ein Fehler aufgetreten.';

/* languages */
$this->trads['lang_fr'] = 'Franz&ouml;sisch';
$this->trads['lang_en'] = 'Englisch';
$this->trads['lang_it'] = 'Italienisch';
$this->trads['lang_de'] = 'Deutsch';
$this->trads['lang_sp'] = 'Spanisch';
$this->trads['lang_pt'] = 'Portugiesisch';
$this->trads['lang_br'] = 'Brasilianisches portugiesisch';

/* files */
$this->trads['imagesize'] = 'Bildgr&ouml;&#223;e';
$this->trads['file_unknownfile'] = 'Unbekannte Datei';
$this->trads['file_folder'] = 'Ordner';
$this->trads['file_textfile'] = 'Textdatei (%s)';
$this->trads['file_imagefile'] = 'Bilddatei (%s)';
$this->trads['file_videofile'] = 'Videodatei (%s)';
$this->trads['file_audiofile'] = 'Audiodatei (%s)';
$this->trads['file_presentationfile'] = 'Siashow-Datei (%s)';
$this->trads['file_diskimagefile'] = 'Disk image file (%s)';
$this->trads['file_compressedfile'] = 'Komprimierte Datei (%s)';
$this->trads['file_sourcefile'] = 'Quelldatei (%s)';
$this->trads['file_genericfile'] = '%s-Datei';

$this->trads['file_nofile'] = 'Keine Datei';
$this->trads['file_viewfiletype'] = '%s-Datei ansehen';
$this->trads['file_filetype'] = '%s-Datei';
$this->trads['file_deleted'] = 'Gel&ouml;scht';

/* form inputs */
$this->trads['formitem_separator'] = ': ';
$this->trads['formitem_name'] = 'Name: ';
$this->trads['formitem_type'] = 'Typ: ';
$this->trads['formitem_title'] = 'Titel: ';
$this->trads['formitem_status'] = 'Status: ';
$this->trads['formitem_date'] = 'Datum: ';
$this->trads['formitem_description'] = 'Beschreibung: ';
$this->trads['formitem_address'] = 'Adresse: ';
$this->trads['formitem_zipcode'] = 'Postleitzahl: ';
$this->trads['formitem_city'] = 'Stadt: ';
$this->trads['formitem_state'] = 'State: ';
$this->trads['formitem_country'] = 'Land: ';
$this->trads['formitem_layout'] = 'Layout: ';
$this->trads['formitem_email'] = 'E-Mail: ';
$this->trads['formitem_phone'] = 'Telefon: ';
$this->trads['formitem_mobile'] = 'Mobiltelefon: ';
$this->trads['formitem_fax'] = 'Fax: ';
$this->trads['formitem_firstname'] = 'Vorname: ';
$this->trads['formitem_lastname'] = 'Nachname: ';
$this->trads['formitem_login'] = 'Login: ';
$this->trads['formitem_pwd'] = 'Passwort: ';
$this->trads['formitem_confirm'] = 'Best&auml;tigen: ';
$this->trads['formitem_version'] = 'Version: ';
$this->trads['formitem_package'] = 'Paket: ';
$this->trads['formitem_author'] = 'Author: ';
$this->trads['formitem_page'] = 'Seite: ';
$this->trads['formitem_website'] = 'Websieten: ';
$this->trads['formitem_category'] = 'Kategorie: ';
$this->trads['formitem_company'] = 'Firma: ';
$this->trads['formitem_civility'] = 'Titel: ';

/* form input titles */
$this->trads['formtitle_properties'] = 'Eigenschafter';

/* civility title list */
$this->trads['civility_'] = '';
$this->trads['civility_mr'] = 'Herr';
$this->trads['civility_mrs'] = 'Frau';
$this->trads['civility_ms'] = '';
$this->trads['civility_sir'] = '';
$this->trads['civility_dr'] = 'Dr.';
$this->trads['civility_pr'] = 'Prof.';
$this->trads['civility_me'] = '';

?>