<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0a
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Dictionnary
 * Create Date		: Feb 2012
 * Last Modif Date	: Jan 2018
 *
 * SocialNetworksSharingPanel language dictionnary : english 
 */

/* default share by email values */
$this->trads['input_socialnetworkssharingpanel_emailsubject'] = 'To read on %s';
$this->trads['input_socialnetworkssharingpanel_emailbody'] = 'Hi, _ln_  _ln_ I invite you to follow this link :_ln_  _ln_ _title_ _ln_ _link_ _ln_ _ln_ With best regards,';

/* site */
$this->trads['input_socialnetworkssharingpanel_followuson'] = 'Follow us on %s';

/* configuration */
$this->trads['input_socialnetworkssharingpanel_tabshare'] = 'Share';
$this->trads['input_socialnetworkssharingpanel_formdesc_share'] = 'Indicate social networks your visitors will be able to share your pages, articles, ...';
$this->trads['input_socialnetworkssharingpanel_formtitle_like'] = 'Links "Like"';
$this->trads['input_socialnetworkssharingpanel_formitem_layout'] = 'Layout: ';
$this->trads['input_socialnetworkssharingpanel_formitem_size'] = 'Size: ';
$this->trads['input_socialnetworkssharingpanel_formitem_action'] = 'Action: ';

$this->trads['input_socialnetworkssharingpanel_tabfollow'] = 'Follow';
$this->trads['input_socialnetworkssharingpanel_formdesc_follow'] = 'Indicate the URLs of your accounts on the social networks.';
$this->trads['input_socialnetworkssharingpanel_nosocialnetwork'] = 'None';

$this->trads['input_socialnetworkssharingpanel_share_disabled'] = 'Disabled';
$this->trads['input_socialnetworkssharingpanel_share_primary'] = 'Displayed directly';
$this->trads['input_socialnetworkssharingpanel_share_secondary'] = 'Displayed in pop-pup';

$this->trads['input_socialnetworkssharingpanel_like_disabled'] = 'Disabled';
$this->trads['input_socialnetworkssharingpanel_like_enabled'] = 'Enabled';

?>