<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0a
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Dictionnary
 * Create Date		: Feb 2012
 * Last Modif Date	: Feb 2012
 *
 * SocialNetworksSharingPanel language dictionnary : french 
 */

$this->trads['input_socialnetworkssharingpanel_emailsubject'] = '&Agrave; lire sur %s';
$this->trads['input_socialnetworkssharingpanel_emailbody'] = 'Bonjour, _ln_  _ln_ Je t\'invite &agrave; regarder le lien suivant :_ln_  _ln_ _title_ _ln_ _link_ _ln_ _ln_ Amicalement,';
?>