<?php
/*
 * CaMykS Engine
 * Developed by	       	: camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version       : 1.0
 * Object Type          : Plugin / Input Layout
 * Creation Date	: Jun 2007
 * Last Modif Date	: Jul 2008
 * 
 * FileManager input list view layout
 */
?>
<div id="fm_browser" class="adminControlPanel" style="width:680px;;overflow:auto;">
<?=$this->html?>
</div>