<?php
/**
 * @brief Color german dictionnary
 * @details Engine / Dictionnary
 * @file engine/locale/colors/translation_de.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jul 2017
 * @date Modification: Apr 2018
 * @copyright 2017 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['color_blue'] = 'Blau';
$this->trads['color_white'] = 'Wei&szlig;';
$this->trads['color_red'] = 'Rot';
$this->trads['color_black'] = 'Schwarz';
$this->trads['color_yellow'] = 'Gelb';
$this->trads['color_green'] = 'Gr&uml;n';
$this->trads['color_orange'] = 'Orange';
$this->trads['color_pink'] = 'Pink';
$this->trads['color_purple'] = 'Lila';

$this->trads['color_apricot'] = 'Aprikose';
$this->trads['color_acajou'] = 'Mahagoni';
$this->trads['color_aquamarine'] = 'Aquamarin';
$this->trads['color_almond'] = 'Mandel';
$this->trads['color_amaranth'] = 'Amarant';
$this->trads['color_amber'] = 'Bernstein';
$this->trads['color_amethyst'] = 'Amethyst';
$this->trads['color_anthracite'] = 'Anthrazit';
$this->trads['color_silver'] = 'Silber';
$this->trads['color_aubergine'] = 'Aubergine';
$this->trads['color_auburn'] = 'Rostbraun';
$this->trads['color_blueazure'] = 'Blau';
$this->trads['color_beige'] = 'Beige';
$this->trads['color_steelblue'] = 'Stahlblau';
$this->trads['color_navyblue'] = 'Marineblau';
$this->trads['color_goldbutton'] = 'Hahnenfu&szlig;';
$this->trads['color_brick'] = 'Ziegel';
$this->trads['color_bronze'] = 'Bronze';
$this->trads['color_cocoa'] = 'Kakao';
$this->trads['color_cinnamon'] = 'Zimt';
$this->trads['color_caramel'] = 'Karamell';
$this->trads['color_carmine'] = 'Karminrot';
$this->trads['color_carrot'] = 'Karotte';
$this->trads['color_chocolate'] = 'Schokolade';
$this->trads['color_coral'] = 'Koralle';
$this->trads['color_custard'] = 'Creme';
$this->trads['color_copper'] = 'Kupfer';
$this->trads['color_cyan'] = 'Cyan';
$this->trads['color_scarlet'] = 'Scharlach';
$this->trads['color_raw'] = 'Roh';
$this->trads['color_emerald'] = 'Smaragd';
$this->trads['color_fuchsia'] = 'Fuchsie';
$this->trads['color_greige'] = 'Greige';
$this->trads['color_garnet'] = 'Granat';
$this->trads['color_grey'] = 'Grau';
$this->trads['color_steelgrey'] = 'Stahlgrau';
$this->trads['color_pearlgrey'] = 'Marineblau';
$this->trads['color_indigo'] = 'Indigo';
$this->trads['color_yellowlemon'] = 'Zitronengelb';
$this->trads['color_khaki'] = 'Khaki';
$this->trads['color_lapislazuli'] = 'Lapislazuli';
$this->trads['color_lavender'] = 'Lavendel';
$this->trads['color_lilac'] = 'Flieder';
$this->trads['color_magenta'] = 'Magenta';
$this->trads['color_brown'] = 'Braun';
$this->trads['color_mauve'] = 'Malve';
$this->trads['color_tan'] = 'Ocker';
$this->trads['color_parma'] = 'Parma';
$this->trads['color_periwinkle'] = 'Strandschnecke';
$this->trads['color_cardinalred'] = 'Lila';
$this->trads['color_redhead'] = 'Rot';
$this->trads['color_ruby'] = 'Rubin';
$this->trads['color_sapphire'] = 'Saphir';
$this->trads['color_salmon'] = 'Lachs';
$this->trads['color_sepia'] = 'Sepia';
$this->trads['color_topaz'] = 'Topas';
$this->trads['color_turquoise'] = 'T&uml;rkis';
$this->trads['color_vermilion'] = 'Zinnober';
?>

