<?php
/**
 * @brief Color english dictionnary
 * @details Engine / Dictionnary
 * @file engine/locale/colors/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jul 2017
 * @date Modification: Apr 2018
 * @copyright 2017 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['color_blue'] = 'Blue';
$this->trads['color_white'] = 'White';
$this->trads['color_red'] = 'Red';
$this->trads['color_black'] = 'Black';
$this->trads['color_yellow'] = 'Yellow';
$this->trads['color_green'] = 'Green';
$this->trads['color_orange'] = 'Orange';
$this->trads['color_pink'] = 'Pink';
$this->trads['color_purple'] = 'Purple';

$this->trads['color_apricot'] = 'Apricot';
$this->trads['color_acajou'] = 'Acajou';
$this->trads['color_aquamarine'] = 'Aquamarine';
$this->trads['color_almond'] = 'Almond';
$this->trads['color_amaranth'] = 'Amaranth';
$this->trads['color_amber'] = 'Amber';
$this->trads['color_amethyst'] = 'Amethyst';
$this->trads['color_anthracite'] = 'Anthracite';
$this->trads['color_silver'] = 'Silver';
$this->trads['color_aubergine'] = 'Aubergine';
$this->trads['color_auburn'] = 'Auburn';
$this->trads['color_blueazure'] = 'Blueazure';
$this->trads['color_beige'] = 'Beige';
$this->trads['color_steelblue'] = 'Steelblue';
$this->trads['color_navyblue'] = 'Navyblue';
$this->trads['color_goldbutton'] = 'Goldbutton';
$this->trads['color_brick'] = 'Brick';
$this->trads['color_bronze'] = 'Bronze';
$this->trads['color_cocoa'] = 'Cocoa';
$this->trads['color_coffee'] = 'Coffee';
$this->trads['color_cinnamon'] = 'Cinnamon';
$this->trads['color_caramel'] = 'Caramel';
$this->trads['color_carmine'] = 'Carmine';
$this->trads['color_carrot'] = 'Carrot';
$this->trads['color_chocolate'] = 'Chocolate';
$this->trads['color_coral'] = 'Coral';
$this->trads['color_custard'] = 'Custard';
$this->trads['color_copper'] = 'Copper';
$this->trads['color_cyan'] = 'Cyan';
$this->trads['color_scarlet'] = 'Scarlet';
$this->trads['color_saw'] = 'Saw';
$this->trads['color_emerald'] = 'Emerald';
$this->trads['color_fuchsia'] = 'Fuchsia';
$this->trads['color_greige'] = 'Greige';
$this->trads['color_garnet'] = 'Garnet';
$this->trads['color_grey'] = 'Grey';
$this->trads['color_steelgrey'] = 'Steelgrey';
$this->trads['color_pearlgrey'] = 'Pearlgrey';
$this->trads['color_indigo'] = 'Indigo';
$this->trads['color_yellowlemon'] = 'Yellowlemon';
$this->trads['color_khaki'] = 'Khaki';
$this->trads['color_lapislazuli'] = 'Lapis lazuli';
$this->trads['color_lavender'] = 'Lavander';
$this->trads['color_lilac'] = 'Lilac';
$this->trads['color_magenta'] = 'Magenta';
$this->trads['color_brown'] = 'Brown';
$this->trads['color_mauve'] = 'Mauve';
$this->trads['color_tan'] = 'Tan';
$this->trads['color_parma'] = 'Parma';
$this->trads['color_periwinkle'] = 'Periwinkle';
$this->trads['color_cardinalred'] = 'Cardinalred';
$this->trads['color_redhead'] = 'Redhead';
$this->trads['color_ruby'] = 'Ruby';
$this->trads['color_sapphire'] = 'Sapphire';
$this->trads['color_salmon'] = 'Salmon';
$this->trads['color_sepia'] = 'Sepia';
$this->trads['color_topaz'] = 'Topaz';
$this->trads['color_turquoise'] = 'Turquoise';
$this->trads['color_vermilion'] = 'Vermilion';
?>