<?php
/**
 * @brief Color italian dictionnary
 * @details Engine / Dictionnary
 * @file engine/locale/colors/translation_it.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jul 2017
 * @date Modification: Apr 2018
 * @copyright 2017 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['color_blue'] = 'Blu';
$this->trads['color_white'] = 'Bianco';
$this->trads['color_red'] = 'Rosso';
$this->trads['color_black'] = 'Nero';
$this->trads['color_yellow'] = 'Giallo';
$this->trads['color_green'] = 'Verde';
$this->trads['color_orange'] = 'Arancione';
$this->trads['color_pink'] = 'Rosa';
$this->trads['color_purple'] = 'Porpora';

$this->trads['color_apricot'] = 'Albicocca';
$this->trads['color_acajou'] = 'Mogano';
$this->trads['color_aquamarine'] = 'Acquamarina';
$this->trads['color_almond'] = 'Mandorla';
$this->trads['color_amaranth'] = 'Amaranto';
$this->trads['color_amber'] = 'Ambra';
$this->trads['color_amethyst'] = 'Ametista';
$this->trads['color_anthracite'] = 'Anthracite';
$this->trads['color_silver'] = 'Argento';
$this->trads['color_aubergine'] = 'Melanzana';
$this->trads['color_auburn'] = 'Rame';
$this->trads['color_blueazure'] = 'Blu';
$this->trads['color_beige'] = 'Beige';
$this->trads['color_steelblue'] = 'Acciaio blu';
$this->trads['color_navyblue'] = 'Blu marino';
$this->trads['color_goldbutton'] = 'Ranuncolo';
$this->trads['color_brick'] = 'Mattone';
$this->trads['color_bronze'] = 'Bronzo';
$this->trads['color_cocoa'] = 'Kakao';
$this->trads['color_coffee'] = 'Caffè';
$this->trads['color_cinnamon'] = 'Cannella';
$this->trads['color_caramel'] = 'Caramello';
$this->trads['color_carmine'] = 'Carminio';
$this->trads['color_carrot'] = 'Carota';
$this->trads['color_chocolate'] = 'Cioccolato';
$this->trads['color_coral'] = 'Corallo';
$this->trads['color_custard'] = 'Crema';
$this->trads['color_copper'] = 'Rame';
$this->trads['color_cyan'] = 'Ciano';
$this->trads['color_scarlet'] = 'Scarlatto';
$this->trads['color_raw'] = 'Crudo';
$this->trads['color_emerald'] = 'Smeraldo';
$this->trads['color_fuchsia'] = 'Fucsia';
$this->trads['color_greige'] = 'Greige';
$this->trads['color_garnet'] = 'Granato';
$this->trads['color_grey'] = 'Grigio';
$this->trads['color_steelgrey'] = 'Grigio acciaio';
$this->trads['color_pearlgrey'] = 'Grigio perla';
$this->trads['color_indigo'] = 'Indaco';
$this->trads['color_yellowlemon'] = 'Giallo limone';
$this->trads['color_khaki'] = 'Cachi';
$this->trads['color_lapislazuli'] = 'Lapislazzuli';
$this->trads['color_lavender'] = 'Lavanda';
$this->trads['color_lilac'] = 'Lilla';
$this->trads['color_magenta'] = 'Magenta';
$this->trads['color_brown'] = 'Marrone';
$this->trads['color_mauve'] = 'Malva';
$this->trads['color_tan'] = 'Ocra';
$this->trads['color_parma'] = 'Parma';
$this->trads['color_periwinkle'] = 'Pervinca';
$this->trads['color_cardinalred'] = 'Porpora';
$this->trads['color_redhead'] = 'Rosso';
$this->trads['color_ruby'] = 'Rubino';
$this->trads['color_sapphire'] = 'Zaffiro';
$this->trads['color_salmon'] = 'Salmone';
$this->trads['color_sepia'] = 'Nero di seppia';
$this->trads['color_topaz'] = 'Topazio';
$this->trads['color_turquoise'] = 'Turchese';
$this->trads['color_vermilion'] = 'Vermiglio';
?>
