<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <jb.lebrun@ideogram-design.fr>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Engine / Dictionnary
 * Creation Date    : July 2017
 * Last Modif Date  : July 2017
 *
 * Color portuguese dictionnary
*/
$this->trads['color_blue'] = 'Azul';
$this->trads['color_white'] = 'Branco';
$this->trads['color_red'] = 'Vermelho';
$this->trads['color_black'] = 'Preto';
$this->trads['color_yellow'] = 'Amarelo';
$this->trads['color_green'] = 'Verde';
$this->trads['color_orange'] = 'Laranja';
$this->trads['color_pink'] = 'Rosa';
$this->trads['color_purple'] = 'Roxo';

$this->trads['color_apricot'] = 'Damasco';
$this->trads['color_acajou'] = 'Mogno';
$this->trads['color_aquamarine'] = '&Aacute;gua-marinha';
$this->trads['color_almond'] = 'Am&ecirc;ndoa';
$this->trads['color_amaranth'] = 'Amaranto';
$this->trads['color_amber'] = '&Acirc;mbar';
$this->trads['color_amethyst'] = 'Ametista';
$this->trads['color_anthracite'] = 'Anthracite';
$this->trads['color_silver'] = 'Prateado';
$this->trads['color_aubergine'] = 'Berinjela';
$this->trads['color_auburn'] = 'Castanho-avermelhado';
$this->trads['color_blueazure'] = 'Azul';
$this->trads['color_beige'] = 'Bege';
$this->trads['color_steelblue'] = 'Cinza a&ccedil;o';
$this->trads['color_navyblue'] = 'Azul-marinho';
$this->trads['color_goldbutton'] = 'Ran&uacute;nculo';
$this->trads['color_brick'] = 'Tijolo';
$this->trads['color_bronze'] = 'Bronze';
$this->trads['color_cocoa'] = 'Cacau';
$this->trads['color_coffee'] = 'Caf&eacute;';
$this->trads['color_cinnamon'] = 'Canela';
$this->trads['color_caramel'] = 'Caramelo';
$this->trads['color_carmine'] = 'Carmim';
$this->trads['color_carrot'] = 'Cenoura';
$this->trads['color_chocolate'] = 'Chocolate';
$this->trads['color_coral'] = 'Coral';
$this->trads['color_custard'] = 'Creme';
$this->trads['color_copper'] = 'Cobre';
$this->trads['color_cyan'] = 'Ciano';
$this->trads['color_scarlet'] = 'Escarlate';
$this->trads['color_raw'] = 'Cru';
$this->trads['color_emerald'] = 'Esmeralda';
$this->trads['color_fuchsia'] = 'F&uacute;csia';
$this->trads['color_greige'] = 'Greige';
$this->trads['color_garnet'] = 'Granada';
$this->trads['color_grey'] = 'Cinza';
$this->trads['color_steelgrey'] = 'Cinza a&ccedil;o';
$this->trads['color_pearlgrey'] = 'Cinza'; // to be fixed
$this->trads['color_indigo'] = '&Iacute;ndigo';
$this->trads['color_yellowlemon'] = 'Amarelo lim&atilde;o';
$this->trads['color_khaki'] = 'Caqui';
$this->trads['color_lapislazuli'] = 'Lazulite';
$this->trads['color_lavender'] = 'Lavanda';
$this->trads['color_lilac'] = 'Lil&aacute;s';
$this->trads['color_magenta'] = 'Magenta';
$this->trads['color_brown'] = 'Marrom';
$this->trads['color_mauve'] = 'Malva';
$this->trads['color_tan'] = 'Ocre';
$this->trads['color_parma'] = 'Parma';
$this->trads['color_periwinkle'] = 'Mirta';
$this->trads['color_cardinalred'] = 'Roxo';
$this->trads['color_redhead'] = 'Vermelho';
$this->trads['color_ruby'] = 'Rubi';
$this->trads['color_sapphire'] = 'Safira';
$this->trads['color_salmon'] = 'Salm&atilde;o';
$this->trads['color_sepia'] = 'S&eacute;pia';
$this->trads['color_topaz'] = 'Top&aacute;zio';
$this->trads['color_turquoise'] = 'Turquesa';
$this->trads['color_vermilion'] = 'Vermelh&atilde;o';
?>

