<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author           : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Module Dictionnary
 * Creation Date    : Sep 2010
 * Last Modif Date  : Sep 2010
 *
 * Content_GenericGuestbookViewer french dictionnary
 */
$this->trads['mod_content_genericguestbookviewer_title'] = 'Affichage du livre d\'or';
$this->trads['mod_content_genericguestbookviewer_desc'] = '';

/* layout list */
$this->trads['mod_content_genericguestbookviewer_layout_nobox'] = 'Sans cadre';

/* config message form layout values */
$this->trads['mod_content_genericguestbookviewer_formlayout_newpage'] = 'Nouvelle page';
$this->trads['mod_content_genericguestbookviewer_formlayout_popup'] = 'Pop-up';


/* gpc source list */
$this->trads['mod_content_genericguestbookviewer_gpc_name'] = 'Contr&ocirc;leur';

/* admin */
$this->trads['mod_content_genericguestbookviewer_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericguestbookviewer_tabcontent'] = 'Contenu';

$this->trads['mod_content_genericguestbookviewer_formitem_layout'] = 'Affichage : ';
$this->trads['mod_content_genericguestbookviewer_formitem_msgbypage'] = 'Messages par page : ';
$this->trads['mod_content_genericguestbookviewer_formitem_gpcstyle'] = 'Design sp&eacute;cifi&eacute; par : ';
$this->trads['mod_content_genericguestbookviewer_formitem_formlayout'] = 'Affichage du formulaire : ';

/* save */
$this->trads['mod_content_genericguestbookviewer_savedone'] = 'Sauvegarde en cours...';

/* site */
$this->trads['mod_content_genericguestbookviewer_addmymessage'] = 'Ajouter mon message';
$this->trads['mod_content_genericguestbookviewer_msgpopup_title'] = 'Ajouter mon message';
$this->trads['mod_content_genericguestbookviewer_msgpopup_valid'] = 'Envoyer mon message';
$this->trads['mod_content_genericguestbookviewer_formitem_message'] = 'Message : ';

$this->trads['mod_content_genericguestbookviewer_message_submitted'] = 'Votre message a &eacute;t&eacute; enregistr&eacute;. Merci pour votre participation!';

$this->trads['mod_content_genericguestbookviewer_messagepostedbyxaty'] = 'Message post&eacute;e par %s le %s';
?>