<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0b
 * Object Version	: 1.0
 * Object Type	        : Plugin / Module Dictionnary
 * Creation Date	: Feb 2013
 * Last Modif Date	: Feb 2013
 *
 * Admin_PluginManager module english dictionnary
 */
$this->trads['mod_admin_pluginmanager_title'] = 'Plugin Manager';
$this->trads['mod_admin_pluginmanager_desc'] = 'Manage available plugins';

/* tabs titles */
$this->trads['mod_admin_pluginmanager_tabmodules'] = 'Modules';
$this->trads['mod_admin_pluginmanager_tabthemes'] = 'Themes';
$this->trads['mod_admin_pluginmanager_tabtemplates'] = 'Templates';
$this->trads['mod_admin_pluginmanager_tabinputs'] = 'Inputs';

/* list */
$this->trads['mod_admin_pluginmanager_type'] = 'Type';
$this->trads['mod_admin_pluginmanager_package'] = 'Package';
$this->trads['mod_admin_pluginmanager_version'] = 'V.';
$this->trads['mod_admin_pluginmanager_location'] = 'Folder';
$this->trads['mod_admin_pluginmanager_state'] = 'Status';
$this->trads['mod_admin_pluginmanager_actions'] = 'Actions';
$this->trads['mod_admin_pluginmanager_active'] = 'Enabled';
$this->trads['mod_admin_pluginmanager_inactive'] = 'Disabled';
$this->trads['mod_admin_pluginmanager_installed'] = 'Installed';
$this->trads['mod_admin_pluginmanager_notinstalled'] = 'Not installed';
$this->trads['mod_admin_pluginmanager_noinstallationrequired'] = 'No installation required';
$this->trads['mod_admin_pluginmanager_desactivate'] = 'Disable';
$this->trads['mod_admin_pluginmanager_activate'] = 'Enable';
$this->trads['mod_admin_pluginmanager_required'] = 'Required';

/* messages */
$this->trads['mod_admin_pluginmanager_activationdone'] = 'Plugin "%s" is now enabled.';
$this->trads['mod_admin_pluginmanager_activationfailed'] = 'Plugin "%s" could not be installed, an error has occured while installing the plugin.';
$this->trads['mod_admin_pluginmanager_desactivationdone'] = 'Plugin "%s" is now disabled.';
$this->trads['mod_admin_pluginmanager_cleaningdone'] = 'Database cleaning in progress..';
$this->trads['mod_admin_pluginmanager_nocleaningneeded'] = 'No cleaning required, no action done.';

/* menu */
$this->trads['mod_admin_pluginmanager_cleandatabase'] = 'Clean database';
?>