<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		    : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0
 * Object Version	: 1.0
 * Object Type	    : Plugin / Module Dictionnary
 * Creation Date	: Jun 2005
 * Last Modif Date	: May 2007
 *
 * Admin_PluginManager module french  dictionnary
 */
$this->trads['mod_admin_pluginmanager_title'] = 'Gestionnaire de plugins';
$this->trads['mod_admin_pluginmanager_desc'] = 'Gestion des plugins disponibles';

/* tabs titles */
$this->trads['mod_admin_pluginmanager_tabmodules'] = 'Les modules';
$this->trads['mod_admin_pluginmanager_tabthemes'] = 'Les th&egrave;mes';
$this->trads['mod_admin_pluginmanager_tabtemplates'] = 'Les templates';
$this->trads['mod_admin_pluginmanager_tabinputs'] = 'Les inputs';

/* list */
$this->trads['mod_admin_pluginmanager_type'] = 'Type';
$this->trads['mod_admin_pluginmanager_package'] = 'Package';
$this->trads['mod_admin_pluginmanager_version'] = 'V.';
$this->trads['mod_admin_pluginmanager_location'] = 'Dossier';
$this->trads['mod_admin_pluginmanager_state'] = 'Etat';
$this->trads['mod_admin_pluginmanager_actions'] = 'Actions';
$this->trads['mod_admin_pluginmanager_active'] = 'Activ&eacute;';
$this->trads['mod_admin_pluginmanager_inactive'] = 'D&eacute;sactiv&eacute;';
$this->trads['mod_admin_pluginmanager_installed'] = 'Install&eacute;';
$this->trads['mod_admin_pluginmanager_notinstalled'] = 'Non install&eacute;';
$this->trads['mod_admin_pluginmanager_noinstallationrequired'] = 'Aucune installation requise';
$this->trads['mod_admin_pluginmanager_desactivate'] = 'D&eacute;sactiver';
$this->trads['mod_admin_pluginmanager_activate'] = 'Activer';
$this->trads['mod_admin_pluginmanager_required'] = 'Requis';

/* messages */
$this->trads['mod_admin_pluginmanager_activationdone'] = 'Le plugin "%s" vient d\'&ecirc;tre activ&eacute;.';
$this->trads['mod_admin_pluginmanager_activationfailed'] = 'Le plugin "%s" n\' a pu &ecirc;tre activ&eacute;, une erreur est survenue lors de l\'installation du plugin.';
$this->trads['mod_admin_pluginmanager_desactivationdone'] = 'Le plugin "%s" vient d\'&ecirc;tre d&eacute;sactiv&eacute;.';
$this->trads['mod_admin_pluginmanager_cleaningdone'] = 'Nettoyage de la base de donn&eacute;e en cours...';
$this->trads['mod_admin_pluginmanager_nocleaningneeded'] = 'Aucun nettoyage n&eacute;cessaire. Aucune action effectu&eacute;e.';
$this->trads['mod_admin_pluginmanager_configurationupdated'] = 'Configuration mise &agrave; jour.';
$this->trads['mod_admin_pluginmanager_configurationotupdated'] = 'Une erreur est survenue lors de la mise &agrave; jour.';

/* menu */
$this->trads['mod_admin_pluginmanager_cleandatabase'] = 'Nettoyer la base de donn&eacute;es';

/* action menus */
$this->trads['mod_admin_pluginmanager_applyassitedefaulttheme'] = 'Appliquer en tant que th&egrave;me visiteur par d&eacute;faut';
$this->trads['mod_admin_pluginmanager_applyasadmindefaulttheme'] = 'Appliquer en tant que th&egrave;me admin par d&eacute;faut';
$this->trads['mod_admin_pluginmanager_applyassitedefaulttemplate'] = 'Appliquer en tant que template visiteur par d&eacute;faut';
?>