<?php
/**
 * @brief GenericRSSFeed Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/GenericRSSFeed/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Dec 2007
 * @date Modification: Apr 2018
 * @copyright 2007 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['input_genericrssfeed_title'] = 'Generic RSS Feed';
$this->trads['input_genericrssfeed_desc'] = 'Return a RSS Feed XML file';
$this->trads['input_genericrssfeed_rssgenerator'] = 'RSS Generator by CaMykS ( http://www.camyks.net )';
?>
