<?php
/*
 * CaMykS Engine
 * Developed by	       	: camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version       : 1.0
 * Object Type          : Plugin / Input Dictionnary
 * Creation Date	: Dec 2007
 * Last Modif Date	: Dec 2007
 *
 * GenericRSSFeed language dictionnary : English
 */
$this->trads['input_genericrssfeed_title'] = 'Generic RSS Feed';
$this->trads['input_genericrssfeed_desc'] = 'Return a RSS Feed XML file';
$this->trads['input_genericrssfeed_rssgenerator'] = 'RSS Generator by CaMykS ( http://www.camyks.net )';
?>
