<?php
/**
 * @brief Content_GenericRandomText Module english dictionary.
 * @details Plugin, Module dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Oct 2008
 * @date Modification: Jul 2021
 * @copyright 2008 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericrandomtext_title'] = 'Random texts';
$this->trads['mod_content_genericrandomtext_desc'] = 'Display a text from a random list.';

/* layouts */
$this->trads['mod_content_genericrandomtext_layout_classic'] = 'Classic';
$this->trads['mod_content_genericrandomtext_layout_boxed'] = 'Boxed';

/* admin tabs */
$this->trads['mod_content_genericrandomtext_tabproperties'] = 'Properties';
$this->trads['mod_content_genericrandomtext_tabitems'] = 'Text list';

/* admin list interface */
$this->trads['mod_content_genericrandomtext_sitesessionkeep'] = 'Unique for a session : ';
$this->trads['mod_content_genericrandomtext_sitesessionkeepalt'] = '(Defines if texts are unique for a visitor session.)';
$this->trads['mod_content_genericrandomtext_itemname'] = 'Text name';
$this->trads['mod_content_genericrandomtext_itemweight'] = 'Weight';
$this->trads['mod_content_genericrandomtext_newtext'] = 'Add a new text';
$this->trads['mod_content_genericrandomtext_edittext'] = 'Edit text';
$this->trads['mod_content_genericrandomtext_deletetext'] = 'Delete text';
$this->trads['mod_content_genericrandomtext_deletemessage'] = 'Are you sure to want to delete this text ? This action cannot be undone.';

/* admin edit item interface */
$this->trads['mod_content_genericrandomtext_formitem_name'] = 'Text name : ';
$this->trads['mod_content_genericrandomtext_formitem_weight'] = 'Weight : ';
$this->trads['mod_content_genericrandomtext_formitem_content'] = 'Content : ';
$this->trads['mod_content_genericrandomtext_itemweightalt'] = ' 0 (never) < x < 255 (frequent)';
?>
