<?php
/**
 * @brief Content_GenericRandomText Module french dictionary.
 * @details Plugin, Module dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Mar 2007
 * @date Modification: Jul 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericrandomtext_title'] = 'Textes al&eacute;atoires';
$this->trads['mod_content_genericrandomtext_desc'] = 'Affiche un texte al&eacute;atoirement parmi une liste.';

/* layouts */
$this->trads['mod_content_genericrandomtext_layout_classic'] = 'Classique';
$this->trads['mod_content_genericrandomtext_layout_boxed'] = 'En cadre';

/* admin tabs */
$this->trads['mod_content_genericrandomtext_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericrandomtext_tabitems'] = 'Liste des textes';

/* admin list interface */
$this->trads['mod_content_genericrandomtext_sitesessionkeep'] = 'Unique par session : ';
$this->trads['mod_content_genericrandomtext_sitesessionkeepalt'] = '(Indique si le texte doit &ecirc;tre unique tout au long de la session de l\'utilisateur.)';
$this->trads['mod_content_genericrandomtext_itemname'] = 'Nom du texte';
$this->trads['mod_content_genericrandomtext_itemweight'] = 'Poids';
$this->trads['mod_content_genericrandomtext_newtext'] = 'Ajouter un nouveau texte';
$this->trads['mod_content_genericrandomtext_edittext'] = 'Editer le texte';
$this->trads['mod_content_genericrandomtext_deletetext'] = 'Supprimer le texte';
$this->trads['mod_content_genericrandomtext_deletemessage'] = 'Etes-vous s&ucirc;r de vouloir supprimer ce texte ? Cette action est irr&eacute;versible.';

/* admin edit item interface */
$this->trads['mod_content_genericrandomtext_formitem_name'] = 'Nom du texte : ';
$this->trads['mod_content_genericrandomtext_formitem_weight'] = 'Poids : ';
$this->trads['mod_content_genericrandomtext_formitem_content'] = 'Contenu : ';
$this->trads['mod_content_genericrandomtext_itemweightalt'] = ' 0 (jamais) < x < 255 (fr&eacute;quent)';
?>
