<?php
/**
 * @brief Unknown bots as client bots specific methods
 * @details Engine / Bot Library
 * @file engine/lib/tool/clientBots/Unknowns.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Jan 2019
 * @date Modification: Jan 2019
 * @copyright 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * @warning This library is not loaded with CaMykS initialisation.
 */

/**
 * Return given known web unknown bot list.
 * @return array
 * @private
 */
function _client_getKnownUnknowns() {
    /* SEOBulls */
    $knownBots['seo bulls'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'SEO Bulls (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* SEOBulls */
    $knownBots['seobulls'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'SEO Bulls (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* unknown bot */
    $knownBots['tmm crawler'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'TMM Crawler (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* unknown bot */
    $knownBots['no.indexing@gmail.com'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Unknown bot',
        'bot_url'           => 'mailto:no.indexing@gmail.com',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* unknown bot */
    $knownBots['nbertaupete95(at)gmail.com'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Unknown bot',
        'bot_url'           => 'mailto:nbertaupete95@gmail.com',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Centurybot9 */
    $knownBots['centurybot9'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Centurybot9 (Unknown bot)',
        'bot_url'           => 'mailto:centurybot9@gmail.com',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* celious search engine */
    $knownBots['celious search engine'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Celious Search Engine (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* SMURLExpander */
    $knownBots['smurlexpander'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'SMURLExpander (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* DnyzBot */
    $knownBots['dnyzbot'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'DnyzBot (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* adscanner */
    $knownBots['adscanner'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'adscanner (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* UCmore */
    $knownBots['ucmore'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'UCmore (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* BigDataCloud */
    $knownBots['bigdatacloud'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'BigDataCloud (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Peopleman */
    $knownBots['peopleman'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Peopleman (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* KickFire */
    $knownBots['kickfire'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'KickFire (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Microgine Crawler */
    $knownBots['microgine crawler'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Microgine Crawler (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Meta_Bot */
    $knownBots['meta_bot'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Meta_Bot (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Your-Website-Sucks */
    $knownBots['your-website-sucks'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Your-Website-Sucks (Unknown bot)',
        'bot_url'           => 'http://www.Your-Website-Sucks.net/',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* test/0.1 (tester)    */
    $knownBots['(tester)'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'test (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* MauiBot */
    $knownBots['mauibot'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'MauiBot',
        'bot_url'           => 'mailto:crawler.feedback+wc@gmail.com',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* MauiBot ? crawler (crawler.feedback@gmail.com) */
    $knownBots['crawler.feedback@gmail.com'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'crawler (crawler.feedback@gmail.com) (Unknown bot)',
        'bot_url'           => 'mailto:crawler.feedback@gmail.com',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Auto Spider */
    $knownBots['auto spider'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Auto Spider (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* The Knowledge AI */
    $knownBots['the knowledge ai'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'The Knowledge AI (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* CRMNLCrawlAgent */
    $knownBots['crmnlcrawlagent'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'CRMNLCrawlAgent (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* SOcrawl */
    $knownBots['socrawl'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'SOcrawl (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Kerrigan */
    $knownBots['kerrigan'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Kerrigan (Unknown bot)',
        'bot_url'           => 'mailto:kerrigan@mashable.com',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* dcrawl */
    $knownBots['dcrawl'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'dcrawl (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* BUFF library */
    $knownBots['buff library'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'BUFF library (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* WordupinfoSearch */
    $knownBots['wordupinfosearch'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'WordupinfoSearch (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Who.is Bot */
    $knownBots['who.is bot'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Who.is Bot (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* HoneyBee Bot */
    $knownBots['honeybee'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'HoneyBee (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* Blackboard Safeassign Bot */
    $knownBots['blackboard safeassign'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Blackboard Safeassign (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* SIMON SMITH Bot */
    $knownBots['simon smith'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'Simon Smith (Unknown bot)',
        'bot_url'           => 'forensic@evestigator.com.au',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* YunSecurityBot */
    $knownBots['yunsecuritybot'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'YunSecurityBot (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* NETCOMplete */
    $knownBots['netcomplete'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'NETCOMplete (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* PocketImageCache - PocketParser (https://getpocket.com) bot ? */
    $knownBots['pocketimagecache'] = array(
        'platform_type'     => 'bot',
        'platform_format'   => 'desktop',
        'bot_title'         => 'PocketImageCache (Unknown bot)',
        'bot_url'           => '',
        'engine_title'      => '',
        'engine_url'        => '',
    );

    /* return bot list */
    return $knownBots;
}
