<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <jb.lebrun@ideogram-design.fr>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Engine / Dictionnary
 * Creation Date    : Jun 2017
 * Last Modif Date  : Jun 2017
 *
 * French departments french dictionnary
*/

$this->trads['frenchdepartment_01'] = 'Ain';
$this->trads['frenchdepartment_02'] = 'Aisne';
$this->trads['frenchdepartment_03'] = 'Allier';
$this->trads['frenchdepartment_04'] = 'Alpes-de-Haute-Provence';
$this->trads['frenchdepartment_05'] = 'Hautes-Alpes';
$this->trads['frenchdepartment_06'] = 'Alpes-Maritimes';
$this->trads['frenchdepartment_07'] = 'Ard&egrave;che';
$this->trads['frenchdepartment_08'] = 'Ardennes';
$this->trads['frenchdepartment_09'] = 'Ari&egrave;ge';
$this->trads['frenchdepartment_10'] = 'Aube';
$this->trads['frenchdepartment_11'] = 'Aude';
$this->trads['frenchdepartment_12'] = 'Aveyron';
$this->trads['frenchdepartment_13'] = 'Bouches-du-Rh&ocirc;ne';
$this->trads['frenchdepartment_14'] = 'Calvados';
$this->trads['frenchdepartment_15'] = 'Cantal';
$this->trads['frenchdepartment_16'] = 'Charente';
$this->trads['frenchdepartment_17'] = 'Charente-Maritime';
$this->trads['frenchdepartment_18'] = 'Cher';
$this->trads['frenchdepartment_19'] = 'Corr&egrave;ze';
$this->trads['frenchdepartment_20'] = 'Corse';
$this->trads['frenchdepartment_2a'] = 'Corse-du-Sud';
$this->trads['frenchdepartment_2b'] = 'Haute-Corse';
$this->trads['frenchdepartment_21'] = 'C&ocirc;te-d\'Or';
$this->trads['frenchdepartment_22'] = 'C&ocirc;tes-d\'Armor';
$this->trads['frenchdepartment_23'] = 'Creuse';
$this->trads['frenchdepartment_24'] = 'Dordogne';
$this->trads['frenchdepartment_25'] = 'Doubs';
$this->trads['frenchdepartment_26'] = 'Dr&ocirc;me';
$this->trads['frenchdepartment_27'] = 'Eure';
$this->trads['frenchdepartment_28'] = 'Eure-et-Loir';
$this->trads['frenchdepartment_29'] = 'Finist&egrave;re';
$this->trads['frenchdepartment_30'] = 'Gard';
$this->trads['frenchdepartment_31'] = 'Haute-Garonne';
$this->trads['frenchdepartment_32'] = 'Gers';
$this->trads['frenchdepartment_33'] = 'Gironde';
$this->trads['frenchdepartment_34'] = 'H&eacute;rault';
$this->trads['frenchdepartment_35'] = 'Ille-et-Vilaine';
$this->trads['frenchdepartment_36'] = 'Indre';
$this->trads['frenchdepartment_37'] = 'Indre-et-Loire';
$this->trads['frenchdepartment_38'] = 'Is&egrave;re';
$this->trads['frenchdepartment_39'] = 'Jura';
$this->trads['frenchdepartment_40'] = 'Landes';
$this->trads['frenchdepartment_41'] = 'Loir-et-Cher';
$this->trads['frenchdepartment_42'] = 'Loire';
$this->trads['frenchdepartment_43'] = 'Haute-Loire';
$this->trads['frenchdepartment_44'] = 'Loire-Atlantique';
$this->trads['frenchdepartment_45'] = 'Loiret';
$this->trads['frenchdepartment_46'] = 'Lot';
$this->trads['frenchdepartment_47'] = 'Lot-et-Garonne';
$this->trads['frenchdepartment_48'] = 'Loz&egrave;re';
$this->trads['frenchdepartment_49'] = 'Maine-et-Loire';
$this->trads['frenchdepartment_50'] = 'Manche';
$this->trads['frenchdepartment_51'] = 'Marne';
$this->trads['frenchdepartment_52'] = 'Haute-Marne';
$this->trads['frenchdepartment_53'] = 'Mayenne';
$this->trads['frenchdepartment_54'] = 'Meurthe-et-Moselle';
$this->trads['frenchdepartment_55'] = 'Meuse';
$this->trads['frenchdepartment_56'] = 'Morbihan';
$this->trads['frenchdepartment_57'] = 'Moselle';
$this->trads['frenchdepartment_58'] = 'Ni&egrave;vre';
$this->trads['frenchdepartment_59'] = 'Nord';
$this->trads['frenchdepartment_60'] = 'Oise';
$this->trads['frenchdepartment_61'] = 'Orne';
$this->trads['frenchdepartment_62'] = 'Pas-de-Calais';
$this->trads['frenchdepartment_63'] = 'Puy-de-D&ocirc;me';
$this->trads['frenchdepartment_64'] = 'Pyr&eacute;n&eacute;es-Atlantiques';
$this->trads['frenchdepartment_65'] = 'Hautes-Pyr&eacute;n&eacute;es';
$this->trads['frenchdepartment_66'] = 'Pyr&eacute;n&eacute;es-Orientales';
$this->trads['frenchdepartment_67'] = 'Bas-Rhin';
$this->trads['frenchdepartment_68'] = 'Haut-Rhin';
$this->trads['frenchdepartment_69'] = 'Rh&ocirc;ne';
$this->trads['frenchdepartment_70'] = 'Haute-Sa&ocirc;ne';
$this->trads['frenchdepartment_71'] = 'Sa&ocirc;ne-et-Loire';
$this->trads['frenchdepartment_72'] = 'Sarthe';
$this->trads['frenchdepartment_73'] = 'Savoie';
$this->trads['frenchdepartment_74'] = 'Haute-Savoie';
$this->trads['frenchdepartment_75'] = 'Paris';
$this->trads['frenchdepartment_76'] = 'Seine-Maritime';
$this->trads['frenchdepartment_77'] = 'Seine-et-Marne';
$this->trads['frenchdepartment_78'] = 'Yvelines';
$this->trads['frenchdepartment_79'] = 'Deux-S&egrave;vres';
$this->trads['frenchdepartment_80'] = 'Somme';
$this->trads['frenchdepartment_81'] = 'Tarn';
$this->trads['frenchdepartment_82'] = 'Tarn-et-Garonne';
$this->trads['frenchdepartment_83'] = 'Var';
$this->trads['frenchdepartment_84'] = 'Vaucluse';
$this->trads['frenchdepartment_85'] = 'Vend&eacute;e';
$this->trads['frenchdepartment_86'] = 'Vienne';
$this->trads['frenchdepartment_87'] = 'Haute-Vienne';
$this->trads['frenchdepartment_88'] = 'Vosges';
$this->trads['frenchdepartment_89'] = 'Yonne';
$this->trads['frenchdepartment_90'] = 'Territoire de Belfort';
$this->trads['frenchdepartment_91'] = 'Essonne';
$this->trads['frenchdepartment_92'] = 'Haut-de-Seine';
$this->trads['frenchdepartment_93'] = 'Seine-Saint-Denis';
$this->trads['frenchdepartment_94'] = 'Val-de-Marne';
$this->trads['frenchdepartment_95'] = 'Val-d\'Oise';
$this->trads['frenchdepartment_98'] = 'Monaco';
$this->trads['frenchdepartment_971'] = 'Guadeloupe';
$this->trads['frenchdepartment_972'] = 'Martinique';
$this->trads['frenchdepartment_973'] = 'Guyane';
$this->trads['frenchdepartment_974'] = 'La R&eacute;union';
$this->trads['frenchdepartment_975'] = 'Saint-Pierre-et-Miquelon';
$this->trads['frenchdepartment_976'] = 'Mayotte';
$this->trads['frenchdepartment_977'] = 'Saint-Barth&eacute;lemy';
$this->trads['frenchdepartment_978'] = 'Saint-Martin';
$this->trads['frenchdepartment_986'] = 'Wallis-et-Futuna';
$this->trads['frenchdepartment_987'] = 'Polyn&eacute;sie Française';
$this->trads['frenchdepartment_988'] = 'Nouvelle-Cal&eacute;donie';
?>

