<?php
/**
 * @brief French departments italian dictionnary
 * @details Engine / Dictionnary
 * @file engine/locale/frenchdepartments/translation_it.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jun 2017
 * @date Modification: Apr 2018
 * @copyright 2017 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['frenchdepartment_01'] = 'Ain';
$this->trads['frenchdepartment_02'] = 'Aisne';
$this->trads['frenchdepartment_03'] = 'Allier';
$this->trads['frenchdepartment_04'] = 'Alpi dell\'Alta Provenza';
$this->trads['frenchdepartment_05'] = 'Alte Alpi';
$this->trads['frenchdepartment_06'] = 'Alpi Marittime';
$this->trads['frenchdepartment_07'] = 'Ard&egrave;che';
$this->trads['frenchdepartment_08'] = 'Ardennes';
$this->trads['frenchdepartment_09'] = 'Ari&egrave;ge';
$this->trads['frenchdepartment_10'] = 'Aube';
$this->trads['frenchdepartment_11'] = 'Aude';
$this->trads['frenchdepartment_12'] = 'Aveyron';
$this->trads['frenchdepartment_13'] = 'Bocche del Rodano';
$this->trads['frenchdepartment_14'] = 'Calvados';
$this->trads['frenchdepartment_15'] = 'Cantal';
$this->trads['frenchdepartment_16'] = 'Charente';
$this->trads['frenchdepartment_17'] = 'Charente Marittima';
$this->trads['frenchdepartment_18'] = 'Cher';
$this->trads['frenchdepartment_19'] = 'Corr&egrave;ze';
$this->trads['frenchdepartment_20'] = 'Corsica';
$this->trads['frenchdepartment_2a'] = 'Corsica del Sud';
$this->trads['frenchdepartment_2b'] = 'Alta Corsica';
$this->trads['frenchdepartment_21'] = 'C&ocirc;te-d\'Or';
$this->trads['frenchdepartment_22'] = 'C&ocirc;tes-d\'Armor';
$this->trads['frenchdepartment_23'] = 'Creuse';
$this->trads['frenchdepartment_24'] = 'Dordogne';
$this->trads['frenchdepartment_25'] = 'Doubs';
$this->trads['frenchdepartment_26'] = 'Dr&ocirc;me';
$this->trads['frenchdepartment_27'] = 'Eure';
$this->trads['frenchdepartment_28'] = 'Eure-et-Loir';
$this->trads['frenchdepartment_29'] = 'Finist&egrave;re';
$this->trads['frenchdepartment_30'] = 'Gard';
$this->trads['frenchdepartment_31'] = 'Alta Garonna';
$this->trads['frenchdepartment_32'] = 'Gers';
$this->trads['frenchdepartment_33'] = 'Gironda';
$this->trads['frenchdepartment_34'] = 'H&eacute;rault';
$this->trads['frenchdepartment_35'] = 'Ille-et-Vilaine';
$this->trads['frenchdepartment_36'] = 'Indre';
$this->trads['frenchdepartment_37'] = 'Indre-et-Loire';
$this->trads['frenchdepartment_38'] = 'Is&egrave;re';
$this->trads['frenchdepartment_39'] = 'Giura';
$this->trads['frenchdepartment_40'] = 'Landes';
$this->trads['frenchdepartment_41'] = 'Loir-et-Cher';
$this->trads['frenchdepartment_42'] = 'Loira';
$this->trads['frenchdepartment_43'] = 'Alta Loira';
$this->trads['frenchdepartment_44'] = 'Loira Atlantica';
$this->trads['frenchdepartment_45'] = 'Loiret';
$this->trads['frenchdepartment_46'] = 'Lot';
$this->trads['frenchdepartment_47'] = 'Lot e Garonna';
$this->trads['frenchdepartment_48'] = 'Loz&egrave;re';
$this->trads['frenchdepartment_49'] = 'Maine e Loira';
$this->trads['frenchdepartment_50'] = 'Manica';
$this->trads['frenchdepartment_51'] = 'Marna';
$this->trads['frenchdepartment_52'] = 'Alta Marna';
$this->trads['frenchdepartment_53'] = 'Mayenne';
$this->trads['frenchdepartment_54'] = 'Meurthe e Mosella';
$this->trads['frenchdepartment_55'] = 'Mosa';
$this->trads['frenchdepartment_56'] = 'Morbihan';
$this->trads['frenchdepartment_57'] = 'Mosella';
$this->trads['frenchdepartment_58'] = 'Ni&egrave;vre';
$this->trads['frenchdepartment_59'] = 'Nord';
$this->trads['frenchdepartment_60'] = 'Oise';
$this->trads['frenchdepartment_61'] = 'Orne';
$this->trads['frenchdepartment_62'] = 'Passo di Calais';
$this->trads['frenchdepartment_63'] = 'Puy-de-D&ocirc;me';
$this->trads['frenchdepartment_64'] = 'Pirenei Atlantici';
$this->trads['frenchdepartment_65'] = 'Alti Pirenei';
$this->trads['frenchdepartment_66'] = 'Pirenei Orientali';
$this->trads['frenchdepartment_67'] = 'Basso Reno';
$this->trads['frenchdepartment_68'] = 'Alto Reno';
$this->trads['frenchdepartment_69'] = 'Rh&ocirc;ne';
$this->trads['frenchdepartment_70'] = 'Alta Saona';
$this->trads['frenchdepartment_71'] = 'Saona e Loira';
$this->trads['frenchdepartment_72'] = 'Sarthe';
$this->trads['frenchdepartment_73'] = 'Savoia';
$this->trads['frenchdepartment_74'] = 'Alta Savoia';
$this->trads['frenchdepartment_75'] = 'Parigi';
$this->trads['frenchdepartment_76'] = 'Senna Marittima';
$this->trads['frenchdepartment_77'] = 'Senna e Marna';
$this->trads['frenchdepartment_78'] = 'Yvelines';
$this->trads['frenchdepartment_79'] = 'Deux-S&egrave;vres';
$this->trads['frenchdepartment_80'] = 'Somme';
$this->trads['frenchdepartment_81'] = 'Tarn';
$this->trads['frenchdepartment_82'] = 'Tarn e Garonna';
$this->trads['frenchdepartment_83'] = 'Var';
$this->trads['frenchdepartment_84'] = 'Vaucluse';
$this->trads['frenchdepartment_85'] = 'Vendea';
$this->trads['frenchdepartment_86'] = 'Vienne';
$this->trads['frenchdepartment_87'] = 'Alta Vienne';
$this->trads['frenchdepartment_88'] = 'Vosgi';
$this->trads['frenchdepartment_89'] = 'Yonne';
$this->trads['frenchdepartment_90'] = 'Territorio di Belfort';
$this->trads['frenchdepartment_91'] = 'Essonne';
$this->trads['frenchdepartment_92'] = 'Haut-de-Seine';
$this->trads['frenchdepartment_93'] = 'Senna-Saint-Denis';
$this->trads['frenchdepartment_94'] = 'Valle della Marna';
$this->trads['frenchdepartment_95'] = 'Val-d\'Oise';
$this->trads['frenchdepartment_98'] = 'Monaco';
$this->trads['frenchdepartment_971'] = 'Guadalupa';
$this->trads['frenchdepartment_972'] = 'Martinica';
$this->trads['frenchdepartment_973'] = 'Guyana francese';
$this->trads['frenchdepartment_974'] = 'Riunione';
$this->trads['frenchdepartment_975'] = 'Saint-Pierre-et-Miquelon';
$this->trads['frenchdepartment_976'] = 'Mayotte';
$this->trads['frenchdepartment_977'] = 'Saint-Barth&eacute;lemy';
$this->trads['frenchdepartment_978'] = 'Saint-Martin';
$this->trads['frenchdepartment_986'] = 'Wallis-et-Futuna';
$this->trads['frenchdepartment_987'] = 'Polyn&eacute;sie Française';
$this->trads['frenchdepartment_988'] = 'Nouvelle-Cal&eacute;donie';
?>
