<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Creation Date	: Jan 2008
 * Last Modif Date      : Jun 2008
 *
 * Tool_Installer language dictionnary : English
*/
$this->trads['mod_tool_installer_title'] = 'Site installer';
$this->trads['mod_tool_installer_desc'] = 'Site installer';

/* check interface */
$this->trads['mod_tool_installer_camyksconfigcheck'] = 'Checking CaMykS system';
$this->trads['mod_tool_installer_siteconfigcheck'] = 'Checking configuration file';
$this->trads['mod_tool_installer_databasecheck'] = 'Checking database';
$this->trads['mod_tool_installer_symlinkscheck'] = 'Checking access rights and symbolic links';
$this->trads['mod_tool_installer_pluginscheck'] = 'Checking required plugins';

$this->trads['mod_tool_installer_symlinkfound'] = 'Link "%s" found';
$this->trads['mod_tool_installer_configvalue'] = 'Value "%s"';

$this->trads['mod_tool_installer_ok'] = 'OK';
$this->trads['mod_tool_installer_notok'] = 'No';
$this->trads['mod_tool_installer_error'] = 'invalide';
$this->trads['mod_tool_installer_notfound'] = 'Absent';
$this->trads['mod_tool_installer_oldversion'] = 'Incompatible version';

$this->trads['mod_tool_installer_availability'] = 'Availability';
$this->trads['mod_tool_installer_installationmode'] = 'Installation mode';

$this->trads['mod_tool_installer_sitename_error'] = 'The "site name" value should match the website folder name.';
$this->trads['mod_tool_installer_url_error'] = 'The "URL" field cannot be empty.';
$this->trads['mod_tool_installer_adminentry_error'] = 'The entry point to the admin section must be accessible.<br/> The default setting is "admin.php".';
$this->trads['mod_tool_installer_database_name_error'] = 'The "database name" value cannot be empty.';
$this->trads['mod_tool_installer_page_maxmodules_error'] = 'The "maximum number of modules per page" value must be positive.';
$this->trads['mod_tool_installer_database_connection'] = 'Connection';
$this->trads['mod_tool_installer_database_connection_failed'] = 'The connection to the database engine failed.';
$this->trads['mod_tool_installer_database_db'] = 'Database';
$this->trads['mod_tool_installer_database_dbdoesntexist'] = 'The database does not exist.';
$this->trads['mod_tool_installer_write_rights'] = 'Write permissions';

$this->trads['mod_tool_installer_install'] = 'Install';

$this->trads['mod_tool_installer_database_created'] = 'Database created';
$this->trads['mod_tool_installer_module_x_installed'] = 'Module "%s" installed;';
$this->trads['mod_tool_installer_input_x_installed'] = 'Input "%s" installed;';
$this->trads['mod_tool_installer_theme_x_installed'] = 'Theme "%s" installed;';
$this->trads['mod_tool_installer_template_x_installed'] = 'Template "%s" installed;';
$this->trads['mod_tool_installer_symlink_x_created'] = 'Link "%s" created;';
$this->trads['mod_tool_installer_installation_done'] = 'Installation complete';
$this->trads['mod_tool_installer_open_admin'] = 'Access to the admin section';
?>