<?php
/**
 * @brief Tool_Installer Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @file plugin/module/Tool_InfoBar/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Aug 2007
 * @date Modification: May 2019
 * @copyright 2007 - 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_tool_installer_title'] = 'Installation du site';
$this->trads['mod_tool_installer_desc'] = 'Installation du site';

/* SSL mode values */
$this->trads['mod_tool_installer_sslmode_default'] = 'Par d&eacute;faut (choix de l\'utilisateur)';
$this->trads['mod_tool_installer_sslmode_auto'] = 'Automatique (SSL utilis&eacute; si disponible)';
$this->trads['mod_tool_installer_sslmode_forced'] = 'Forc&eacute;';
$this->trads['mod_tool_installer_sslmode_none'] = 'Forc&eacute; sans SSL';

/* mobile mode values */
$this->trads['mod_tool_installer_mobilemode_none'] = 'Aucune';
$this->trads['mod_tool_installer_mobilemode_responsive'] = 'Affichage adaptatif';
$this->trads['mod_tool_installer_mobilemode_dedicated'] = 'Affichage d&eacute;di&eacute;';

/* welcome */
$this->trads['mod_tool_installer_welcome_title'] = 'Bienvenue sur';
$this->trads['mod_tool_installer_start_installation'] = 'D&eacute;marrer l\'installation';

/* utilities texts */
$this->trads['mod_tool_installer_no_selected_theme'] = 'Aucun';
$this->trads['mod_tool_installer_no_selected_template'] = 'Aucun';

/* configuration */
$this->trads['mod_tool_installer_formtitle_configuration'] = 'Configuration';
$this->trads['mod_tool_installer_formtitle_website'] = 'Site internet';
$this->trads['mod_tool_installer_formitem_title'] = 'Titre : ';
$this->trads['mod_tool_installer_formitem_version'] = 'Version : ';
$this->trads['mod_tool_installer_formitem_encoding'] = 'Encodage : ';
$this->trads['mod_tool_installer_formitem_author'] = 'Auteur : ';
$this->trads['mod_tool_installer_formitem_company'] = 'Soci&eacute;t&eacute; : ';
$this->trads['mod_tool_installer_formtitle_admin'] = 'Espace d\'administration';
$this->trads['mod_tool_installer_formitem_languages'] = 'Langues disponibles : ';
$this->trads['mod_tool_installer_formitem_default_language'] = 'Langue par d&eacute;faut : ';
$this->trads['mod_tool_installer_formitem_editing_languages'] = 'Langues en &eacute;dition : ';
$this->trads['mod_tool_installer_formitem_theme'] = 'Th&egrave;me : ';
$this->trads['mod_tool_installer_formitem_ssl'] = 'SSL : ';
$this->trads['mod_tool_installer_formtitle_visitor'] = 'Espace visiteur';
$this->trads['mod_tool_installer_formitem_template'] = 'Template : ';
$this->trads['mod_tool_installer_formitem_maxmodules'] = 'Modules max. par page : ';
$this->trads['mod_tool_installer_formtitle_database'] = 'Base de donn&eacute;es';
$this->trads['mod_tool_installer_formitem_driver'] = 'Driver : ';
$this->trads['mod_tool_installer_formitem_host'] = 'H&ocirc;te : ';
$this->trads['mod_tool_installer_formitem_name'] = 'Nom de la base : ';
$this->trads['mod_tool_installer_formtitle_webmaster'] = 'Compte principal';
$this->trads['mod_tool_installer_formdesc_webmaster'] = 'Indiquez les informations de connection pour le compte administrateur principal.';
$this->trads['mod_tool_installer_formitem_login'] = 'Identifiant : ';
$this->trads['mod_tool_installer_formitem_password'] = 'Mot de passe : ';
$this->trads['mod_tool_installer_formtitle_options'] = 'Options';
$this->trads['mod_tool_installer_formitem_googleanalytics'] = 'Google Analytics : ';
$this->trads['mod_tool_installer_formitem_domain'] = 'Domaine : ';
$this->trads['mod_tool_installer_formdesc_domain'] = 'Laissez vide si n&eacute;cessaire';
$this->trads['mod_tool_installer_formitem_mobilemode'] = 'Adaptation mobile : ';
$this->trads['mod_tool_installer_continue'] = 'Continuer';

/* check interface */
$this->trads['mod_tool_installer_camyksconfigcheck'] = 'V&eacute;rification du syst&egrave;me CaMykS';
$this->trads['mod_tool_installer_siteconfigcheck'] = 'V&eacute;rification du fichier de configuration';
$this->trads['mod_tool_installer_databasecheck'] = 'V&eacute;rification de la base de donn&eacute;es';
$this->trads['mod_tool_installer_symlinkscheck'] = 'V&eacute;rification des droits d\'acc&egrave;s et des liens symboliques';
$this->trads['mod_tool_installer_pluginscheck'] = 'V&eacute;rification des plugins obligatoires';
$this->trads['mod_tool_installer_adminscheck'] = 'V&eacute;rification du compte principal';

$this->trads['mod_tool_installer_symlinkfound'] = 'Lien "%s" trouv&eacute;';
$this->trads['mod_tool_installer_configvalue'] = 'Valeur "%s"';

$this->trads['mod_tool_installer_ok'] = 'ok';
$this->trads['mod_tool_installer_notok'] = 'non';
$this->trads['mod_tool_installer_error'] = 'invalide';
$this->trads['mod_tool_installer_notfound'] = 'Absent';
$this->trads['mod_tool_installer_oldversion'] = 'Version incompatible';

$this->trads['mod_tool_installer_availability'] = 'Disponibilit&eacute;';
$this->trads['mod_tool_installer_installationmode'] = 'Mode d\'installation';

$this->trads['mod_tool_installer_sitename_error'] = 'Le nom du site doit &ecirc;tre identique au nom du dossier qui le contient.';
$this->trads['mod_tool_installer_url_error'] = 'L\'url du site ne doit pas &ecirc;tre vide.';
$this->trads['mod_tool_installer_adminentry_error'] = 'Le point d\'entr&eacute;e de la partie administrative doit &ecirc;tre accessible. Par d&eacute;faut, le fichier a pour nom "admin.php".';
$this->trads['mod_tool_installer_database_name_error'] = 'Le nom de la base de donn&eacute;e du site ne doit pas &ecirc;tre vide.';
$this->trads['mod_tool_installer_page_maxmodules_error'] = 'Cette valeur doit donc &ecirc;tre positive.';
$this->trads['mod_tool_installer_database_connection'] = 'Connexion';
$this->trads['mod_tool_installer_database_connection_failed'] = 'La connexion au moteur de base de donn&eacute;es a &eacute;chou&eacute;e.';
$this->trads['mod_tool_installer_database_db'] = 'Base';
$this->trads['mod_tool_installer_database_dbdoesntexist'] = 'La base n\'existe pas.';
$this->trads['mod_tool_installer_write_rights'] = 'Droits d\'&eacute;criture';

$this->trads['mod_tool_installer_masteraccount'] = 'Administrateur ';

/* install interface */
$this->trads['mod_tool_installer_install'] = 'Installer';

$this->trads['mod_tool_installer_database_created'] = 'Base de donn&eacute;es cr&eacute;&eacute;e';
$this->trads['mod_tool_installer_module_x_installed'] = 'Module "%s" install&eacute;';
$this->trads['mod_tool_installer_input_x_installed'] = 'Input "%s" install&eacute;';
$this->trads['mod_tool_installer_theme_x_installed'] = 'Th&egrave;me "%s" install&eacute;';
$this->trads['mod_tool_installer_template_x_installed'] = 'Template "%s" install&eacute;';
$this->trads['mod_tool_installer_symlink_x_created'] = 'Lien "%s" cr&eacute;&eacute;';
$this->trads['mod_tool_installer_installation_done'] = 'Installation termin&eacute;e';
$this->trads['mod_tool_installer_open_admin'] = 'Acc&eacute;der &agrave; l\'administration du site';

/* installation errors */
$this->trads['mod_tool_installer_installation_error_cantwriteconfigfile'] = 'Impossible d\'&eacute;crire le fichier de configuration.';
?>
