<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		    : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a
 * Object Version	: 1.0
 * Object Type	    : Plugin / Module Dictionnary
 * Creation Date	: Sep 2009
 * Last Modif Date	: Sep 2009
 *
 * Admin_DocumentManager english dictionnary
*/
$this->trads['mod_admin_documentmanager_title'] = 'Documents';
$this->trads['mod_admin_documentmanager_desc'] = 'Manage files used in web pages';

/* rights */
$this->trads['mod_admin_documentmanager_addfile'] = 'Add';
$this->trads['mod_admin_documentmanager_removefile'] = 'Delete';
$this->trads['mod_admin_documentmanager_alterstructure'] = 'Modify file tree';
?>