<?php
/**
 * @brief Admin_DocumentManager Module french dictionnary.
 * @details Plugin / Module layout
 * @file plugin/module/Admin_DocumentManager/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jun 2007
 * @date Modification: Apr 2019
 * @copyright 2007 - 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_documentmanager_title'] = 'Documents';
$this->trads['mod_admin_documentmanager_desc'] = 'Gestion des fichiers (images, documents, ...)';

/* Permissions */
$this->trads['mod_admin_documentmanager_addfile'] = 'Ajouter';
$this->trads['mod_admin_documentmanager_removefile'] = 'Supprimer';
$this->trads['mod_admin_documentmanager_alterstructure'] = 'Modifier l\'arborescence';
?>
