<?php
/**
 * @brief CrispChat Input english dictionary
 * @details Plugin / Input Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jul 2020
 * @date Modification: Mar 2021
 * @copyright 2020 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* configuration */
$this->trads['input_crispchat_formtitle_params'] = 'Parameters';
$this->trads['input_crispchat_formitem_websiteid'] = 'Website ID: ';

/* cookie management */
$this->trads['input_crispchat_cookie_title'] = 'CrispChat';
$this->trads['input_crispchat_cookie_purpose'] = 'Live chat with website managers.';
?>
