<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		    : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0b
 * Object Version	: 1.0
 * Object Type      : Plugin / Module Dictionnary
 * Creation Date	: Oct 2005
 * Last Modif Date  : Feb 2016
 *
 * Tool_ControlPanel language dictionnary : French 
 */

$this->trads['mod_tool_controlpanel_title'] = 'Panneau de contr&ocirc;le';
$this->trads['mod_tool_controlpanel_desc'] = 'Menu principal des fonctionnalit&eacute;s dans la partie Administrative du site.';
$this->trads['mod_tool_controlpanel_adminhome'] = 'Accueil Admin';
$this->trads['mod_tool_controlpanel_gcontent'] = 'Gestion du contenu';
$this->trads['mod_tool_controlpanel_gconfiguration'] = 'Outils de configuration';
$this->trads['mod_tool_controlpanel_gother'] = 'Autres';
$this->trads['mod_tool_controlpanel_gusers'] = 'Gestion des utilisateurs';
$this->trads['mod_tool_controlpanel_gmonitoring'] = 'Outils de surveillance';
$this->trads['mod_tool_controlpanel_ghelpers'] = 'Outils d\'aide';
$this->trads['mod_tool_controlpanel_gspecific'] = 'Outils &amp; contenus sp&eacute;cifiques';
$this->trads['mod_tool_controlpanel_gdevel'] = 'Outils de d&eacute;veloppement';
$this->trads['mod_tool_controlpanel_gpersonal'] = 'Informations personnelles';
$this->trads['mod_tool_controlpanel_icon'] = 'Ic&ocirc;ne : %s';
?>
