<?php
/**
 * @brief Tool_ControlPanel Module english dictionnary
 * @details Plugin / Module Dictionnary
 * @file plugin/module/Tool_ControlPanel/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Fev 2008
 * @date Modification: May 2019
 * @copyright 2008 - 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_tool_controlpanel_title'] = 'Control panel';
$this->trads['mod_tool_controlpanel_desc'] = 'Hub of the admin section.';
$this->trads['mod_tool_controlpanel_adminhome'] = 'Admin home';
$this->trads['mod_tool_controlpanel_gcontent'] = 'Content management';
$this->trads['mod_tool_controlpanel_gother'] = 'Others';
$this->trads['mod_tool_controlpanel_gusers'] = 'Accounts management';
$this->trads['mod_tool_controlpanel_gconfiguration'] = 'Configuration tools';
$this->trads['mod_tool_controlpanel_gmonitoring'] = 'Monitoring tools';
$this->trads['mod_tool_controlpanel_ghelpers'] = 'Help tools';
$this->trads['mod_tool_controlpanel_gspecific'] = 'Specific tools &amp; contents';
$this->trads['mod_tool_controlpanel_gdevel'] = 'Development tools';
$this->trads['mod_tool_controlpanel_gpersonal'] = 'Personal information';
?>
