<?php
/**
 * @brief MoneticoPaiement Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/MoneticoPaiement/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Apr 2018
 * @date Modification: Apr 2018
 * @copyright 2018 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['input_moneticopaiement_error_transactionparamsnotdefined'] = 'Les param&egrave;tres de transaction n\'ont pas &eacute;t&eacute; d&eacute;finis.';
?>
