<?php
/**
 * @brief MoneticoPaiement Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Apr 2018
 * @date Modification: Sep 2020
 * @copyright 2018 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* Operation mode list */
$this->trads['input_moneticopaiement_mode_test'] = 'Test';
$this->trads['input_moneticopaiement_mode_live'] = 'Live';

/* Config */
$this->trads['input_moneticopaiement_formtitle_operation'] = 'Operation';
$this->trads['input_moneticopaiement_formitem_mode'] = 'Mode: ';
$this->trads['input_moneticopaiement_formitem_companycode'] = 'Company code: ';
$this->trads['input_moneticopaiement_formitem_countrycode'] = 'Country code: ';

$this->trads['input_moneticopaiement_formtitle_testkeys'] = 'Test mode';
$this->trads['input_moneticopaiement_formtitle_livekeys'] = 'Live mode';
$this->trads['input_moneticopaiement_formitem_tpeid'] = 'TPE identifier: ';
$this->trads['input_moneticopaiement_formitem_key'] = 'Security key: ';

/* site */
$this->trads['input_moneticopaiement_redirectobankmessage'] = 'You will be redirected to the banking service.';
$this->trads['input_moneticopaiement_redirectobankmessage2'] = 'If not, <a href="%s" class="%s">click here</a>.';
$this->trads['input_moneticopaiement_error_transactionparamsnotdefined'] = 'Transaction parameters are not defined.';
?>
