<?php
/**
 * @brief Admin_GenericEmailingManager module, english dictionary.
 * @details Plugin, Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.9
 * @date Creation: Feb 2021
 * @date Modification: Nov 2022
 * @copyright 2021 - 2022 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_genericemailingmanager_title'] = 'E-mailings';
$this->trads['mod_admin_genericemailingmanager_desc'] = 'Manage contacts and mailings';

/* module rights */
$this->trads['mod_admin_genericemailingmanager_read_data'] = 'Data reading';
$this->trads['mod_admin_genericemailingmanager_edit_data'] = 'Data editing';
$this->trads['mod_admin_genericemailingmanager_read_emailings'] = 'E-mailings reading';
$this->trads['mod_admin_genericemailingmanager_edit_emailings'] = 'E-mailings editing';
$this->trads['mod_admin_genericemailingmanager_send_emailings'] = 'E-mailings sending';
$this->trads['mod_admin_genericemailingmanager_config'] = 'Configuration';

/* object titles */
$this->trads['mod_admin_genericemailingmanager_contact'] = 'Contact';
$this->trads['mod_admin_genericemailingmanager_contacts'] = 'Contacts';

$this->trads['mod_admin_genericemailingmanager_emailing'] = 'E-mailing';
$this->trads['mod_admin_genericemailingmanager_emailings'] = 'E-mailings';

/* emailing generic values */
$this->trads['mod_admin_genericemailingmanager_emailings_all'] = 'Tous';

/* emailing status values */
$this->trads['mod_admin_genericemailingmanager_emailingstatus_opened'] = 'Opened';
$this->trads['mod_admin_genericemailingmanager_emailingstatus_started'] = 'Initiated';
$this->trads['mod_admin_genericemailingmanager_emailingstatus_done'] = 'Done';

/* emailing status values */
$this->trads['mod_admin_genericemailingmanager_emailingsstatus_opened'] = 'Opened';
$this->trads['mod_admin_genericemailingmanager_emailingsstatus_started'] = 'Initiated';
$this->trads['mod_admin_genericemailingmanager_emailingsstatus_done'] = 'Done';

/* contact generic values */
$this->trads['mod_admin_genericemailingmanager_contacts_all'] = 'All';
$this->trads['mod_admin_genericemailingmanager_contactgroup_all'] = 'All';
$this->trads['mod_admin_genericemailingmanager_contactgroup_none'] = 'None';
$this->trads['mod_admin_genericemailingmanager_contactgroup_other'] = 'Other...';

/* contact status values */
$this->trads['mod_admin_genericemailingmanager_contactstatus_disabled'] = 'Disabled';
$this->trads['mod_admin_genericemailingmanager_contactstatus_subscribed'] = 'Subscribed';
$this->trads['mod_admin_genericemailingmanager_contactstatus_unsubscribed'] = 'Unsubscribed';
$this->trads['mod_admin_genericemailingmanager_contactstatus_invalid'] = 'Invalid';
$this->trads['mod_admin_genericemailingmanager_contactstatus_test'] = 'Test';

/* contact source values */
$this->trads['mod_admin_genericemailingmanager_contactsource_internal'] = 'Internal';
$this->trads['mod_admin_genericemailingmanager_contactsource_internaltest'] = 'Internal - tests';

/* contacts status values */
$this->trads['mod_admin_genericemailingmanager_contactsstatus_disabled'] = 'Disabled';
$this->trads['mod_admin_genericemailingmanager_contactsstatus_subscribed'] = 'Subscribed';
$this->trads['mod_admin_genericemailingmanager_contactsstatus_unsubscribed'] = 'Unsubscribed';
$this->trads['mod_admin_genericemailingmanager_contactsstatus_invalid'] = 'Invalid';
$this->trads['mod_admin_genericemailingmanager_contactsstatus_test'] = 'Tests';

/* admin main : contacts tab */
$this->trads['mod_admin_genericemailingmanager_addnewcontact'] = 'Add a contact';
$this->trads['mod_admin_genericemailingmanager_editcontact'] = 'Edit contact';
$this->trads['mod_admin_genericemailingmanager_deletecontact'] = 'Delete contact';
$this->trads['mod_admin_genericemailingmanager_deletecontactmessage'] = 'Are you sur to want to delete this contact? This action can\'t be undone.';
$this->trads['mod_admin_genericemailingmanager_formitem_search'] = 'Search: ';

/* admin main : emailings tab */
$this->trads['mod_admin_genericemailingmanager_addnewemailing'] = 'Add an e-mailing';
$this->trads['mod_admin_genericemailingmanager_previewemailing'] = 'Preview this e-mailing';
$this->trads['mod_admin_genericemailingmanager_viewemailing'] = 'View this e-mailing';
$this->trads['mod_admin_genericemailingmanager_editemailing'] = 'Edit this e-mailing';
$this->trads['mod_admin_genericemailingmanager_deleteemailing'] = 'Delete this e-mailing';
$this->trads['mod_admin_genericemailingmanager_deleteemailingmessage'] = 'Are you sur to want to delete this e-mailing? This action can\'t be undone.';

/* admin main : config tab  / edit configuration */
$this->trads['mod_admin_genericemailingmanager_configuration'] = 'Configuration';
$this->trads['mod_admin_genericemailingmanager_formtitle_unsubscribe'] = 'Unsubscribing';
$this->trads['mod_admin_genericemailingmanager_formitem_backpage'] = 'Back page: ';
$this->trads['mod_admin_genericemailingmanager_properties'] = 'Properties';
$this->trads['mod_admin_genericemailingmanager_select_sitepage'] = 'Select a page from website';

/* admin edit generic content */
$this->trads['mod_admin_genericemailingmanager_tabproperties'] = 'Properties';

/* admin view emailing : menu */
$this->trads['mod_admin_genericemailingmanager_menutitle'] = 'E-Mailing';
$this->trads['mod_admin_genericemailingmanager_contactsexport'] = 'Export contacts (.xls)';
$this->trads['mod_admin_genericemailingmanager_contactsexportxlsx'] = 'Export contacts (.xlsx)';
$this->trads['mod_admin_genericemailingmanager_contactsimport'] = 'Import contacts (.xlsx)';
$this->trads['mod_admin_genericemailingmanager_resultsexport'] = 'Export r&eacute;sultats (.xls)';

/* admin edit/view emailing */
$this->trads['mod_admin_genericemailingmanager_emailingnew'] = 'New e-mailing';
$this->trads['mod_admin_genericemailingmanager_emailingid'] = 'E-mailing #%s';
$this->trads['mod_admin_genericemailingmanager_formitem_cdate'] = 'Creation date: ';
$this->trads['mod_admin_genericemailingmanager_formitem_sdate'] = 'Send begin date: ';
$this->trads['mod_admin_genericemailingmanager_formitem_edate'] = 'Send end date: ';
$this->trads['mod_admin_genericemailingmanager_formitem_contactstatus'] = 'Target contacts: ';
$this->trads['mod_admin_genericemailingmanager_formitem_contactgroup'] = ' - Group: ';
$this->trads['mod_admin_genericemailingmanager_group_x'] = 'Group %s';
$this->trads['mod_admin_genericemailingmanager_formitem_secondsign'] = 'Second signature: ';

/* admin edit emailing : advanced tab */
$this->trads['mod_admin_genericemailingmanager_tabadvanced'] = 'Advanced parameters';
$this->trads['mod_admin_genericemailingmanager_formtitle_headers'] = 'E-mail headers';
$this->trads['mod_admin_genericemailingmanager_formitem_envelopeemail'] = '"Return-Path" e-mail: ';
$this->trads['mod_admin_genericemailingmanager_formitem_includelistunsub'] = '"List Unsubscribe" link:';
$this->trads['mod_admin_genericemailingmanager_formtitle_sending'] = 'Sending';
$this->trads['mod_admin_genericemailingmanager_formitem_sendinginterval'] = 'Delay between two sendings: ';

$this->trads['mod_admin_genericemailingmanager_formtitle_emailcontent'] = 'E-mail';
$this->trads['mod_admin_genericemailingmanager_formitem_content'] = 'Content: ';
$this->trads['mod_admin_genericemailingmanager_formitem_sendername'] = 'Sender - Name: ';
$this->trads['mod_admin_genericemailingmanager_formitem_senderemail'] = 'Sender - E-mail: ';
$this->trads['mod_admin_genericemailingmanager_formitem_replytoname'] = 'Reply-to - Name: ';
$this->trads['mod_admin_genericemailingmanager_formitem_replytoemail'] = 'Reply-to - E-mail: ';
$this->trads['mod_admin_genericemailingmanager_formitem_images'] = 'Pictures: ';
$this->trads['mod_admin_genericemailingmanager_formtitle_attachedimages'] = 'Attaches pictures';
$this->trads['mod_admin_genericemailingmanager_formitem_contentimage'] = 'Picture "%s"';
$this->trads['mod_admin_genericemailingmanager_reset_emailing'] = 'Reset';
$this->trads['mod_admin_genericemailingmanager_formitem_sender'] = 'Sender: ';
$this->trads['mod_admin_genericemailingmanager_formitem_replyto'] = 'Replay-to: ';
$this->trads['mod_admin_genericemailingmanager_formitem_unsubscribed'] = 'Unsubcribed: ';
$this->trads['mod_admin_genericemailingmanager_formitem_invalid'] = 'Invalid: ';

/* admin view emailing : sending tab */
$this->trads['mod_admin_genericemailingmanager_tabsending'] = 'Sending';
$this->trads['mod_admin_genericemailingmanager_formitem_approxemailtosend'] = 'Approximate number of sendings: ';
$this->trads['mod_admin_genericemailingmanager_formitem_alreadysent'] = 'Already sent: ';
$this->trads['mod_admin_genericemailingmanager_formitem_remainingtosend'] = 'Remaining to send: ';
$this->trads['mod_admin_genericemailingmanager_action_startsending'] = 'Start sending';
$this->trads['mod_admin_genericemailingmanager_action_continuesending'] = 'Continue sending';
$this->trads['mod_admin_genericemailingmanager_formitem_totalsent'] = 'E-mails sent: ';
$this->trads['mod_admin_genericemailingmanager_formitem_totalsucceededsent'] = 'Succeded sendings: ';
$this->trads['mod_admin_genericemailingmanager_formitem_totalopened'] = 'Opened e-mails: ';
$this->trads['mod_admin_genericemailingmanager_formitem_totalclicks'] = 'Total clicks: ';

/* admin view emailing : details tab */
$this->trads['mod_admin_genericemailingmanager_tabdetails'] = 'Details';
$this->trads['mod_admin_genericemailingmanager_sending'] = 'Sending';
$this->trads['mod_admin_genericemailingmanager_opening'] = 'Opening';
$this->trads['mod_admin_genericemailingmanager_firstclick'] = 'First click';
$this->trads['mod_admin_genericemailingmanager_clicks'] = 'Clicks';
$this->trads['mod_admin_genericemailingmanager_deleteemail'] = 'Delete sending results';
$this->trads['mod_admin_genericemailingmanager_deleteemailmessage'] = 'Are you sur to want to delete this sending results? This action can\'t be undone.';
$this->trads['mod_admin_genericemailingmanager_markemailasinvalid'] = 'Mark this e-mail address as invalid.';

/* admin send emailing */
$this->trads['mod_admin_genericemailingmanager_emailsending'] = 'E-mail sending';

$this->trads['mod_admin_genericemailingmanager_initialise_emailing'] = 'Sending initialisation started.';
$this->trads['mod_admin_genericemailingmanager_initialise_emailing_done'] = 'Sending initialisation done.';
$this->trads['mod_admin_genericemailingmanager_initialise_emailing_failure'] = 'Sending initialisation failed.';
$this->trads['mod_admin_genericemailingmanager_send_email'] = 'Sending in progress';
$this->trads['mod_admin_genericemailingmanager_send_email_done'] = 'Sending done.';
$this->trads['mod_admin_genericemailingmanager_send_email_failure'] = 'Sending failed.';
$this->trads['mod_admin_genericemailingmanager_finalise_emailing'] = 'Sending finalisation started.';
$this->trads['mod_admin_genericemailingmanager_finalise_emailing_done'] = 'Sending finalisation done.';
$this->trads['mod_admin_genericemailingmanager_emailstobesent'] = '%s e-mails will be sent.';
$this->trads['mod_admin_genericemailingmanager_continue_sending'] = 'Continue sending';

/* admin edit contact */
$this->trads['mod_admin_genericemailingmanager_contactnew'] = 'New contact';
$this->trads['mod_admin_genericemailingmanager_contactid'] = 'Contact #%s';
$this->trads['mod_admin_genericemailingmanager_formitem_group'] = 'Group: ';
$this->trads['mod_admin_genericemailingmanager_formitem_denomination'] = 'Denomination: ';

/* admin save configuration */
$this->trads['mod_admin_genericemailingmanager_config_saved'] = 'Configuration saved.';
$this->trads['mod_admin_genericemailingmanager_config_notsaved'] = 'An error has occured while saving configuration.';

/* admin save emailing */
$this->trads['mod_admin_genericemailingmanager_emailing_saved'] = 'E-mailing saved.';
$this->trads['mod_admin_genericemailingmanager_emailing_notsaved'] = 'An error has occured while saving this e-mailing.';

/* admin delete emailing */
$this->trads['mod_admin_genericemailingmanager_emailing_deleted'] = 'E-mailing deleted.';
$this->trads['mod_admin_genericemailingmanager_emailing_notdeleted'] = 'An error has occured while deleteing this emailing.';

/* admin reset emailing */
$this->trads['mod_admin_genericemailingmanager_emailing_reseted'] = 'E-mailing reset.';
$this->trads['mod_admin_genericemailingmanager_emailing_notreseted'] = 'An error has occured while reseting this emailing.';

/* admin delete email results */
$this->trads['mod_admin_genericemailingmanager_email_deleted'] = 'Sending results deleted.';
$this->trads['mod_admin_genericemailingmanager_email_notdeleted'] = 'An error has occured while deleteing this sending results.';

/* admin mark email as invalid */
$this->trads['mod_admin_genericemailingmanager_email_markedasinvalid'] = 'E-mail address marked as invalid.';

/* admin save contact */
$this->trads['mod_admin_genericemailingmanager_contact_saved'] = 'Contact saved.';
$this->trads['mod_admin_genericemailingmanager_contact_notsaved'] = 'An error has occured while saving this contact.';
$this->trads['mod_admin_genericemailingmanager_contact_saveerror_alreadyexists'] = 'Database already contains a contact with the same email address. <br />Contact has not been saved.';
$this->trads['mod_admin_genericemailingmanager_contact_saveerror_emailinvalid'] = 'E-mail is invalid. <br />Contact has not been saved.';
$this->trads['mod_admin_genericemailingmanager_contact_saveerror_namesinvalid'] = 'Names must be filled in. <br />Contact has not been saved.';

/* admin delete contact */
$this->trads['mod_admin_genericemailingmanager_contact_deleted'] = 'Contact deleted.';
$this->trads['mod_admin_genericemailingmanager_contact_notdeleted'] = 'An error has occured while deleting this contact.';

/* admin import contacts */
$this->trads['mod_admin_genericemailingmanager_contacstimport'] = 'Contact importation';
$this->trads['mod_admin_genericemailingmanager_formitem_yourfile'] = 'Your contact file: ';
$this->trads['mod_admin_genericemailingmanager_xlinesfound'] = '%s lines found.';

$this->trads['mod_admin_genericemailingmanager_formtitle_colmapping'] = 'Column mapping';
$this->trads['mod_admin_genericemailingmanager_formtitle_listquicklook'] = 'List quicklook';
$this->trads['mod_admin_genericemailingmanager_formitem_loadfromline'] = 'Import from line:';
$this->trads['mod_admin_genericemailingmanager_column'] = 'Column';
$this->trads['mod_admin_genericemailingmanager_value'] = 'Value';
$this->trads['mod_admin_genericemailingmanager_field'] = 'Field';
$this->trads['mod_admin_genericemailingmanager_parameters'] = 'Parameters';
$this->trads['mod_admin_genericemailingmanager_none'] = 'None';

$this->trads['mod_admin_genericemailingmanager_initialise_importation'] = 'Importation initialisation started.';
$this->trads['mod_admin_genericemailingmanager_initialise_importation_done'] = 'Importation initialisation done.';
$this->trads['mod_admin_genericemailingmanager_import_contact'] = 'Importation of a new contact started.';
$this->trads['mod_admin_genericemailingmanager_import_contact_done'] = 'Importation of contact %s done.';
$this->trads['mod_admin_genericemailingmanager_import_contact_failure'] = 'An error has occured while importing data from %s: ';
$this->trads['mod_admin_genericemailingmanager_finalise_importation'] = 'Importation finalisation started.';
$this->trads['mod_admin_genericemailingmanager_finalise_importation_done'] = 'Importation finalisation done.';
$this->trads['mod_admin_genericemailingmanager_contactstobeimported'] = '%s contacts will be imported.';

$this->trads['mod_admin_genericemailingmanager_importation_error_cannotfindfile'] = 'No file found.';
$this->trads['mod_admin_genericemailingmanager_importation_error_cannotfindxlsreader'] = 'XLSX reader not found.';
$this->trads['mod_admin_genericemailingmanager_importation_error_cannotopenfile'] = 'Can\'t open file or file is not a XLSX file.';
$this->trads['mod_admin_genericemailingmanager_importation_error_filehasnodata'] = 'File has no data.';

/* request contact export */
$this->trads['mod_admin_genericemailingmanager_status'] = 'Status';
$this->trads['mod_admin_genericemailingmanager_group'] = 'Group';
$this->trads['mod_admin_genericemailingmanager_denomination'] = 'Denomination';
?>
