<?php
/**
 * @brief Admin_User Module french dictionnary.
 * @details Plugin / Module layout
 * @file plugin/module/Admin_User/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jun 2005
 * @date Modification: Mar 2019
 * @copyright 2005 - 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_user_title'] = 'Utilisateurs';
$this->trads['mod_admin_user_desc'] = 'Gestion des utilisateurs';

/* users status list */
$this->trads['mod_admin_user_users_all'] = 'Tous';
$this->trads['mod_admin_user_users_disabled'] = 'D&eacute;sactiv&eacute;s';
$this->trads['mod_admin_user_users_enabled'] = 'Activ&eacute;s';

/* admin list */
$this->trads['mod_admin_user_formitem_search'] = 'Rechercher : ';
$this->trads['mod_admin_user_adduser'] = 'Ajouter un utilisateur';
$this->trads['mod_admin_user_select'] = 'S&eacute;lectionnez un utilisateur.';
$this->trads['mod_admin_user_doesn_t_exist'] = 'L\'utilisateur n\'existe pas.';
$this->trads['mod_admin_user_pwd_conf'] = 'Confirmation';
$this->trads['mod_admin_user_pwd_change'] = 'Modifier le mot de passe : ';
$this->trads['mod_admin_user_is_active'] = 'Est activ&eacute;';

/* list translations */
$this->trads['mod_admin_user_viewuser'] = 'Afficher cet utilisateur';
$this->trads['mod_admin_user_edituser'] = 'Editer cet utilisateur';
$this->trads['mod_admin_user_deleteuser'] = 'Supprimer cet utilisateur';
$this->trads['mod_admin_user_personalinfos'] = 'Informations Personnelles';
$this->trads['mod_admin_user_rights'] = 'Droits';
$this->trads['mod_admin_user_user'] = 'Utilisateur';

/* message */
$this->trads['mod_admin_user_usermodificationnotallowed'] = 'Vous n\'&ecirc;tes pas autoris&eacute; &agrave; modifier cet utilisateur.';

/* errors */
$this->trads['mod_admin_user_erroremptylogin'] = 'L\'identifiant ne doit pas &ecirc;tre vide.';
$this->trads['mod_admin_user_errorbadlogin'] = 'L\'identifiant contient des caract&egrave;res interdits.';
$this->trads['mod_admin_user_errorshortlogin'] = 'L\'identifiant doit &ecirc;tre compos&eacute; d\'au moins 3 caract&egrave;res.';
$this->trads['mod_admin_user_errorexistinglogin'] = 'Cet identifiant est d&eacute;j&agrave; utilis&eacute; pour un autre utilisateur';
$this->trads['mod_admin_user_erroremptymail'] = 'L\'e-mail ne doit pas &ecirc;tre vide.';
$this->trads['mod_admin_user_errorbadmail'] = 'L\'e-mail doit &ecirc;tre valide.';
$this->trads['mod_admin_user_erroremptypwd'] = 'Le mot de passe ne doit pas &ecirc;tre vide.';
$this->trads['mod_admin_user_errorshortpwd'] = 'Le mot de passe doit &ecirc;tre compos&eacute; d\'au moins 3 caract&egrave;res.';
$this->trads['mod_admin_user_errorconfpwd'] = 'Le mot de passe ne se confirme pas.';

?>
