<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a2
 * Object Version	: 1.0
 * Object Type	        : Plugin / Module Dictionnary
 * Create Date	       	: Oct 2005
 * Last Modif Date	: Oct 2005
 * 
 * Dummy module english dictionnary
 */
$this->trads['mod_dummy_title'] = 'Dummy Module';
$this->trads['mod_dummy_desc'] = 'Display a "Dummy" text';
$this->trads['mod_dummy_admin_text'] = 'No setting available for this module.';
$this->trads['mod_dummy_site_title'] = 'Test module';
$this->trads['mod_dummy_site_text'] = 'This is a test module, it just display this text.';
?>
