<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a2
 * Object Version	: 1.0
 * Object Type	        : Plugin / Module Dictionnary
 * Create Date	       	: Oct 2005
 * Last Modif Date	: Oct 2005
 * 
 * Dummy module french dictionnary
 */
$this->trads['mod_dummy_title'] = 'Dummy Module';
$this->trads['mod_dummy_desc'] = 'Affiche un "Dummy" texte';
$this->trads['mod_dummy_admin_text'] = 'Ce module n\'est pas configurable.';
$this->trads['mod_dummy_site_title'] = 'Module de test';
$this->trads['mod_dummy_site_text'] = 'Ceci est un module d\'exemple, il n\'affiche que ce texte.';
?>
