<?php
/**
 * @brief Content_GenericArticle module, french dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Sep 2007
 * @date Modification: Jul 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericarticle_title'] = 'Articles';
$this->trads['mod_content_genericarticle_desc'] = 'Affiche un article';

/* admin tabs */
$this->trads['mod_content_genericarticle_tabgeneral'] = 'Propri&eacute;t&eacute;s';

/* layouts */
$this->trads['mod_content_genericarticle_layout'] = 'Layout';
$this->trads['mod_content_genericarticle_layout_classic'] = 'Classique';
$this->trads['mod_content_genericarticle_layout_classicbox'] = 'Classique encadr&eacute;';
$this->trads['mod_content_genericarticle_layout_notebox'] = 'Encadr&eacute;, note en exergue';
$this->trads['mod_content_genericarticle_layout_contentbox'] = 'Encadr&eacute;, contenu en exergue ';
$this->trads['mod_content_genericarticle_layout_custom'] = 'Custom';

/* admin */
$this->trads['mod_content_genericarticle_itemname'] = 'Nom : ';
$this->trads['mod_content_genericarticle_itemtitle'] = 'Titre : ';
$this->trads['mod_content_genericarticle_itemsubtitle'] = 'Sous-titre : ';
$this->trads['mod_content_genericarticle_itemheader'] = 'Chapeau : ';
$this->trads['mod_content_genericarticle_itemcontent'] = 'Contenu : ';
$this->trads['mod_content_genericarticle_itemnote'] = 'Note : ';
$this->trads['mod_content_genericarticle_itemdate'] = 'Date : ';
$this->trads['mod_content_genericarticle_itemauthor'] = 'Auteur : ';
$this->trads['mod_content_genericarticle_itemlayout'] = 'Affichage : ';

/* site */
$this->trads['mod_content_genericarticle_siteauthor'] = 'Par %s';
?>
