<?php
/**
 * @brief Admin_GlobalHelp Module english dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Mar 2009
 * @date Modification: Jan 2021
 * @copyright 2009 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_globalhelp_title'] = 'Global Help';
$this->trads['mod_admin_globalhelp_desc'] = 'Display help files';

$this->trads['mod_admin_globalhelp_withengine'] = 'Help files available with %s';
$this->trads['mod_admin_globalhelp_withmodules'] = 'Help files available with modules.';
$this->trads['mod_admin_globalhelp_withsite'] = 'Help files available with website';
$this->trads['mod_admin_globalhelp_nohelpfound'] = 'No help file found';
$this->trads['mod_admin_globalhelp_viewhelp'] = 'Display help';
?>
