<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a2
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Creation Date	: Fev 2007
 * Last Modif Date	: Mar 2009
 *
 * Admin_GlobalHelp module french dictionnary
*/
$this->trads['mod_admin_globalhelp_title'] = 'Aide Globale';
$this->trads['mod_admin_globalhelp_desc'] = 'Affiche les aides';
/* tabs titles */
$this->trads['mod_admin_globalhelp_withengine'] = 'Aides disponibles avec %s';
$this->trads['mod_admin_globalhelp_withmodules'] = 'Aides disponibles avec les modules';
$this->trads['mod_admin_globalhelp_withsite'] = 'Aides disponibles avec le site';
$this->trads['mod_admin_globalhelp_nohelpfound'] = 'Aucun fichier d\'aide trouv&eacute;.';
$this->trads['mod_admin_globalhelp_viewhelp'] = 'Afficher l\'aide';
?>
