<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a2
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Creation Date	: Mar 2009
 * Last Modif Date	: Mar 2009
 *
 * Admin_GlobalHelp module english dictionnary
*/
$this->trads['mod_admin_globalhelp_title'] = 'Global Help';
$this->trads['mod_admin_globalhelp_desc'] = 'Display help files';
/* tabs titles */
$this->trads['mod_admin_globalhelp_withengine'] = 'Help files available with %s';
$this->trads['mod_admin_globalhelp_withmodules'] = 'Help files available with modules.';
$this->trads['mod_admin_globalhelp_withsite'] = 'Help files available with website';
$this->trads['mod_admin_globalhelp_nohelpfound'] = 'No help file found';
$this->trads['mod_admin_globalhelp_viewhelp'] = 'Display help';
?>
