<?php
/**
 * @brief TinyMCEv3 Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/TinyMCEv3/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jul 2008
 * @date Modification: Jul 2018
 * @copyright 2008 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['input_tinymcev3_config_advanced'] = 'Advanced';
$this->trads['input_tinymcev3_config_default'] = 'Default';
$this->trads['input_tinymcev3_config_classic'] = 'Classic';
$this->trads['input_tinymcev3_config_simple'] = 'Simple';
$this->trads['input_tinymcev3_config_textual'] = 'Text';
$this->trads['input_tinymcev3_config_flash'] = 'Flash';
$this->trads['input_tinymcev3_config_classic_cs'] = 'Classic - Client-side';
$this->trads['input_tinymcev3_config_simple_cs'] = 'Simple - Client-side';
?>
