<?php
/**
 * @brief PayZenPayment Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/PayZenPayment/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Dec 2018
 * @date Modification: Dec 2018
 * @copyright 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* mode values */
$this->trads['input_payzenpayment_mode_test'] = 'Test';
$this->trads['input_payzenpayment_mode_production'] = 'Live';

/* configuration */
$this->trads['input_payzenpayment_formtitle_operation'] = 'Operation';
$this->trads['input_payzenpayment_formitem_mode'] = 'Mode: ';

$this->trads['input_payzenpayment_formtitle_bankkeys'] = 'Bank keys';
$this->trads['input_payzenpayment_formitem_test'] = 'Test: ';
$this->trads['input_payzenpayment_formitem_live'] = 'Live: ';

$this->trads['input_payzenpayment_formtitle_bankconfiguration'] = 'Bank configuration';
$this->trads['input_payzenpayment_formitem_site'] = 'Shop: ';
$this->trads['input_payzenpayment_formitem_hashmode'] = 'Hash: ';

/* site */
$this->trads['input_payzenpayment_redirectobankmessage'] = 'You will be redirected to the banking service.';
?>
