<?php
/**
 * @brief GenericPageController Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/GenericPageController/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jan 2018
 * @date Modification: Apr 2018
 * @copyright 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['input_genericpagecontroller_gotonextpage'] = 'Go to next page';
$this->trads['input_genericpagecontroller_gotopreviouspage'] = 'Go to previous page';
$this->trads['input_genericpagecontroller_isfirstpage'] = 'This is the first page';
$this->trads['input_genericpagecontroller_islastpage'] = 'This is the last page';
?>
