<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Dictionnary
 * Creation Date	: Jan 2018
 * Last Modif Date	: Jan 2018
 *
 * GenericPageController language dictionnary : English
 */
$this->trads['input_genericpagecontroller_gotonextpage'] = 'Go to next page';
$this->trads['input_genericpagecontroller_gotopreviouspage'] = 'Go to previous page';
$this->trads['input_genericpagecontroller_isfirstpage'] = 'This is the first page';
$this->trads['input_genericpagecontroller_islastpage'] = 'This is the last page';
?>
