<?php
/**
 * @brief Languages english dictionary.
 * @details Engine / Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Jun 2021
 * @date Modification: Jun 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['languagescript_arabic'] = 'Arabic';
$this->trads['languagescript_armenian'] = 'Armenian';
$this->trads['languagescript_avestan'] = 'Avestan';
$this->trads['languagescript_balinese'] = 'Balinese';
$this->trads['languagescript_bamum'] = 'Bamum';
$this->trads['languagescript_batak'] = 'Batak';
$this->trads['languagescript_bengali'] = 'Bengali';
$this->trads['languagescript_bopomofo'] = 'Bopomofo';
$this->trads['languagescript_brahmi'] = 'Brahmi';
$this->trads['languagescript_braille'] = 'Braille';
$this->trads['languagescript_buginese'] = 'Buginese';
$this->trads['languagescript_buhid'] = 'Buhid';
$this->trads['languagescript_canadian_aboriginal'] = 'Canadian Aboriginal';
$this->trads['languagescript_carian'] = 'Carian';
$this->trads['languagescript_chakma'] = 'Chakma';
$this->trads['languagescript_cham'] = 'Cham';
$this->trads['languagescript_cherokee'] = 'Cherokee';
$this->trads['languagescript_common'] = 'Common';
$this->trads['languagescript_coptic'] = 'Coptic';
$this->trads['languagescript_cuneiform'] = 'Cuneifore';
$this->trads['languagescript_cypriot'] = 'Cypriot';
$this->trads['languagescript_cyrillic'] = 'Cyrillic';
$this->trads['languagescript_deseret'] = 'Deseret';
$this->trads['languagescript_devanagari'] = 'Devanagari';
$this->trads['languagescript_egyptian_hieroglyphs'] = 'Egyptian Hieroglyphs';
$this->trads['languagescript_ethiopic'] = 'Ethiopic';
$this->trads['languagescript_georgian'] = 'Georgian';
$this->trads['languagescript_glagolitic'] = 'Glagolitic';
$this->trads['languagescript_gothic'] = 'Gothic';
$this->trads['languagescript_greek'] = 'Greek';
$this->trads['languagescript_gujarati'] = 'Gujarati';
$this->trads['languagescript_gurmukhi'] = 'Gurmukhi';
$this->trads['languagescript_han'] = 'Han';
$this->trads['languagescript_hangul'] = 'Hangul';
$this->trads['languagescript_hanunoo'] = 'Hanunoo';
$this->trads['languagescript_hebrew'] = 'Hebrew';
$this->trads['languagescript_hiragana'] = 'Hiragana';
$this->trads['languagescript_imperial_aramaic'] = 'Imperial Aramaic';
$this->trads['languagescript_inherited'] = 'Inherited';
$this->trads['languagescript_inscriptional_pahlavi'] = 'Inscriptional Pahlavi';
$this->trads['languagescript_inscriptional_parthian'] = 'Inscriptional Parthian';
$this->trads['languagescript_javanese'] = 'Javanese';
$this->trads['languagescript_kaithi'] = 'Kaithi';
$this->trads['languagescript_kannada'] = 'Kannada';
$this->trads['languagescript_katakana'] = 'Katakana';
$this->trads['languagescript_kayah_li'] = 'Kayah Li';
$this->trads['languagescript_kharoshthi'] = 'Kharoshthi';
$this->trads['languagescript_khmer'] = 'Khmer';
$this->trads['languagescript_lao'] = 'Lao';
$this->trads['languagescript_latin'] = 'Latin';
$this->trads['languagescript_lepcha'] = 'Lepcha';
$this->trads['languagescript_limbu'] = 'Limbu';
$this->trads['languagescript_linear_b'] = 'Linear B';
$this->trads['languagescript_lisu'] = 'Lisu';
$this->trads['languagescript_lycian'] = 'Lycian';
$this->trads['languagescript_lydian'] = 'Lydian';
$this->trads['languagescript_malayalam'] = 'Malayalam';
$this->trads['languagescript_mandaic'] = 'Mandaic';
$this->trads['languagescript_meetei_mayek'] = 'Meetei Mayek';
$this->trads['languagescript_meroitic_cursive'] = 'Meroitic Cursive';
$this->trads['languagescript_meroitic_hieroglyphs'] = 'Meroitic Hieroglyphs';
$this->trads['languagescript_miao'] = 'Miao';
$this->trads['languagescript_mongolian'] = 'Mongolian';
$this->trads['languagescript_myanmar'] = 'Myanmar';
$this->trads['languagescript_new_tai_lue'] = 'New Tai Lue';
$this->trads['languagescript_nko'] = 'Nko';
$this->trads['languagescript_ogham'] = 'Ogham';
$this->trads['languagescript_old_italic'] = 'Old Italic';
$this->trads['languagescript_old_persian'] = 'Old Persian';
$this->trads['languagescript_old_south_arabian'] = 'Old South Arabic';
$this->trads['languagescript_old_turkic'] = 'Old Turkic';
$this->trads['languagescript_ol_chiki'] = 'Ol Chiki';
$this->trads['languagescript_oriya'] = 'Oriya';
$this->trads['languagescript_osmanya'] = 'Osmanya';
$this->trads['languagescript_phags_pa'] = 'Phags Pa';
$this->trads['languagescript_phoenician'] = 'Phoenician';
$this->trads['languagescript_rejang'] = 'Rejang';
$this->trads['languagescript_runic'] = 'Runic';
$this->trads['languagescript_samaritan'] = 'Samaritain';
$this->trads['languagescript_saurashtra'] = 'Saurashtra';
$this->trads['languagescript_sharada'] = 'Sharada';
$this->trads['languagescript_shavian'] = 'Shavian';
$this->trads['languagescript_sinhala'] = 'Sinhala';
$this->trads['languagescript_sora_sompeng'] = 'Sora Sompeng';
$this->trads['languagescript_sundanese'] = 'Sundanese';
$this->trads['languagescript_syloti_nagri'] = 'Syloti Nagri';
$this->trads['languagescript_syriac'] = 'Syriac';
$this->trads['languagescript_tagalog'] = 'Tagalog';
$this->trads['languagescript_tagbanwa'] = 'Tagbanwa';
$this->trads['languagescript_tai_le'] = 'Tai Le';
$this->trads['languagescript_tai_tham'] = 'Tai Tham';
$this->trads['languagescript_tai_viet'] = 'Tai Viet';
$this->trads['languagescript_takri'] = 'Takri';
$this->trads['languagescript_tamil'] = 'Tamil';
$this->trads['languagescript_telugu'] = 'Telugu';
$this->trads['languagescript_thaana'] = 'Thaana';
$this->trads['languagescript_thai'] = 'Thai';
$this->trads['languagescript_tibetan'] = 'Tibetan';
$this->trads['languagescript_tifinagh'] = 'Tifinagh';
$this->trads['languagescript_ugaritic'] = 'Ugaritic';
$this->trads['languagescript_vai'] = 'Vai';
$this->trads['languagescript_yi'] = 'Yi';
?>
