<?php
/**
 * @brief Admin_Statistics Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: May 2007
 * @date Modification: Sep 2020
 * @copyright 2007 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_statistics_title'] = 'Statistiques du site';
$this->trads['mod_admin_statistics_desc'] = 'Visiteurs, pages vues, ...';

/* main layout */
$this->trads['mod_admin_statistics_objects'] = 'Objets';
$this->trads['mod_admin_statistics_computeagain'] = 'Recalculer';
$this->trads['mod_admin_statistics_settings'] = 'Configuration';
$this->trads['mod_admin_statistics_status_disabled'] = 'D&eacute;sactiv&eacute;';
$this->trads['mod_admin_statistics_status_enabled'] = 'Activ&eacute;';
$this->trads['mod_admin_statistics_status_simple'] = 'Simple';
$this->trads['mod_admin_statistics_status_complete'] = 'Complet(d&eacute;conseill&eacute;)';

/* config message */
$this->trads['mod_admin_statistics_configuration_saved'] = 'Configuration en cours de sauvegarde...';
$this->trads['mod_admin_statistics_configuration_notsaved'] = 'Une erreur est survenue pendant la sauvegarde de la configuration.';

/* rights */
$this->trads['mod_admin_statistics_rights_configuration'] = 'Configuration';

/* edit settings */
$this->trads['mod_admin_statistics_enabledstatistics'] = 'Statistiques activ&eacute;es';
$this->trads['mod_admin_statistics_filteredips'] = 'Adresses IP filtr&eacute;es';

/* tabs */
$this->trads['mod_admin_statistics_tabdisplay'] = 'Affichage';
$this->trads['mod_admin_statistics_tabdetail'] = 'D&eacute;tail';
$this->trads['mod_admin_statistics_taboptions'] = 'Options';

/* stat items */
$this->trads['mod_admin_statistics_stat_webbots'] = 'Moteurs de recherche';
$this->trads['mod_admin_statistics_stat_webbots_main'] = 'page(s) parcourue(s) par les moteurs de recherche';

$this->trads['mod_admin_statistics_stat_webtools'] = 'Outils Internet';
$this->trads['mod_admin_statistics_stat_webtools_main'] = 'page(s) vue(s) via un outil Internet';

/* stat desc */
$this->trads['mod_admin_statistics_firstrecorddate'] = 'Premier enregistrement le %s';

/* stat type : none */
$this->trads['mod_admin_statistics_selectanobjecttoview'] = 'S&eacute;lectionnez la statistique que vous d&eacute;sirez voir.';

/* stat type : single */
$this->trads['mod_admin_statistics_todaysrecords'] = 'Liste des enregistrements ajout&eacute;s aujourd\'hui.';
$this->trads['mod_admin_statistics_yesterdaysrecords'] = 'Liste des enregistrements ajout&eacute;s hier.';
$this->trads['mod_admin_statistics_fromxtoyrecords'] = 'Liste des enregistrements du %s au %s.';
$this->trads['mod_admin_statistics_dayxrecords'] = 'Liste des enregistrements le %s.';
$this->trads['mod_admin_statistics_lastxrecords'] = 'Liste des %s derniers enregistrements.';

/* stat type : mixed */
$this->trads['mod_admin_statistics_total'] = 'Total : ';
$this->trads['mod_admin_statistics_view_detail'] = 'D&eacute;tail';
$this->trads['mod_admin_statistics_thexlastdays'] = 'Les %s derniers jours';
$this->trads['mod_admin_statistics_thexlastmonths'] = 'Les %s derniers mois';
$this->trads['mod_admin_statistics_thexlastyears'] = 'Les %s derni&egrave;res ann&eacute;es';

/* options */
$this->trads['mod_admin_statistics_valueselection'] = 'Afficher les valeurs pour';
$this->trads['mod_admin_statistics_thelastxstats'] = 'Les %s derniers enregistrements';
$this->trads['mod_admin_statistics_colorselection'] = 'Couleurs';
$this->trads['mod_admin_statistics_coloralternate1'] = 'Alternance 1 : ';
$this->trads['mod_admin_statistics_coloralternate2'] = 'Alternance 2 : ';
$this->trads['mod_admin_statistics_value3selection'] = 'Afficher seulement';
$this->trads['mod_admin_statistics_thefirstxstats'] = 'Les %s premiers enregistrements';
?>
