<?php
/**
 * @brief Admin_Statistics Module english dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Sep 2009
 * @date Modification: Sep 2020
 * @copyright 2007 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['mod_admin_statistics_title'] = 'Website Statistics';
$this->trads['mod_admin_statistics_desc'] = 'Visits, page views, ...';

/* main layout */
$this->trads['mod_admin_statistics_objects'] = 'Objects';
$this->trads['mod_admin_statistics_computeagain'] = 'Refresh';
$this->trads['mod_admin_statistics_settings'] = 'Configuration';
$this->trads['mod_admin_statistics_status_disabled'] = 'Disabled';
$this->trads['mod_admin_statistics_status_enabled'] = 'Enabled';
$this->trads['mod_admin_statistics_status_simple'] = 'Simple';
$this->trads['mod_admin_statistics_status_complete'] = 'Complete(unrecommended)';

/* config message */
$this->trads['mod_admin_statistics_configuration_saved'] = 'Configuration saved.';
$this->trads['mod_admin_statistics_configuration_notsaved'] = 'An error has occured while saving the configuration';

/* rights */
$this->trads['mod_admin_statistics_rights_configuration'] = 'Configuration';

/* edit config */
$this->trads['mod_admin_statistics_enabledstatistics'] = 'Enabled statistics';
$this->trads['mod_admin_statistics_filteredips'] = 'Filtered IP addresses';

/* tabs */
$this->trads['mod_admin_statistics_tabdisplay'] = 'Display';
$this->trads['mod_admin_statistics_tabdetail'] = 'Detail';
$this->trads['mod_admin_statistics_taboptions'] = 'Options';

/* stat items */
$this->trads['mod_admin_statistics_stat_webbots'] = 'Web search engine';
$this->trads['mod_admin_statistics_stat_webbots_main'] = 'indexed page(s) by web search engines';

$this->trads['mod_admin_statistics_stat_webtools'] = 'Internet tools';
$this->trads['mod_admin_statistics_stat_webtools_main'] = 'viewed page(s) with Internet tools';

/* stat desc */
$this->trads['mod_admin_statistics_firstrecorddate'] = 'First record on %s';

/* stat type: none */
$this->trads['mod_admin_statistics_selectanobjecttoview'] = 'Select statistic to display';

/* stat type: single */
$this->trads['mod_admin_statistics_todaysrecords'] = 'Today records';
$this->trads['mod_admin_statistics_yesterdaysrecords'] = 'Yesterday records';
$this->trads['mod_admin_statistics_fromxtoyrecords'] = 'Records from %s to %s.';
$this->trads['mod_admin_statistics_dayxrecords'] = 'Records on %s.';
$this->trads['mod_admin_statistics_lastxrecords'] = 'Last %s records';

/* stat type: mixed */
$this->trads['mod_admin_statistics_total'] = 'Total: ';
$this->trads['mod_admin_statistics_view_detail'] = 'Detail';
$this->trads['mod_admin_statistics_thexlastdays'] = 'Last %s days';
$this->trads['mod_admin_statistics_thexlastmonths'] = 'Last %s monthes';
$this->trads['mod_admin_statistics_thexlastyears'] = 'Last %s years';

/* options */
$this->trads['mod_admin_statistics_valueselection'] = 'Display results for';
$this->trads['mod_admin_statistics_thelastxstats'] = 'Last %s records';
$this->trads['mod_admin_statistics_colorselection'] = 'Colors';
$this->trads['mod_admin_statistics_coloralternate1'] = 'Color 1: ';
$this->trads['mod_admin_statistics_coloralternate2'] = 'Color 2: ';
$this->trads['mod_admin_statistics_value3selection'] = 'Display only';
$this->trads['mod_admin_statistics_thefirstxstats'] = 'First %s records';
?>
