<?php
/**
 * @brief Admin_MonitoringUserAgentChecker Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @file plugin/module/Admin_MonitoringUserAgentChecker/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.3
 * @date Creation: Dec 2014
 * @date Modification: Dec 2018
 * @copyright 2014 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_monitoringuseragentchecker_title'] = 'Agents Utilisateurs';
$this->trads['mod_admin_monitoringuseragentchecker_desc'] = 'Gestion des agents utilisateurs';

$this->trads['mod_admin_monitoringuseragentchecker_desc1'] = '1 agent utilisateur non v&eacute;rifi&eacute;';
$this->trads['mod_admin_monitoringuseragentchecker_descx'] = '%s agents utilisateurs non v&eacute;rifi&eacute;s';

/* record platfrom type */
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_handheld'] = 'Mobile';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_tablet'] = 'Tablette';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_computer'] = 'Ordinateur';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_tvset'] = 'T&eacute;l&eacute;vision';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_bot'] = 'Robot';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_tool'] = 'Outil';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_hack'] = 'Hack';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_fake'] = 'Fausse visite';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_other'] = 'Autre';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_undefined'] = 'Ind&eacute;termin&eacute;';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type_all'] = 'Tous';

$this->trads['mod_admin_monitoringuseragentchecker_platform_format_handheld'] = 'Mobile';
$this->trads['mod_admin_monitoringuseragentchecker_platform_format_tablet'] = 'Tablette';
$this->trads['mod_admin_monitoringuseragentchecker_platform_format_desktop'] = 'Ordinateur';

/* record status type */
$this->trads['mod_admin_monitoringuseragentchecker_record_all'] = 'Tous';
$this->trads['mod_admin_monitoringuseragentchecker_recordstatus_notverified'] = 'Non v&eacute;rifi&eacute;';
$this->trads['mod_admin_monitoringuseragentchecker_recordstatus_verified'] = 'V&eacute;rifi&eacute;';

$this->trads['mod_admin_monitoringuseragentchecker_recordsstatus_notverified'] = 'Non v&eacute;rifi&eacute;s';
$this->trads['mod_admin_monitoringuseragentchecker_recordsstatus_verified'] = 'V&eacute;rifi&eacute;s';

/* menus */
$this->trads['mod_admin_monitoringuseragentchecker_markitemsasverified'] = 'Marquer les &eacute;l&eacute;ments s&eacute;lectionn&eacute;s comme v&eacute;rifi&eacute;s';
$this->trads['mod_admin_monitoringuseragentchecker_validaterecordsmessage'] = 'Etes-vous s&ucirc;r de vouloir marquer ces agents utilisateurs comme v&eacute;rifi&eacute;s ?';

/* filters */
$this->trads['mod_admin_monitoringuseragentchecker_tabrecords'] = 'Agents utilisateurs';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_platform_type'] = 'Type : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_search'] = 'Recherche : ';
$this->trads['mod_admin_monitoringuseragentchecker_addnewrecord'] = 'Ajouter un agent utilisateur';

/* add poupup */
$this->trads['mod_admin_monitoringuseragentchecker_addpopupname'] = 'Ajouter un agent utilisateur';
$this->trads['mod_admin_monitoringuseragentchecker_addpopuptitle'] = 'Agents Utilisateurs';

/* list headers */
$this->trads['mod_admin_monitoringuseragentchecker_user_agent'] = 'Agent utilisateur';
$this->trads['mod_admin_monitoringuseragentchecker_platform_type'] = 'Type';
$this->trads['mod_admin_monitoringuseragentchecker_nvisits'] = 'Visites';
$this->trads['mod_admin_monitoringuseragentchecker_lvisits'] = 'Dern. Visite';

/* view record */
$this->trads['mod_admin_monitoringuseragentchecker_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_user_agent'] = 'Agent utilisateur : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_platform_type'] = 'Type : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_nvisits'] = 'Nb. Visites : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_lvisits'] = 'Dern. Visite : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_nvisit'] = 'Nombre de visites : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_fvisit'] = 'Premi&egrave;re visite : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_lvisit'] = 'Derni&egrave;re visite : ';
$this->trads['mod_admin_monitoringuseragentchecker_formtitle_details'] = 'D&eacute;tails : ';
$this->trads['mod_admin_monitoringuseragentchecker_formtitle_infos'] = 'Infos visites : ';

/* client_getUAInfos vars */
$this->trads['mod_admin_monitoringuseragentchecker_formitem_platform_company'] = 'Editeur : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_platform_model'] = 'Mod&egrave;le : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_platform_format'] = 'Format : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_system_title'] = 'Syst&egrave;me : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_system_version'] = 'Version du Syst&egrave;me : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_browser_title'] = 'Navigateur : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_browser_version'] = 'Version du Navigateur : ';
$this->trads['mod_admin_monitoringuseragentchecker_markasverified'] = 'Marquer comme v&eacute;rifi&eacute;';
$this->trads['mod_admin_monitoringuseragentchecker_markasunverified'] = 'Marquer comme non-v&eacute;rifi&eacute;';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_bot_title'] = 'Nom du robot : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_tool_title'] = 'Nom de l\'outil : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_bot_url'] = 'URL : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_engine_title'] = 'Nom du moteur : ';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_engine_url'] = 'URL :';
$this->trads['mod_admin_monitoringuseragentchecker_formitem_info'] = 'Informations :';

/* list buttons */
$this->trads['mod_admin_monitoringuseragentchecker_viewrecord'] = 'Voir cet agent utilisateur';
$this->trads['mod_admin_monitoringuseragentchecker_editrecord'] = 'Editer cet agent utilisateur';
$this->trads['mod_admin_monitoringuseragentchecker_deleterecord'] = 'Supprimer cet agent utilisateur';
$this->trads['mod_admin_monitoringuseragentchecker_deleterecordmessage'] = 'Etes-vous s&ucirc;r de vouloir supprimer cet agent utilisateur ? Cette action est irr&eacute;versible.';

/* messsages */
$this->trads['mod_admin_monitoringuseragentchecker_recordnew'] = 'Nouvel agent utilisateur';
$this->trads['mod_admin_monitoringuseragentchecker_recordid'] = 'Agent utilisateur n&deg;%s';
$this->trads['mod_admin_monitoringuseragentchecker_record_saved'] = 'Agent utilisateur enregistr&eacute;.';
$this->trads['mod_admin_monitoringuseragentchecker_record_notsaved'] = 'Une erreur est survenue lors de l\'enregistrement de cet agent utilisateur.';
$this->trads['mod_admin_monitoringuseragentchecker_record_updated'] = 'Agent utilisateur mis &agrave; jour.';
$this->trads['mod_admin_monitoringuseragentchecker_record_notupdated'] = 'Une erreur est survenue lors de la mise &agrave; jour de cet agent utilisateur.';
$this->trads['mod_admin_monitoringuseragentchecker_record_duplicated'] = 'Cet agent utilisateur existe d&eacute;j&agrave;.';
$this->trads['mod_admin_monitoringuseragentchecker_record_deleted'] = 'Agent utilisateur supprim&eacute;.';
$this->trads['mod_admin_monitoringuseragentchecker_record_notdeleted'] = 'Une erreur est survenue lors de la suppression de cet agent utilisateur.';
$this->trads['mod_admin_monitoringuseragentchecker_records_updated'] = 'Agents utilisateurs mis &agrave; jour.';
$this->trads['mod_admin_monitoringuseragentchecker_records_notupdated'] = 'Une erreur est survenue lors de la mise &agrave; jour de ces agents utilisateurs.';
?>
