<?php
/**
 * @brief Admin_SystemLogManager Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @file plugin/module/Admin_SystemLogManager/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jun 2018
 * @date Modification: Jun 2018
 * @copyright 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['mod_admin_systemlogmanager_title'] = 'Journaux Internes';
$this->trads['mod_admin_systemlogmanager_desc'] = 'Historique des actions';

/* objects */
$this->trads['mod_admin_systemlogmanager_logs'] = 'Journaux';

/* logging perdiod values */
$this->trads['mod_admin_systemlogmanager_loggingperiod_daily'] = 'tous les jours';
$this->trads['mod_admin_systemlogmanager_loggingperiod_weekly'] = 'toutes les semaines';
$this->trads['mod_admin_systemlogmanager_loggingperiod_monthly'] = 'tous les mois';

/* configuration */
$this->trads['mod_admin_systemlogmanager_configuration'] = 'Configuration';
$this->trads['mod_admin_systemlogmanager_formitem_rotate'] = 'Rotation ';
$this->trads['mod_admin_systemlogmanager_formitem_keeplast'] = 'Conserver les ';
$this->trads['mod_admin_systemlogmanager_formdesc_keeplast'] = ' derniers';

/* admin : main */
$this->trads['mod_admin_systemlogmanager_refresh'] = 'Rafra&icirc;chir';
$this->trads['mod_admin_systemlogmanager_download'] = 'T&eacute;l&eacute;charger';
$this->trads['mod_admin_systemlogmanager_filter'] = 'Filtrer';
$this->trads['mod_admin_systemlogmanager_reset_filter'] = 'R&eacute;initialiser le filtre';
$this->trads['mod_admin_systemlogmanager_selectalog'] = 'Veuillez s&eacute;lectionner un journal.';
$this->trads['mod_admin_systemlogmanager_selectafile'] = 'Veuillez s&eacute;lectionner un fichier.';
$this->trads['mod_admin_systemlogmanager_noresultforthisfilter'] = 'Aucun r&eacute;sultat pour ce filtre.';

/* admin : save config */
$this->trads['mod_admin_systemlogmanager_config_saved'] = 'Configuration enregistr&eacute;.';
$this->trads['mod_admin_systemlogmanager_config_notsaved'] = 'Une erreur est survenue lors de l\'enregistrement de la configuration.';

?>
