<?php
/**
 * @brief Tool_Login Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @file plugin/module/Tool_Login/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.1.1
 * @date Creation: Sep 2005
 * @date Modification: Jun 2020
 * @copyright 2005 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['mod_tool_login_title'] = 'Identification';
$this->trads['mod_tool_login_desc'] = 'Identification pour acceder &agrave; la partie administrative du site.';

/* admin menu */
$this->trads['mod_tool_login_logout'] = 'D&eacute;connexion';

/* log in frame */
$this->trads['mod_tool_login_loginfailed'] = 'Identification erron&eacute;e';
$this->trads['mod_tool_login_formitem_language'] = 'Langue : ';
$this->trads['mod_tool_login_access'] = 'Acc&eacute;der';

/* log out frame */
$this->trads['mod_tool_login_logout_message'] = 'D&eacute;connexion en cours...';

/* stats */
$this->trads['mod_tool_login_stat_adminlogin'] = 'Connexions admin.';
$this->trads['mod_tool_login_stat_adminloginfailed'] = 'Connexions admin. erron&eacute;es';
?>
