<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version       : 1.0a
 * Object Version       : 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Creation Date        : Sep 2005
 * Last Modif Date      : Dec 2009
 *
 * Tool_Login language dictionnary : French
*/
$this->trads['mod_tool_login_title'] = 'Identification';
$this->trads['mod_tool_login_desc'] = 'Identification pour acceder &agrave; la partie administrative du site.';

$this->trads['mod_tool_login_loginfailed'] = 'Identification erron&eacute;e';
$this->trads['mod_tool_login_formitem_language'] = 'Langue : ';
$this->trads['mod_tool_login_access'] = 'Acc&eacute;der';

/* stats */
$this->trads['mod_tool_login_stat_adminlogin'] = 'Connexions admin.';
$this->trads['mod_tool_login_stat_adminloginfailed'] = 'Connexions admin. erron&eacute;es';
?>