<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	    : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Module Dictionnary
 * Creation Date    : Jan 2008
 * Last Modif Date  : Dec 2010
 *
 * Tool_Disconnect english dictionnary
 */

$this->trads['mod_tool_disconnect_title'] = 'Log out';
$this->trads['mod_tool_disconnect_desc'] = 'Log out module';
$this->trads['mod_tool_disconnect_message'] = 'Disconnecting...';
$this->trads['mod_tool_disconnect_disconnect'] = 'Log out';
?>
