<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Oct 2005
 * Last Modif Date	: Jan 2008
 *
 * Tool_Disconnect french dictionnary
 */

$this->trads['mod_tool_disconnect_title'] = 'D&eacute;connection';
$this->trads['mod_tool_disconnect_desc'] = 'Module de d&eacute;connection';
$this->trads['mod_tool_disconnect_message'] = 'D&eacute;connection en cours...';
$this->trads['mod_tool_disconnect_disconnect'] = 'D&eacute;connection';
?>
