<?php
/**
 * @brief Content_GenericLegalMentions Module site definitions, english sub layout.
 * @details Plugin / Module layout
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Apr 2021
 * @date Modification: Apr 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
?>
<div id="LM-Annexe1" class="anchor" title="Appendix 1: Definitions"></div>

<h2 class="eTitle2">
    Appendix 1: Definitions
</h2>

<ul>
    <li class="eContent1">
        <span class="eContent2">Website</span>: he present website, the URL address of which is <?= $this->contentItem->get_websiteURL(); ?>.
    </li>

    <li class="eContent1">
        <span class="eContent2">Client</span>: all professionals or capable natural persons within the meaning of articles 1123 and following of the Civil Code, or legal entities, which visit the <span class="eContent2">Website</span> subject to the present general terms.
    </li>

<?php if (false): ?>
    <li>
        <span class="eContent2">Prestations et Services</span>: <?= $this->contentItem->get_editorFullName(); ?> met &agrave; disposition des <span class="eContent2">Clients</span>
    </li>
<?php endif; ?>

    <li>
        <span class="eContent2">Content</span>: All elements comprising the information present on the <span class="eContent2">Website</span>, and in particular the texts, images and videos.
    </li>

    <li>
        <span class="eContent2">Client data</span>: Called hereinafter &laquo; Data &raquo;, which corresponds to all personal data which may be held by the company Ideogram Design for management of your account, for management of customer relations and for analytical and statistical purposes.
    </li>

    <li>
        <span class="eContent2">User</span>: The Web surfer logging into and using the above-named <span class="eContent2">Website</span>.
    </li>

    <li>
        <span class="eContent2">Service provider:</span>: all professionals or capable natural persons within the meaning of articles 1123 and following of the Civil Code, or legal entities, which is or are responsible for creation of the above-named <span class="eContent2">Website</span>.
    </li>

    <li>
        <span class="eContent2">Personal Data</span>: &laquo; Data which enables, in any manner whatsoever, whether directly or indirectly, identification of the natural persons to which it applies &raquo; (article 4 of french law n&deg; 78-17 of 6 January 1978).
    </li>
</ul>
<p class="eContent1">
    The terms &laquo; personal data &raquo;, &laquo; person concerned &raquo;, &laquo; subcontractor &raquo; and &laquo; sensitive data &raquo; have the meanings defined by the General Data Protection Regulation (GDPR: n&deg; 2016-679).
</p>
<p class="eContent1">
    &nbsp;
</p>
