<?php
/**
 * @brief Content_GenericLegalMentions Module site lins, english sub layout.
 * @details Plugin / Module layout
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Apr 2021
 * @date Modification: Apr 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
?>
<div id="LM-Links" class="anchor" title="11. Links"></div>

<h2 class="eTitle2">
    11. Links
</h2>

<p class="eContent1">
    The <span class="eContent2">Website</span> <?= $this->contentItem->get_websiteURL(); ?> may contain links to other outside websites which are independent of <?= $this->contentItem->get_editorFullName(); ?>, and which have specific legal terms. <?= ucfirst($this->contentItem->get_editorFullName()); ?> has no control over the management of these sites, and declines all liability concerning the contents of their pages. Visiting of these sites, which are independent of <?= $this->contentItem->get_editorFullName(); ?>, is undertaken at the <span class="eContent2">User</span>'s sole liability.

</p>

<p class="eContent1">
    &nbsp;
</p>
