<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a2
 * Object Version	: 1.0
 * Object Type	        : Plugin / Module Help File
 * Create Date	       	: Oct 2007
 * Last Modif Date	: Mar 2009
 *
 * Admin_SecurityTools Module Help HTML File
 */
?>
<p class="eContent1">
Permet d'activer quelques &eacute;l&eacute;ments de s&eacute;curit&eacute; pour votre site web.
</p>
<p class="eContent1">
Les outils actuellement disponibles sont un filtre IP et un outil de sauvegarde, tout deux configurables.
</p>