<?php
/**
 * @brief Content_GenericMenu module, french dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jul 2007
 * @date Modification: May 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericmenu_title'] = 'Menu';
$this->trads['mod_content_genericmenu_desc'] = 'Affiche un menu bas&eacute; sur la structure des pages du site';

/* admin tabs */
$this->trads['mod_content_genericmenu_tabgeneral'] = 'Propri&eacute;t&eacute;s';

/* layouts */
$this->trads['mod_content_genericmenu_layout'] = 'Affichage : ';
$this->trads['mod_content_genericmenu_layout_horizontal_bottomlayers'] = 'Horizontal / menu en dessous';
$this->trads['mod_content_genericmenu_layout_vertical_rightlayers'] = 'Vertical / menu &agrave; droite';
$this->trads['mod_content_genericmenu_layout_vertical_leftlayers'] = 'Vertical / menu &agrave; gauche';
$this->trads['mod_content_genericmenu_layout_vertical_inline'] = 'Vertical / Colonne';
$this->trads['mod_content_genericmenu_layout_custom'] = 'Custom';

/* admin */
$this->trads['mod_content_genericmenu_itemname'] = 'Nom : ';
$this->trads['mod_content_genericmenu_root'] = 'Page racine : ';
$this->trads['mod_content_genericmenu_levelcount'] = 'Nombre de niveau : ';
?>
