<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Jul 2007
 * Last Modif Date	: Oct 2008
 *
 * Content_GenericMenu french dictionnary
*/
$this->trads['mod_content_genericmenu_title'] = 'Menu';
$this->trads['mod_content_genericmenu_desc'] = 'Affiche un menu bas&eacute; sur la structure des pages du site';

/* admin tabs */
$this->trads['mod_content_genericmenu_tabgeneral'] = 'Propri&eacute;t&eacute;s';

/* layouts */
$this->trads['mod_content_genericmenu_layout'] = 'Affichage : ';
$this->trads['mod_content_genericmenu_layout_horizontal_bottomlayers'] = 'Horizontal / menu en dessous';
$this->trads['mod_content_genericmenu_layout_vertical_rightlayers'] = 'Vertical / menu &agrave; droite';
$this->trads['mod_content_genericmenu_layout_vertical_leftlayers'] = 'Vertical / menu &agrave; gauche';
$this->trads['mod_content_genericmenu_layout_vertical_inline'] = 'Vertical / Colonne';
$this->trads['mod_content_genericmenu_layout_custom'] = 'Custom';

/* admin */
$this->trads['mod_content_genericmenu_itemname'] = 'Nom : ';
$this->trads['mod_content_genericmenu_root'] = 'Page racine : ';
$this->trads['mod_content_genericmenu_levelcount'] = 'Nombre de niveau : ';
?>