<?php
/**
 * @brief Content_GenericMenu module, english dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Oct 2008
 * @date Modification: May 2021
 * @copyright 2008 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericmenu_title'] = 'Menu';
$this->trads['mod_content_genericmenu_desc'] = 'Display menu based on site pages';

/* admin tabs */
$this->trads['mod_content_genericmenu_tabgeneral'] = 'Properties';

/* layouts */
$this->trads['mod_content_genericmenu_layout'] = 'Layout: ';
$this->trads['mod_content_genericmenu_layout_horizontal_bottomlayers'] = 'Horizontal / Layered menus under';
$this->trads['mod_content_genericmenu_layout_vertical_rightlayers'] = 'Vertical / Layered menus on the right';
$this->trads['mod_content_genericmenu_layout_vertical_leftlayers'] = 'Vertical / Layered menus on the left';
$this->trads['mod_content_genericmenu_layout_vertical_inline'] = 'Vertical / Column';
$this->trads['mod_content_genericmenu_layout_custom'] = 'Custom';

/* admin */
$this->trads['mod_content_genericmenu_itemname'] = 'Nom : ';
$this->trads['mod_content_genericmenu_root'] = 'Root page: ';
$this->trads['mod_content_genericmenu_levelcount'] = 'Levels displayed: ';
?>
