<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Oct 2008
 * Last Modif Date	: Oct 2008
 *
 * Content_GenericMenu english dictionnary
*/
$this->trads['mod_content_genericmenu_title'] = 'Menu';
$this->trads['mod_content_genericmenu_desc'] = 'Display menu based on site pages';

/* admin tabs */
$this->trads['mod_content_genericmenu_tabgeneral'] = 'Properties';

/* layouts */
$this->trads['mod_content_genericmenu_layout'] = 'Layout: ';
$this->trads['mod_content_genericmenu_layout_horizontal_bottomlayers'] = 'Horizontal / Layered menus under';
$this->trads['mod_content_genericmenu_layout_vertical_rightlayers'] = 'Vertical / Layered menus on the right';
$this->trads['mod_content_genericmenu_layout_vertical_leftlayers'] = 'Vertical / Layered menus on the left';
$this->trads['mod_content_genericmenu_layout_vertical_inline'] = 'Vertical / Column';
$this->trads['mod_content_genericmenu_layout_custom'] = 'Custom';

/* admin */
$this->trads['mod_content_genericmenu_itemname'] = 'Nom : ';
$this->trads['mod_content_genericmenu_root'] = 'Root page: ';
$this->trads['mod_content_genericmenu_levelcount'] = 'Levels displayed: ';
?>