<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Module Dictionnary
 * Creation Date    : Oct 2010
 * Last Modif Date  : Oct 2010
 *
 * Admin_CommunityAccountManager french dictionnary
*/
$this->trads['mod_admin_communityaccountmanager_title'] = 'Comptes visiteur';
$this->trads['mod_admin_communityaccountmanager_desc'] = 'Gestion des comptes';
$this->trads['mod_admin_communityaccountmanager_desc1'] = '1 compte est en attente de validation';
$this->trads['mod_admin_communityaccountmanager_descx'] = '%s comptes sont en attente de validation';

/* admin rights */
$this->trads['mod_admin_communityaccountmanager_rights_configuration'] = 'Configuration';
$this->trads['mod_admin_communityaccountmanager_rights_edit_account'] = 'Edition des comptes';
$this->trads['mod_admin_communityaccountmanager_rights_delete_account'] = 'Suppression des comptes';
$this->trads['mod_admin_communityaccountmanager_rights_edit_group'] = 'Edition des groupes';
$this->trads['mod_admin_communityaccountmanager_rights_delete_group'] = 'Suppression des groupes';

/* admin stats */
$this->trads['mod_admin_communityaccountmanager_stat_account_registration'] = 'Inscriptions';
$this->trads['mod_admin_communityaccountmanager_stat_account_registration_main'] = 'cr&eacute;ations de compte';
$this->trads['mod_admin_communityaccountmanager_stat_account_connection'] = 'Connexions';
$this->trads['mod_admin_communityaccountmanager_stat_account_connection_main'] = 'connexions &agrave; l\'espace r&eacute;serv&eacute;';

/* configuration registation status list */
$this->trads['mod_admin_communityaccountmanager_config_registrationstatus_closed'] = 'Ferm&eacute;es';
$this->trads['mod_admin_communityaccountmanager_config_registrationstatus_invitation'] = 'Sur invitation';
$this->trads['mod_admin_communityaccountmanager_config_registrationstatus_opened'] = 'Ouvertes';

/* configuration registration validation mode list */
$this->trads['mod_admin_communityaccountmanager_config_registrationvalidation_none'] = 'Aucune';
$this->trads['mod_admin_communityaccountmanager_config_registrationvalidation_email'] = 'Confirmation par e-mail';
$this->trads['mod_admin_communityaccountmanager_config_registrationvalidation_admin'] = 'Administrative';

/* configuration registration captcha list */
$this->trads['mod_admin_communityaccountmanager_config_registrationcaptcha_none'] = 'Aucun';
$this->trads['mod_admin_communityaccountmanager_config_registrationcaptcha_securimage'] = 'Securimage';

/* configuration login status list */
$this->trads['mod_admin_communityaccountmanager_config_loginstatus_closed'] = 'Ferm&eacute;es';
$this->trads['mod_admin_communityaccountmanager_config_loginstatus_limited'] = 'Limit&eacute;es (Administrateur)';
$this->trads['mod_admin_communityaccountmanager_config_loginstatus_opened'] = 'Ouvertes';

/* configuration login method list */
$this->trads['mod_admin_communityaccountmanager_config_loginmethod_full'] = 'Identifiant ou e-mail';
$this->trads['mod_admin_communityaccountmanager_config_loginmethod_email'] = 'E-mail';
$this->trads['mod_admin_communityaccountmanager_config_loginmethod_login'] = 'Identifiant';




/* single account status */
$this->trads['mod_admin_communityaccountmanager_accountstatus_inactive'] = 'Inactif';
$this->trads['mod_admin_communityaccountmanager_accountstatus_active'] = 'Activ&eacute;';
$this->trads['mod_admin_communityaccountmanager_accountstatus_banned'] = 'Banni';

/* multi account status */
$this->trads['mod_admin_communityaccountmanager_accountsstatus_all'] = 'Tous';
$this->trads['mod_admin_communityaccountmanager_accountsstatus_inactive'] = 'Inactifs';
$this->trads['mod_admin_communityaccountmanager_accountsstatus_active'] = 'Activ&eacute;s';
$this->trads['mod_admin_communityaccountmanager_accountsstatus_banned'] = 'Bannis';

/* single account types */
$this->trads['mod_admin_communityaccountmanager_accounttype_visitor'] = 'Visiteur';
$this->trads['mod_admin_communityaccountmanager_accounttype_advanced'] = 'Avanc&eacute;';
$this->trads['mod_admin_communityaccountmanager_accounttype_community'] = 'Membre d\'Qsim';

/* multi account types */
$this->trads['mod_admin_communityaccountmanager_accountstype_all'] = 'Tous';
$this->trads['mod_admin_communityaccountmanager_accountstype_visitor'] = 'Visiteurs';
$this->trads['mod_admin_communityaccountmanager_accountstype_advanced'] = 'Avanc&eacute;s';
$this->trads['mod_admin_communityaccountmanager_accountstype_community'] = 'Membres d\'community';

/* admin list */
$this->trads['mod_admin_communityaccountmanager_addnewaccount'] = 'Ajouter un compte';
$this->trads['mod_admin_communityaccountmanager_itempage'] = 'Page : ';
$this->trads['mod_admin_communityaccountmanager_headlogin'] = 'Identifiant';
$this->trads['mod_admin_communityaccountmanager_headname'] = 'Nom';
$this->trads['mod_admin_communityaccountmanager_headtype'] = 'Type';
$this->trads['mod_admin_communityaccountmanager_deleteaccountmessage'] = 'Etes vous s&ucirc;r de vouloir supprimer ce compte? Cette action est irr&eacute;versible.';
$this->trads['mod_admin_communityaccountmanager_editaccount'] = 'Editer ce compte';
$this->trads['mod_admin_communityaccountmanager_deleteaccount'] = 'Supprimer ce compte';

/* admin edit tabs */
$this->trads['mod_admin_communityaccountmanager_tabadmininfos'] = 'Informations administratives';
$this->trads['mod_admin_communityaccountmanager_tabpersonalinfos'] = 'Informations personnelles';
$this->trads['mod_admin_communityaccountmanager_taboptions'] = 'Options';

/* admin edit admin tab items */
$this->trads['mod_admin_communityaccountmanager_new_account_title'] = 'Ajouter un nouveau compte';
$this->trads['mod_admin_communityaccountmanager_edit_account_title'] = 'Editer le compte';
$this->trads['mod_admin_communityaccountmanager_accountnew'] = 'Nouveau compte';
$this->trads['mod_admin_communityaccountmanager_accountid'] = 'Compte n&deg;%s';
$this->trads['mod_admin_communityaccountmanager_formitem_changepassword'] = 'Changer de mot de passe : ';
$this->trads['mod_admin_communityaccountmanager_formitem_password'] = 'Mot de passe : ';
$this->trads['mod_admin_communityaccountmanager_formitem_confirm'] = 'Confirmation : ';
$this->trads['mod_admin_communityaccountmanager_formitem_registrationdate'] = 'Date d\'inscription : ';
$this->trads['mod_admin_communityaccountmanager_formitem_connectiondate'] = 'Derni&egrave;re connexion : ';
$this->trads['mod_admin_communityaccountmanager_formitem_ipaddresses'] = 'Adresses IP : ';
$this->trads['mod_admin_communityaccountmanager_formitem_securecode'] = 'Code s&eacute;curit&eacute; : ';
$this->trads['mod_admin_communityaccountmanager_formitem_company'] = 'Soci&eacute;t&eacute; : ';

/* admin message */
$this->trads['mod_admin_communityaccountmanager_account_saved'] = 'Compte en cours de sauvegarde...';
$this->trads['mod_admin_communityaccountmanager_account_notsaved'] = 'Une erreur est survenue, lors de la sauvegarde de ce compte.';

$this->trads['mod_admin_communityaccountmanager_account_deleted'] = 'Compte en cours de suppression...';
$this->trads['mod_admin_communityaccountmanager_account_notdeleted'] = 'Une erreur est survenue, lors de la sauvegarde de ce compte.';

?>
