<?php
/**
 * @brief Content_GenericGallery Module french dictionary.
 * @details Plugin, Module dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jul 2007
 * @date Modification: May 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericgallery_title'] = 'Galerie d\'image';
$this->trads['mod_content_genericgallery_desc'] = 'Affiche une galerie d\'image';

/* admin tabs */
$this->trads['mod_content_genericgallery_tabgeneral'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericgallery_tabimages'] = 'Images';

/* layouts */
$this->trads['mod_content_genericgallery_layout'] = 'Affichage : ';
$this->trads['mod_content_genericgallery_layout_box'] = 'Avec cadre (type %s)';
$this->trads['mod_content_genericgallery_layout_nobox'] = 'Sans cadre';

/* admin Smart Gallery configuration */
$this->trads['mod_content_genericgallery_itemname'] = 'Nom : ';
$this->trads['mod_content_genericgallery_theme'] = 'Th&egrave;me : ';
$this->trads['mod_content_genericgallery_thumb_width'] = 'Largeur des vignettes : ';
$this->trads['mod_content_genericgallery_thumb_height'] = 'Hauteur des vignettes : ';
$this->trads['mod_content_genericgallery_thumb_count'] = 'Nombre de vignette : ';
$this->trads['mod_content_genericgallery_image_width'] = 'Largeur des images : ';
$this->trads['mod_content_genericgallery_image_height'] = 'Hauteur des images : ';
$this->trads['mod_content_genericgallery_image_title'] = 'Afficher le titre : ';
$this->trads['mod_content_genericgallery_image_desc'] = 'Afficher la description : ';
$this->trads['mod_content_genericgallery_sliding_method'] = 'M&eacute;thode de glissement : ';
$this->trads['mod_content_genericgallery_sliding_accel'] = 'Acc&eacute;l&eacute;leration du glissement : ';
$this->trads['mod_content_genericgallery_sliding_speed'] = 'Vitesse du glissement : ';
$this->trads['mod_content_genericgallery_sliding_interval'] = 'Intervalle du glissement : ';
$this->trads['mod_content_genericgallery_addnewimage'] = 'Ajouter une image';
$this->trads['mod_content_genericgallery_editimage'] = 'Editer l\'image';
$this->trads['mod_content_genericgallery_deleteimage'] = 'Supprimer l\'image';
$this->trads['mod_content_genericgallery_deleteitemconfirm'] = 'Etes vous s&ucirc;r de vouloir supprimer cette image ? Cette action est irr&eacute;versible.';

/* admin Smart Gallery Item configuration */
$this->trads['mod_content_genericgallery_itemtitle'] = 'Titre : ';
$this->trads['mod_content_genericgallery_image'] = 'Image : ';
$this->trads['mod_content_genericgallery_thumb'] = 'Vignette : ';
$this->trads['mod_content_genericgallery_noimage'] = 'Aucune';
$this->trads['mod_content_genericgallery_maxfilesize'] = 'Taille max. : %s';
$this->trads['mod_content_genericgallery_description'] = 'Description : ';
$this->trads['mod_content_genericgallery_viewfile'] = 'Voir le fichier';
$this->trads['mod_content_genericgallery_deletefile'] = 'Supprimer le fichier';
?>
