<?php
/**
 * @brief Content_GenericSiteMap module, french dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jul 2008
 * @date Modification: Jul 2021
 * @copyright 2008 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericsitemap_title'] = 'Plan du site';
$this->trads['mod_content_genericsitemap_desc'] = 'Affiche un plan du site';

/* admin UI */
$this->trads['mod_content_genericsitemap_itemname'] = 'Nom : ';
$this->trads['mod_content_genericsitemap_itemlayout'] = 'Affichage : ';
$this->trads['mod_content_genericsitemap_itemcolumns'] = 'Colonnes : ';

/* layouts */
$this->trads['mod_content_genericsitemap_layout_text'] = 'Sans cadre';
$this->trads['mod_content_genericsitemap_layout_textbox'] = 'Encadr&eacute;(type %s)';

/* site */
$this->trads['mod_content_genericsitemap_site_title'] = 'Plan du site';

/* site fatal error */
$this->trads['mod_content_genericsitemap_site_fatalerror_title'] = 'Une erreur fatale est survenue!';
$this->trads['mod_content_genericsitemap_site_fatalerror_desc'] = '';
?>
