<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Oct 2008
 * Last Modif Date	: Oct 2008
 *
 * Content_GenericSiteMap english dictionnary
 */

$this->trads['mod_content_genericsitemap_title'] = 'Site map';
$this->trads['mod_content_genericsitemap_desc'] = 'Display site map';

/* admin UI */
$this->trads['mod_content_genericsitemap_itemname'] = 'Name: ';
$this->trads['mod_content_genericsitemap_itemlayout'] = 'Layout: ';
$this->trads['mod_content_genericsitemap_itemcolumns'] = 'Columns : ';

/* layouts */
$this->trads['mod_content_genericsitemap_layout_text'] = 'Without box';
$this->trads['mod_content_genericsitemap_layout_textbox'] = 'With box(type %s)';

/* site */
$this->trads['mod_content_genericsitemap_site_title'] = 'Site Map';

/* site fatal error */
$this->trads['mod_content_genericsitemap_site_fatalerror_title'] = 'A fatal error occured!';
$this->trads['mod_content_genericsitemap_site_fatalerror_desc'] = '';
?>