<?php
/**
 * @brief Content_GenericPageList module, french dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Nov 2007
 * @date Modification: May 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericpagelist_title'] = 'Liste de page';
$this->trads['mod_content_genericpagelist_desc'] = 'Affiche une liste des pages du site';

/* admin */
$this->trads['mod_content_genericpagelist_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericpagelist_formitem_root'] = 'Page racine : ';
$this->trads['mod_content_genericpagelist_layout_bordered'] = 'Encadr&eacute;';
$this->trads['mod_content_genericpagelist_layout_noborder'] = 'Sans cadre';
$this->trads['mod_content_genericpagelist_layout_borderedalt'] = 'Encadr&eacute; &amp; altern&eacute;';
$this->trads['mod_content_genericpagelist_formitem_order'] = 'Sens : ';
$this->trads['mod_content_genericpagelist_order_normal'] = 'Sens normal';
$this->trads['mod_content_genericpagelist_order_reverse'] = 'Sens inverse';
?>
