<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Nov 2007
 * Last Modif Date	: Oct 2008
 *
 * Content_GenericPageList french dictionnary 
*/
$this->trads['mod_content_genericpagelist_title'] = 'Liste de page';
$this->trads['mod_content_genericpagelist_desc'] = 'Affiche une liste des pages du site';

/* admin */
$this->trads['mod_content_genericpagelist_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericpagelist_formitem_root'] = 'Page racine : ';
$this->trads['mod_content_genericpagelist_layout_bordered'] = 'Encadr&eacute;';
$this->trads['mod_content_genericpagelist_layout_noborder'] = 'Sans cadre';
$this->trads['mod_content_genericpagelist_layout_borderedalt'] = 'Encadr&eacute; &amp; altern&eacute;';
$this->trads['mod_content_genericpagelist_formitem_order'] = 'Sens : ';
$this->trads['mod_content_genericpagelist_order_normal'] = 'Sens normal';
$this->trads['mod_content_genericpagelist_order_reverse'] = 'Sens inverse';
?>