<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Oct 2008
 * Last Modif Date	: Oct 2008
 *
 * Content_GenericPageList english dictionnary 
*/
$this->trads['mod_content_genericpagelist_title'] = 'Page list';
$this->trads['mod_content_genericpagelist_desc'] = 'Display website page list';

/* admin */
$this->trads['mod_content_genericpagelist_tabproperties'] = 'Properties';
$this->trads['mod_content_genericpagelist_formitem_root'] = 'Root page : ';
$this->trads['mod_content_genericpagelist_layout_bordered'] = 'Bordered';
$this->trads['mod_content_genericpagelist_layout_noborder'] = 'Without border';
$this->trads['mod_content_genericpagelist_layout_borderedalt'] = 'Bordered with alternate lines';
$this->trads['mod_content_genericpagelist_formitem_order'] = 'Order : ';
$this->trads['mod_content_genericpagelist_order_normal'] = 'Normal order';
$this->trads['mod_content_genericpagelist_order_reverse'] = 'Reverse order';
?>