<?php
/**
 * @brief Content_GenericPageList module, english dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Oct 2008
 * @date Modification: May 2021
 * @copyright 2008 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericpagelist_title'] = 'Page list';
$this->trads['mod_content_genericpagelist_desc'] = 'Display website page list';

/* admin */
$this->trads['mod_content_genericpagelist_tabproperties'] = 'Properties';
$this->trads['mod_content_genericpagelist_formitem_root'] = 'Root page : ';
$this->trads['mod_content_genericpagelist_layout_bordered'] = 'Bordered';
$this->trads['mod_content_genericpagelist_layout_noborder'] = 'Without border';
$this->trads['mod_content_genericpagelist_layout_borderedalt'] = 'Bordered with alternate lines';
$this->trads['mod_content_genericpagelist_formitem_order'] = 'Order : ';
$this->trads['mod_content_genericpagelist_order_normal'] = 'Normal order';
$this->trads['mod_content_genericpagelist_order_reverse'] = 'Reverse order';
?>
