<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		    : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0
 * Object Version	: 1.0
 * Object Type      : Plugin / Module Dictionnary
 * Creation Date	: Jun 2005
 * Last Modif Date  : Oct 2017
 *
 * Admin_Site language dictionnary : French 
*/
$this->trads['mod_admin_site_title'] = 'Configuration du site';
$this->trads['mod_admin_site_desc'] = 'Gestion de tous les param&egrave;tres du site';

/* ssl values */
$this->trads['mod_admin_site_sslvalue_auto'] = 'Automatique (SSL utilis&eacute; si disponible)';
$this->trads['mod_admin_site_sslvalue_forced'] = 'Forc&eacute;';
$this->trads['mod_admin_site_sslvalue_none'] = 'Forc&eacute; sans SSL';
$this->trads['mod_admin_site_sslvalue_default'] = 'Par d&eacute;faut (choix de l\'utilisateur)';

/* caches values */
$this->trads['mod_admin_site_cache_none'] = 'Aucun';
$this->trads['mod_admin_site_cache_default'] = 'Par d&eacute;faut (celui du navigateur)';
$this->trads['mod_admin_site_cache_disabled'] = 'D&eacute;sactiv&eacute;';
$this->trads['mod_admin_site_cache_enabled'] = 'Activ&eacute;';

/* camyks installation values */
$this->trads['mod_admin_site_camyksinstallation_dedicated'] = 'D&eacute;di&eacute;e';
$this->trads['mod_admin_site_camyksinstallation_shared'] = 'Partag&eacute;e';

/* generic conf texts */
$this->trads['mod_admin_site_formtitle_general'] = 'G&eacute;n&eacute;ral';
$this->trads['mod_admin_site_formitem_ssl'] = 'Connexion SSL : ';
$this->trads['mod_admin_site_formtitle_languages'] = 'Langues';
$this->trads['mod_admin_site_formitem_version'] = 'Version : ';

/* properties conf texts */
$this->trads['mod_admin_site_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_admin_site_formitem_sitetitle'] = 'Titre : ';
$this->trads['mod_admin_site_formitem_sitename'] = 'Nom : ';
$this->trads['mod_admin_site_formitem_url'] = 'URL : ';
$this->trads['mod_admin_site_formitem_friendlyurls'] = 'URLs sympathiques : ';
$this->trads['mod_admin_site_formitem_author'] = 'Auteur : ';
$this->trads['mod_admin_site_formitem_company'] = 'Soci&eacute;t&eacute; : ';
$this->trads['mod_admin_site_formitem_installation'] = 'Installation : ';
$this->trads['mod_admin_site_formitem_path'] = 'Chemin : ';
$this->trads['mod_admin_site_formtitle_contacts'] = 'Contacts';
$this->trads['mod_admin_site_formtitle_settings'] = 'R&eacute;glages';
$this->trads['mod_admin_site_formitem_encoding'] = 'Encodage des caract&egrave;res : ';
$this->trads['mod_admin_site_formitem_htmlversion'] = 'Version du HTML : ';
$this->trads['mod_admin_site_formtitle_caches'] = 'Caches';
$this->trads['mod_admin_site_formitem_serverside'] = 'C&ocirc;t&eacute; serveur : ';
$this->trads['mod_admin_site_formitem_clientside'] = 'C&ocirc;t&eacute; client : ';

/* database conf texts */
$this->trads['mod_admin_site_formtitle_connection'] = 'Connexion';
$this->trads['mod_admin_site_tabdatabase'] = 'Base de donn&eacute;es';
$this->trads['mod_admin_site_formitem_databasedriver'] = 'Driver : ';
$this->trads['mod_admin_site_formitem_databasehost'] = 'Serveur h&ocirc;te : ';
$this->trads['mod_admin_site_formitem_databasename'] = 'Nom de la base : ';
$this->trads['mod_admin_site_formitem_databaselogin'] = 'Identifiant : ';
$this->trads['mod_admin_site_formitem_databasesize'] = 'Taille de la base : ';
$this->trads['mod_admin_site_formitem_tables'] = 'Tables : ';
$this->trads['mod_admin_site_formitem_lines'] = 'Lignes : ';
$this->trads['mod_admin_site_formtitle_status'] = 'Etat';
$this->trads['mod_admin_site_formitem_tablesok'] = 'Tables en bonne sant&eacute; : ';
$this->trads['mod_admin_site_formitem_tablesnotok'] = 'N&eacute;cessitant r&eacute;paration : ';
$this->trads['mod_admin_site_formtitle_error'] = 'Erreurs';
$this->trads['mod_admin_site_formtitle_info'] = 'Informations';
$this->trads['mod_admin_site_formtitle_note'] = 'Notes';
$this->trads['mod_admin_site_formtitle_warning'] = 'Avertissements';
$this->trads['mod_admin_site_formdesc_nomessage'] = 'Aucun message';

/* admin conf texts */
$this->trads['mod_admin_site_tabadminmode'] = 'Administration';
$this->trads['mod_admin_site_formitem_adminentry'] = 'Point d\'entr&eacute;e  : ';
$this->trads['mod_admin_site_formitem_theme'] = 'Th&egrave;me utilis&eacute; : ';
$this->trads['mod_admin_site_formitem_adminlanguages'] = 'Langues autoris&eacute;es pour l\'administration du site : ';
$this->trads['mod_admin_site_formitem_editinglanguages'] = 'Langues disponibles &agrave; l\'&eacute;dition : ';
$this->trads['mod_admin_site_formtitle_lists'] = 'Listes';
$this->trads['mod_admin_site_formitem_items'] = 'Elements affich&eacute;s : ';
$this->trads['mod_admin_site_formtitle_files'] = 'Fichiers';
$this->trads['mod_admin_site_formitem_uploadmaxsize'] = 'Taille max. en upload : ';

/* site conf texts */
$this->trads['mod_admin_site_tabsitemode'] = 'Visite';
$this->trads['mod_admin_site_formitem_defaulttheme'] = 'Th&egrave;me par d&eacute;faut : ';
$this->trads['mod_admin_site_formitem_defaulttemplate'] = 'Template par d&eacute;faut : ';
$this->trads['mod_admin_site_formitem_pagemaxmodules'] = 'Modules par page : ';
$this->trads['mod_admin_site_formtitle_statistics'] = 'Statistiques';
$this->trads['mod_admin_site_formitem_google_analytics'] = 'Code Google Analytics : ';
$this->trads['mod_admin_site_formitem_domain'] = ' - Domaine : ';
$this->trads['mod_admin_site_stats_none'] = 'Aucun';
$this->trads['mod_admin_site_stats_nonef'] = 'Aucune';
$this->trads['mod_admin_site_stats_enabled'] = 'Activ&eacute;es';
$this->trads['mod_admin_site_stats_disabled'] = 'D&eacute;sactiv&eacute;es';
$this->trads['mod_admin_site_formtitle_handheld'] = 'Mobile';
$this->trads['mod_admin_site_formitem_responsive'] = 'Site adaptatif : '; 	
$this->trads['mod_admin_site_formitem_declination'] = 'D&eacute;clinaison mobile : ';

/* server conf texts */
$this->trads['mod_admin_site_tabserver'] = 'Serveur';
$this->trads['mod_admin_site_formtitle_apache'] = 'Apache';
$this->trads['mod_admin_site_formtitle_php'] = 'PHP';
?>