<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a2
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Creation Date	: Feb 2013
 * Last Modif Date      : Feb 2013
 *
 * Admin_Site english dictionnary
*/
$this->trads['mod_admin_site_title'] = 'Website configuration';
$this->trads['mod_admin_site_desc'] = 'Check website configuration';

/* generic conf texts */
$this->trads['mod_admin_site_theme'] = 'Used theme: ';

/* global conf texts */
$this->trads['mod_admin_site_general'] = 'Properties';
$this->trads['mod_admin_site_site_title'] = 'Title: ';
$this->trads['mod_admin_site_site_name'] = 'Name: ';
$this->trads['mod_admin_site_url'] = 'URL: ';
$this->trads['mod_admin_site_version'] = 'Version: ';
$this->trads['mod_admin_site_friendly_urls'] = 'Friendly URLs: ';
$this->trads['mod_admin_site_author'] = 'Author: ';
$this->trads['mod_admin_site_company'] = 'Company: ';

/* database conf texts */
$this->trads['mod_admin_site_database'] = 'Database';
$this->trads['mod_admin_site_database_host'] = 'Host: ';
$this->trads['mod_admin_site_database_name'] = 'Name: ';
$this->trads['mod_admin_site_database_login'] = 'Login: ';
$this->trads['mod_admin_site_database_change_pwd'] = 'Change password? ';
$this->trads['mod_admin_site_database_pwd'] = 'Password: ';
$this->trads['mod_admin_site_database_size'] = 'Database size: ';

/* admin conf texts */
$this->trads['mod_admin_site_adminpart'] = 'Administration';
$this->trads['mod_admin_site_admin_entry'] = 'Admin entry point: ';
$this->trads['mod_admin_site_admin_languages'] = 'Admin authorised languages: ';
$this->trads['mod_admin_site_editing_languages'] = 'Edition available languages: ';

/* site conf texts */
$this->trads['mod_admin_site_viewpart'] = 'Visit';
$this->trads['mod_admin_site_visit_content'] = 'Content: ';
$this->trads['mod_admin_site_template'] = 'Default template: ';
$this->trads['mod_admin_site_pagemaxmodules'] = 'Max. module by page: ';
$this->trads['mod_admin_site_languages'] = 'Available languages: ';
$this->trads['mod_admin_site_visit_stats'] = 'Statistics: ';
$this->trads['mod_admin_site_google_analytics_code'] = 'Google Analytics code: ';
$this->trads['mod_admin_site_stats_none'] = 'None';
$this->trads['mod_admin_site_stats_nonef'] = 'None';
$this->trads['mod_admin_site_stats_enabled'] = 'Enabled';
$this->trads['mod_admin_site_stats_disabled'] = 'Disabled';
?>