<?php
/**
 * @brief Admin_Site Module english dictionnary.
 * @details Plugin / Module layout
 * @file plugin/module/Admin_Site/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.2
 * @date Creation: Feb 2013
 * @date Modification: Sep 2019
 * @copyright 2013 - 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_site_title'] = 'Website configuration';
$this->trads['mod_admin_site_desc'] = 'Check website configuration';

/* admin rights */
$this->trads['mod_admin_site_rights_read_site_config'] = 'Read website configuration';
$this->trads['mod_admin_site_rights_edit_site_config'] = 'Edit website configuration';
$this->trads['mod_admin_site_rights_read_plugin_config'] = 'Read plugin configuration';
$this->trads['mod_admin_site_rights_edit_plugin_config'] = 'Edit plugin configuration';

/* ssl values */
$this->trads['mod_admin_site_sslvalue_auto'] = 'Automatic (SSL used if available)';
$this->trads['mod_admin_site_sslvalue_forced'] = 'Forced';
$this->trads['mod_admin_site_sslvalue_none'] = 'Forced without SSL';
$this->trads['mod_admin_site_sslvalue_default'] = 'Default (visitor\'s choice)';

/* caches values */
$this->trads['mod_admin_site_cache_none'] = 'None';
$this->trads['mod_admin_site_cache_default'] = 'Default (browser\'s one)';
$this->trads['mod_admin_site_cache_disabled'] = 'Disabled';
$this->trads['mod_admin_site_cache_enabled'] = 'Enabled';

/* camyks installation values */
$this->trads['mod_admin_site_camyksinstallation_dedicated'] = 'Dedicated';
$this->trads['mod_admin_site_camyksinstallation_shared'] = 'Shared';

/* camyks friendly urls mode values */
$this->trads['mod_admin_site_friendlyurls_legacy'] = 'Legacy mode';
$this->trads['mod_admin_site_friendlyurls_modern'] = 'Modern mode';
$this->trads['mod_admin_site_friendlyurls_modern2'] = 'Modern mode (with languages as folder)';

/* generic conf texts */
$this->trads['mod_admin_site_formtitle_general'] = 'General';
$this->trads['mod_admin_site_formitem_ssl'] = 'SSL connection: ';
$this->trads['mod_admin_site_formtitle_languages'] = 'Languages';
$this->trads['mod_admin_site_formitem_version'] = 'Version: ';

/* properties conf texts */
$this->trads['mod_admin_site_tabproperties'] = 'Properties';
$this->trads['mod_admin_site_formitem_sitetitle'] = 'Title: ';
$this->trads['mod_admin_site_formitem_sitename'] = 'Name: ';
$this->trads['mod_admin_site_formitem_url'] = 'URL: ';
$this->trads['mod_admin_site_formitem_friendlyurls'] = 'Friendly URLs: ';
$this->trads['mod_admin_site_formitem_author'] = 'Author: ';
$this->trads['mod_admin_site_formitem_company'] = 'Company: ';
$this->trads['mod_admin_site_formitem_installation'] = 'Installation: ';
$this->trads['mod_admin_site_formitem_path'] = 'Path: ';
$this->trads['mod_admin_site_action_checkcamyksintegrity'] = 'Check CaMykS integrity';
$this->trads['mod_admin_site_formtitle_contacts'] = 'Contacts';
$this->trads['mod_admin_site_formtitle_settings'] = 'Settings';
$this->trads['mod_admin_site_formitem_encoding'] = 'Encoding: ';
$this->trads['mod_admin_site_formitem_htmlversion'] = 'HTML version: ';
$this->trads['mod_admin_site_formtitle_caches'] = 'Caches';
$this->trads['mod_admin_site_formitem_serverside'] = 'Server-side: ';
$this->trads['mod_admin_site_formitem_clientside'] = 'Client-side: ';

/* database conf texts */
$this->trads['mod_admin_site_tabdatabase'] = 'Database';
$this->trads['mod_admin_site_formtitle_connection'] = 'Connection';
$this->trads['mod_admin_site_formitem_databasedriver'] = 'Driver : ';
$this->trads['mod_admin_site_formitem_databasehost'] = 'Host: ';
$this->trads['mod_admin_site_formitem_databasename'] = 'Name : ';
$this->trads['mod_admin_site_formitem_databaselogin'] = 'Login : ';
$this->trads['mod_admin_site_formitem_databasesize'] = 'Database size: ';
$this->trads['mod_admin_site_formitem_tables'] = 'Tables: ';
$this->trads['mod_admin_site_formitem_lines'] = 'Lines: ';
$this->trads['mod_admin_site_formitem_connections'] = 'Connections: ';
$this->trads['mod_admin_site_formtitle_status'] = 'Status';
$this->trads['mod_admin_site_formitem_tablesok'] = 'Good health status: ';
$this->trads['mod_admin_site_formitem_tablesnotok'] = 'Requiring repair: ';
$this->trads['mod_admin_site_formtitle_error'] = 'Errors';
$this->trads['mod_admin_site_formtitle_info'] = 'Information';
$this->trads['mod_admin_site_formtitle_note'] = 'Notes';
$this->trads['mod_admin_site_formtitle_warning'] = 'Warning';
$this->trads['mod_admin_site_formdesc_nomessage'] = 'No message';

/* admin conf texts */
$this->trads['mod_admin_site_tabadminmode'] = 'Administration';
$this->trads['mod_admin_site_formitem_adminentry'] = 'Entry point: ';
$this->trads['mod_admin_site_formitem_theme'] = 'Theme used: ';
$this->trads['mod_admin_site_formitem_adminlanguages'] = 'Administration languages: ';
$this->trads['mod_admin_site_formitem_editinglanguages'] = 'Edition languages: ';
$this->trads['mod_admin_site_formtitle_lists'] = 'Lists';
$this->trads['mod_admin_site_formitem_items'] = 'Displayed items: ';
$this->trads['mod_admin_site_formtitle_files'] = 'Files';
$this->trads['mod_admin_site_formitem_uploadmaxsize'] = 'Upload max size: ';

/* site conf texts */
$this->trads['mod_admin_site_tabsitemode'] = 'Visit';
$this->trads['mod_admin_site_formitem_defaulttheme'] = 'Default theme: ';
$this->trads['mod_admin_site_formitem_defaulttemplate'] = 'Default template: ';
$this->trads['mod_admin_site_formitem_pagemaxmodules'] = 'Max. module by page: ';
$this->trads['mod_admin_site_formtitle_statistics'] = 'Statistics';
$this->trads['mod_admin_site_formitem_google_analytics'] = 'Google Analytics code: ';
$this->trads['mod_admin_site_formitem_domain'] = ' - Domain: ';
$this->trads['mod_admin_site_stats_none'] = 'Aucun';
$this->trads['mod_admin_site_stats_nonef'] = 'Aucune';
$this->trads['mod_admin_site_stats_enabled'] = 'Enabled';
$this->trads['mod_admin_site_stats_disabled'] = 'Disabled';
$this->trads['mod_admin_site_formtitle_handheld'] = 'Mobile';
$this->trads['mod_admin_site_formitem_responsive'] = 'Responsive design: ';
$this->trads['mod_admin_site_formitem_declination'] = 'Mobile declination: ';

/* server conf texts */
$this->trads['mod_admin_site_tabserver'] = 'Server';
$this->trads['mod_admin_site_formtitle_operatingsystem'] = 'Operating system';
$this->trads['mod_admin_site_formtitle_httpserver'] = 'HTTP Server';
$this->trads['mod_admin_site_formtitle_php'] = 'PHP';

/* plugins conf texts */
$this->trads['mod_admin_site_tabplugins'] = 'Plugins';
$this->trads['mod_admin_site_viewthispluginconfig'] = 'View this plugin configuration';
$this->trads['mod_admin_site_editthispluginconfig'] = 'Edit this plugin configuration';
$this->trads['mod_admin_site_formtitle_pluginconfig'] = 'Configuring plugin %s';

/* save configuration messages */
$this->trads['mod_admin_site_pluginconfiguration_saved'] = 'Plugin %s configuration saved.';
$this->trads['mod_admin_site_pluginconfiguration_notsaved'] = 'An error has occured while saving plugin %s configuration.';
?>
