<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Dictionnary
 * Creation Date    : Mar 2018
 * Last Modif Date  : Mar 2018
 *
 * GenericMediaPopup language dictionnary : French 
 */

/* insertion values */
$this->trads['input_genericmediapopup_insertion_manual'] = 'Manuelle';
$this->trads['input_genericmediapopup_insertion_automatic'] = 'Automatique';

/* style source values */
$this->trads['input_genericmediapopup_stylesource_plugin'] = 'Plugin';
$this->trads['input_genericmediapopup_stylesource_theme'] = 'Th&egrave;me';

/* edit / view config */
$this->trads['input_genericmediapopup_formitem_insertion'] = 'Insertion : ';
$this->trads['input_genericmediapopup_formitem_stylesource'] = 'Source des styles : ';

$this->trads['input_genericmediapopup_formtitle_controls'] = 'Contr&ocirc;les';
$this->trads['input_genericmediapopup_formitem_clickbkgdtoclose'] = 'Clic sur le fond : ';
$this->trads['input_genericmediapopup_formitem_enableclosebutton'] = 'Afficher le bouton fermer : ';
$this->trads['input_genericmediapopup_formitem_enablekeyboard'] = 'Activer le clavier : ';
$this->trads['input_genericmediapopup_formitem_maxwidth'] = 'Largeur maximale : ';
 
$this->trads['input_genericmediapopup_formtitle_diaporama'] = 'Diaporama';
$this->trads['input_genericmediapopup_formitem_enablediaporama'] = 'Autoriser les diaporamas : ';
$this->trads['input_genericmediapopup_formitem_diaporamabuttonsshift'] = 'D&eacute;calage des boutons : ';
 
$this->trads['input_genericmediapopup_formtitle_flashplayer'] = 'Flash Player';
$this->trads['input_genericmediapopup_formitem_enableflash'] = 'Activer Flash : ';
$this->trads['input_genericmediapopup_formitem_flvcontrolercolor'] = 'Couleur du contr&ocirc;leur : ';
$this->trads['input_genericmediapopup_formitem_flvcontroleralpha'] = 'Transparence du contr&ocirc;leur : ';
$this->trads['input_genericmediapopup_formitem_flvcontrolerheight'] = 'Hauteur du contr&ocirc;leur : ';
?>