<?php
/**
 * @brief GenericMediaPopup Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/GenericMediaPopup/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Mar 2018
 * @date Modification: Apr 2018
 * @copyright 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* insertion values */
$this->trads['input_genericmediapopup_insertion_manual'] = 'Manuelle';
$this->trads['input_genericmediapopup_insertion_automatic'] = 'Automatique';

/* style source values */
$this->trads['input_genericmediapopup_stylesource_plugin'] = 'Plugin';
$this->trads['input_genericmediapopup_stylesource_theme'] = 'Th&egrave;me';

/* edit / view config */
$this->trads['input_genericmediapopup_formitem_insertion'] = 'Insertion : ';
$this->trads['input_genericmediapopup_formitem_stylesource'] = 'Source des styles : ';

$this->trads['input_genericmediapopup_formtitle_controls'] = 'Contr&ocirc;les';
$this->trads['input_genericmediapopup_formitem_clickbkgdtoclose'] = 'Clic sur le fond : ';
$this->trads['input_genericmediapopup_formitem_enableclosebutton'] = 'Afficher le bouton fermer : ';
$this->trads['input_genericmediapopup_formitem_enablekeyboard'] = 'Activer le clavier : ';
$this->trads['input_genericmediapopup_formitem_maxwidth'] = 'Largeur maximale : ';
 
$this->trads['input_genericmediapopup_formtitle_diaporama'] = 'Diaporama';
$this->trads['input_genericmediapopup_formitem_enablediaporama'] = 'Autoriser les diaporamas : ';
$this->trads['input_genericmediapopup_formitem_diaporamabuttonsshift'] = 'D&eacute;calage des boutons : ';
 
$this->trads['input_genericmediapopup_formtitle_flashplayer'] = 'Flash Player';
$this->trads['input_genericmediapopup_formitem_enableflash'] = 'Activer Flash : ';
$this->trads['input_genericmediapopup_formitem_flvcontrolercolor'] = 'Couleur du contr&ocirc;leur : ';
$this->trads['input_genericmediapopup_formitem_flvcontroleralpha'] = 'Transparence du contr&ocirc;leur : ';
$this->trads['input_genericmediapopup_formitem_flvcontrolerheight'] = 'Hauteur du contr&ocirc;leur : ';
?>