<?php
/**
 * @brief Admin_SystemNotifications Module english dictionary.
 * @details Plugin / Module dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Apr 2021
 * @date Modification: Apr 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_systemnotifications_title'] = 'Internal notifications';
$this->trads['mod_admin_systemnotifications_desc'] = 'Collects notifications';
$this->trads['mod_admin_systemnotifications_descdate'] = 'Last check %s';
$this->trads['mod_admin_systemnotifications_descdatethe'] = 'Last check on %s';

/* object titles */
$this->trads['mod_admin_systemnotifications_website'] = 'Website';
$this->trads['mod_admin_systemnotifications_websites'] = 'Websites';
$this->trads['mod_admin_systemnotifications_websites_all'] = 'All';

/* admin website status value */
$this->trads['mod_admin_systemnotifications_websitestatus_disabled'] = 'Disabled';
$this->trads['mod_admin_systemnotifications_websitestatus_enabled'] = 'Enabled';

/* admin website status values */
$this->trads['mod_admin_systemnotifications_websitesstatus_disabled'] = 'Disabled';
$this->trads['mod_admin_systemnotifications_websitesstatus_enabled'] = 'Enabled';

/* admin item priority */
$this->trads['mod_admin_systemnotifications_itempriority_low'] = 'Low priority';
$this->trads['mod_admin_systemnotifications_itempriority_medium'] = 'Medium priority';
$this->trads['mod_admin_systemnotifications_itempriority_high'] = 'High priority';

/* admin configuration module mode values */
$this->trads['mod_admin_systemnotifications_modulemode_slave'] = 'Slave';
$this->trads['mod_admin_systemnotifications_modulemode_master'] = 'Master';

/* admin configuration access status values */
$this->trads['mod_admin_systemnotifications_accessstatus_disabled'] = 'Disabled';
$this->trads['mod_admin_systemnotifications_accessstatus_enabled'] = 'Enabled';

/* admin configuration access authentication values */
$this->trads['mod_admin_systemnotifications_accessauthentication_none'] = 'None';
$this->trads['mod_admin_systemnotifications_accessauthentication_credentials'] = 'Login/Password';
$this->trads['mod_admin_systemnotifications_accessauthentication_ipaddress'] = 'IP Address';

/* admin main: follow up tab */
$this->trads['mod_admin_systemnotifications_tabfollowup'] = 'Follow up';
$this->trads['mod_admin_systemnotifications_check_now'] = 'Check now';
$this->trads['mod_admin_systemnotifications_lastcheckdate'] = 'Last check on %s';
$this->trads['mod_admin_systemnotifications_nonotifications'] = 'No notification';
$this->trads['mod_admin_systemnotifications_check_notifications'] = 'Check notifications';

/* admin main: websites */
$this->trads['mod_admin_systemnotifications_editwebsite'] = 'Edit this website';
$this->trads['mod_admin_systemnotifications_deletewebsite'] = 'Delete this website';
$this->trads['mod_admin_systemnotifications_deletewebsitemessage'] = 'Are you sure to want to delete this website ? This action can\'t be undone.';
$this->trads['mod_admin_systemnotifications_addnewwebsite'] = 'Add a website';

/* admin main: configuration / edit configuration */
$this->trads['mod_admin_systemnotifications_tabconfiguration'] = 'Configuration';
$this->trads['mod_admin_systemnotifications_formtitle_module'] = 'Module';
$this->trads['mod_admin_systemnotifications_formitem_mode'] = 'Mode: ';
$this->trads['mod_admin_systemnotifications_formitem_delay'] = 'Delay between 2 checks: ';
$this->trads['mod_admin_systemnotifications_unit_minutes'] = ' minutes';
$this->trads['mod_admin_systemnotifications_formtitle_access'] = 'Access / Authenticating';
$this->trads['mod_admin_systemnotifications_formitem_status'] = 'Status: ';
$this->trads['mod_admin_systemnotifications_formitem_authentication'] = 'Authenticating: ';
$this->trads['mod_admin_systemnotifications_formitem_login'] = 'Login: ';
$this->trads['mod_admin_systemnotifications_formitem_ipaddress'] = 'IP address: ';
$this->trads['mod_admin_systemnotifications_addressip_sameserver'] = 'Same server only';
$this->trads['mod_admin_systemnotifications_edit_configuration'] = 'Edit configuration';
$this->trads['mod_admin_systemnotifications_credentials_all'] = 'All';

/* admin save config messages */
$this->trads['mod_admin_systemnotifications_config_saved'] = 'Configuration saved.';
$this->trads['mod_admin_systemnotifications_config_notsaved'] = 'An error occured while saving configuration.';

/* admin edit website */
$this->trads['mod_admin_systemnotifications_tabproperties'] = 'Properties';
$this->trads['mod_admin_systemnotifications_formitem_url'] = 'URL: ';
$this->trads['mod_admin_systemnotifications_formitem_password'] = 'Password: ';

/* admin save website */
$this->trads['mod_admin_systemnotifications_website_saved'] = 'Website saved.';
$this->trads['mod_admin_systemnotifications_website_notsaved'] = 'An error has occured while saving the website.';

/* admin delete website */
$this->trads['mod_admin_systemnotifications_website_deleted'] = 'Website deleted.';
$this->trads['mod_admin_systemnotifications_website_notdeleted'] = 'An error has occured while deleting the website.';

/* admin check website */
$this->trads['mod_admin_systemnotifications_websites_checked'] = 'Websites checked.';

/* admin check website */
$this->trads['mod_admin_systemnotifications_website_checked'] = 'Website checked.';

/* generic request errors */
$this->trads['mod_admin_systemnotifications_requesterror_requestfailed'] = 'An error occured during the request.';
$this->trads['mod_admin_systemnotifications_requesterror_undefinedaction'] = 'No action defined.';

/* load notification request errors */
$this->trads['mod_admin_systemnotifications_requesterror_connectionfailed'] = 'Connection to the website failed.';
$this->trads['mod_admin_systemnotifications_requesterror_nodatasent'] = 'No data received.';
$this->trads['mod_admin_systemnotifications_requesterror_accessdisabled'] = 'Access disabled.';
$this->trads['mod_admin_systemnotifications_requesterror_authenticationfailed'] = 'Authentication failed.';
?>
