<?php
/**
 * @brief Admin_GenericBlogsManager Module english dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jun 2008
 * @date Modification: Nov 2020
 * @copyright 2008 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_genericblogsmanager_title'] = 'Blogs';
$this->trads['mod_admin_genericblogsmanager_desc'] = 'Create and edit news, moderate comments, ...';
$this->trads['mod_admin_genericblogsmanager_desc1'] = '1 comment waiting for acceptation';
$this->trads['mod_admin_genericblogsmanager_descx'] = '%s comments waiting for acceptation';

/* rights */
$this->trads['mod_admin_genericblogsmanager_right_config'] = 'Settings';
$this->trads['mod_admin_genericblogsmanager_right_news_limited'] = 'Limited edition of news';
$this->trads['mod_admin_genericblogsmanager_right_news_global'] = 'Global edition of news';
$this->trads['mod_admin_genericblogsmanager_right_link_limited'] = 'Limited edition of links';
$this->trads['mod_admin_genericblogsmanager_right_link_global'] = 'Global edition of links';
$this->trads['mod_admin_genericblogsmanager_right_comment_limited'] = 'Limited edition of comments';
$this->trads['mod_admin_genericblogsmanager_right_comment_global'] = 'Global edition of comments';
$this->trads['mod_admin_genericblogsmanager_right_tag_limited'] = 'Limited edition of tags';
$this->trads['mod_admin_genericblogsmanager_right_tag_global'] = 'Global edition of tags';

/* editor modes */
$this->trads['mod_admin_genericblogsmanager_config_newseditormode_0'] = 'Simple text';
$this->trads['mod_admin_genericblogsmanager_config_newseditormode_1'] = 'Simplified HTML';
$this->trads['mod_admin_genericblogsmanager_config_newseditormode_2'] = 'Advanced HTML';
$this->trads['mod_admin_genericblogsmanager_config_newseditormode_3'] = 'Complete HTML';

/* comment status modes */
$this->trads['mod_admin_genericblogsmanager_comment_statusmode_0'] = 'Waiting for acceptation';
$this->trads['mod_admin_genericblogsmanager_comment_statusmode_1'] = 'Validated, on line';
$this->trads['mod_admin_genericblogsmanager_comment_statusmode_2'] = 'Rejected';

/* comment validation modes */
$this->trads['mod_admin_genericblogsmanager_config_commentsvalidationmode_1'] = 'Automatic';
$this->trads['mod_admin_genericblogsmanager_config_commentsvalidationmode_0'] = 'Administrative';

/* document shared mode */
$this->trads['mod_admin_genericblogsmanager_config_newsdocumentmode_0'] = 'Full';
$this->trads['mod_admin_genericblogsmanager_config_newsdocumentmode_1'] = 'Limited';
$this->trads['mod_admin_genericblogsmanager_config_newsdocumentmode_2'] = 'None';

/* main interface / tabs */
$this->trads['mod_admin_genericblogsmanager_tabconfig'] = 'Settings';
$this->trads['mod_admin_genericblogsmanager_tabnews'] = 'News';
$this->trads['mod_admin_genericblogsmanager_tablinks'] = 'Links';
$this->trads['mod_admin_genericblogsmanager_tabtags'] = 'Tags';

/* main interface / configuration tab */
$this->trads['mod_admin_genericblogsmanager_config_links_title'] = 'Links settings';
$this->trads['mod_admin_genericblogsmanager_config_links_maxcount'] = 'Allowed links by administrator: ';

$this->trads['mod_admin_genericblogsmanager_config_news_title'] = 'News settings';
$this->trads['mod_admin_genericblogsmanager_config_news_editormode'] = 'Content editor: ';
$this->trads['mod_admin_genericblogsmanager_config_news_allowvideo'] = 'Allow video links: ';
$this->trads['mod_admin_genericblogsmanager_config_news_documentmode'] = 'Document sharing: ';

$this->trads['mod_admin_genericblogsmanager_config_comments_title'] = 'Comments settings';
$this->trads['mod_admin_genericblogsmanager_config_comments_validationmode'] = 'Acceptation : ';


/* main interface / configuration tab messages */
$this->trads['mod_admin_genericblogsmanager_message_saveconfig_done'] = 'Settings save in progress...';
$this->trads['mod_admin_genericblogsmanager_message_saveconfig_failed'] = 'An error has occured while saving the settings.';

/* main interface / links tab */
$this->trads['mod_admin_genericblogsmanager_links_title'] = 'Title';
$this->trads['mod_admin_genericblogsmanager_links_url'] = 'URL';
$this->trads['mod_admin_genericblogsmanager_links_author'] = 'Author';
$this->trads['mod_admin_genericblogsmanager_links_view'] = 'Open this link';
$this->trads['mod_admin_genericblogsmanager_links_edit'] = 'Edit this link';
$this->trads['mod_admin_genericblogsmanager_links_delete'] = 'Delete this link';
$this->trads['mod_admin_genericblogsmanager_links_add'] = 'Add a lien';
$this->trads['mod_admin_genericblogsmanager_links_deletemessage'] = 'Are you sure to want to delete this link?';
$this->trads['mod_admin_genericblogsmanager_links_maxlinkcountreached'] = 'You reach the allowed links count limit';

/* main interface / links tab messages */
$this->trads['mod_admin_genericblogsmanager_message_deletelink_done'] = 'Link delete in progress...';
$this->trads['mod_admin_genericblogsmanager_message_deletelink_failed'] = 'An error has occured while deleting the link.';

/* main interface / tags tab */
$this->trads['mod_admin_genericblogsmanager_tags_title'] = 'Tag';
$this->trads['mod_admin_genericblogsmanager_tags_counter'] = 'Used';
$this->trads['mod_admin_genericblogsmanager_tags_add'] = 'Add a tag';
$this->trads['mod_admin_genericblogsmanager_tags_save'] = 'Save this tag';
$this->trads['mod_admin_genericblogsmanager_tags_canceledition'] = 'Cancel tag edition';
$this->trads['mod_admin_genericblogsmanager_tags_edit'] = 'Edit this tag';
$this->trads['mod_admin_genericblogsmanager_tags_delete'] = 'Delete this tag';
$this->trads['mod_admin_genericblogsmanager_tags_deletemessage'] = 'Are you sure to want to delete this tag? This action may affect all news that use this tag.';

/* main interface / tags tab messages */
$this->trads['mod_admin_genericblogsmanager_message_savetag_done'] = 'Tag save in progress...';
$this->trads['mod_admin_genericblogsmanager_message_savetag_failed'] = 'An error has occured while saving the tag.';
$this->trads['mod_admin_genericblogsmanager_message_deletetag_done'] = 'Tag delete in progress...';
$this->trads['mod_admin_genericblogsmanager_message_deletetag_failed'] = 'An error has occured while deleting the tag.';

/* main interface / news tab */
$this->trads['mod_admin_genericblogsmanager_news_title'] = 'Title';
$this->trads['mod_admin_genericblogsmanager_news_date'] = 'Date';
$this->trads['mod_admin_genericblogsmanager_news_author'] = 'Author';
$this->trads['mod_admin_genericblogsmanager_news_comment'] = 'Comments';
$this->trads['mod_admin_genericblogsmanager_news_add'] = 'Add a news';
$this->trads['mod_admin_genericblogsmanager_news_edit'] = 'Edit this news';
$this->trads['mod_admin_genericblogsmanager_news_editcomments'] = 'Moderate comments';
$this->trads['mod_admin_genericblogsmanager_news_delete'] = 'Delete news';
$this->trads['mod_admin_genericblogsmanager_news_deletemessage'] = 'Are you sure to want to delete this news ?';
$this->trads['mod_admin_genericblogsmanager_news_listpage'] = 'Page';
$this->trads['mod_admin_genericblogsmanager_news_listunread'] = 'With comments not read only';

/* edit link interface */
$this->trads['mod_admin_genericblogsmanager_editlink_editortitle'] = ' : Edit a link';
$this->trads['mod_admin_genericblogsmanager_editlink_createobject'] = 'New link';
$this->trads['mod_admin_genericblogsmanager_editlink_objectid'] = 'Link #%s';
$this->trads['mod_admin_genericblogsmanager_editlink_title'] = 'Title: ';
$this->trads['mod_admin_genericblogsmanager_editlink_url'] = 'URL: ';
$this->trads['mod_admin_genericblogsmanager_editlink_author'] = 'Author: ';
$this->trads['mod_admin_genericblogsmanager_editlink_ndate'] = 'Creation date: ';

/* edit link messages */
$this->trads['mod_admin_genericblogsmanager_message_savelink_done'] = 'Link save in progress...';
$this->trads['mod_admin_genericblogsmanager_message_savelink_failed'] = 'An error has occured while saving the link.';
$this->trads['mod_admin_genericblogsmanager_message_savelink_notdone'] = 'Link save failed';

/* edit news tabs */
$this->trads['mod_admin_genericblogsmanager_tabproperties'] = 'Properties';
$this->trads['mod_admin_genericblogsmanager_tabcontent'] = 'Content';

/* edit news interface */
$this->trads['mod_admin_genericblogsmanager_editnews_editortitle'] = ' : Edit a news';
$this->trads['mod_admin_genericblogsmanager_editnews_createobject'] = 'New news';
$this->trads['mod_admin_genericblogsmanager_editnews_objectid'] = 'News #%s';
$this->trads['mod_admin_genericblogsmanager_editnews_title'] = 'Title: ';
$this->trads['mod_admin_genericblogsmanager_editnews_author'] = 'Author: ';
$this->trads['mod_admin_genericblogsmanager_editnews_ndate'] = 'Date: ';
$this->trads['mod_admin_genericblogsmanager_editnews_videolink'] = 'Video link: ';
$this->trads['mod_admin_genericblogsmanager_editnews_content'] = 'Content: ';
$this->trads['mod_admin_genericblogsmanager_editnews_active'] = 'Active: ';
$this->trads['mod_admin_genericblogsmanager_editnews_taglist'] = 'Tags: ';
$this->trads['mod_admin_genericblogsmanager_editnews_selecttag'] = 'Select a tag';
$this->trads['mod_admin_genericblogsmanager_editnews_newtag'] = 'Add a tag';
$this->trads['mod_admin_genericblogsmanager_editnews_addthistag'] = 'Add this tag';

/* edit news messages */
$this->trads['mod_admin_genericblogsmanager_message_savenews_done'] = 'News save in progress...';
$this->trads['mod_admin_genericblogsmanager_message_savenews_failed'] = 'An error has occured while saving the news.';

/* view comments interface */
$this->trads['mod_admin_genericblogsmanager_viewcomments_listtitle'] = ' : Comments list';
$this->trads['mod_admin_genericblogsmanager_viewcomments_newscomments'] = 'Comments from news "%2$s" (id : %1$s)';

$this->trads['mod_admin_genericblogsmanager_site_comment_headerfull'] = 'Comment posted by <a href="%3$s" target="_blank" class="%4$s">%1$s</a>, on %2$s : ';
$this->trads['mod_admin_genericblogsmanager_site_comment_headerlight'] = 'Comment posted by %1$s, on %2$s : ';

$this->trads['mod_admin_genericblogsmanager_viewcomments_editcomment'] = 'Edit this comment';
$this->trads['mod_admin_genericblogsmanager_viewcomments_deletecomment'] = 'Delete this comment';
$this->trads['mod_admin_genericblogsmanager_viewcomments_updatecommentstatus'] = 'Update comment status';
$this->trads['mod_admin_genericblogsmanager_comment_deletemessage'] = 'Are you sure to want to delete this comment ? This action can not be canceled.';

/* edit comment interface */
$this->trads['mod_admin_genericblogsmanager_editcomment_editortitle'] = ' : Edit a comment';
$this->trads['mod_admin_genericblogsmanager_editcomment_objectid'] = 'Comment #%s';
$this->trads['mod_admin_genericblogsmanager_editcomment_parentnews'] = 'Related news: ';
$this->trads['mod_admin_genericblogsmanager_editcomment_date'] = 'Written on: ';
$this->trads['mod_admin_genericblogsmanager_editcomment_ipaddress'] = 'from IP address: ';
$this->trads['mod_admin_genericblogsmanager_editcomment_status'] = 'Status: ';
$this->trads['mod_admin_genericblogsmanager_editcomment_author'] = 'Author: ';
$this->trads['mod_admin_genericblogsmanager_editcomment_email'] = 'E-mail: ';
$this->trads['mod_admin_genericblogsmanager_editcomment_website'] = 'Website: ';
$this->trads['mod_admin_genericblogsmanager_editcomment_title'] = 'Title: ';
$this->trads['mod_admin_genericblogsmanager_editcomment_content'] = 'Content: ';


/* view comments & edit comment interfaces messages */
$this->trads['mod_admin_genericblogsmanager_message_savecomment_done'] = 'Comment save in progress...';
$this->trads['mod_admin_genericblogsmanager_message_savecomment_failed'] = 'An error has occured while saving the comment.';
$this->trads['mod_admin_genericblogsmanager_message_deletecomment_done'] = 'Comment delete in progress...';
$this->trads['mod_admin_genericblogsmanager_message_deletecomment_failed'] = 'An error has occured while deleting the comment.';
$this->trads['mod_admin_genericblogsmanager_message_updatecomment_done'] = 'Comment update in progress...';
$this->trads['mod_admin_genericblogsmanager_message_updatecomment_failed'] = 'An error has occured while updating the comment.';

/* comment save failed errors */
$this->trads['mod_admin_genericblogsmanager_savecommentfailed_internalerror'] = 'An error has occured while saving your comment.';
$this->trads['mod_admin_genericblogsmanager_savecommentfailed_emptycontent'] = 'Comment content can not be empty.';
$this->trads['mod_admin_genericblogsmanager_savecommentfailed_emptyauthor'] = 'You must set your name or nickname.';
$this->trads['mod_admin_genericblogsmanager_savecommentfailed_invalidemail'] = 'You must set your email. This email must be valid';
?>
