<?php
/**
 * @brief Admin_GenericBlogsManager Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Apr 2008
 * @date Modification: Nov 2020
 * @copyright 2008 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_genericblogsmanager_title'] = 'Blogs';
$this->trads['mod_admin_genericblogsmanager_desc'] = 'Ajouter des actualit&eacute;s, mod&eacute;rer les commentaires,...';
$this->trads['mod_admin_genericblogsmanager_desc1'] = '1 commentaire en attente de validation';
$this->trads['mod_admin_genericblogsmanager_descx'] = '%s commentaires en attente de validation';

/* rights */
$this->trads['mod_admin_genericblogsmanager_right_config'] = 'Configuration';
$this->trads['mod_admin_genericblogsmanager_right_news_limited'] = 'Edition limit&eacute;e des actualit&eacute;s';
$this->trads['mod_admin_genericblogsmanager_right_news_global'] = 'Edition globale des actualit&eacute;s';
$this->trads['mod_admin_genericblogsmanager_right_link_limited'] = 'Edition limit&eacute;e des liens';
$this->trads['mod_admin_genericblogsmanager_right_link_global'] = 'Edition globale des liens';
$this->trads['mod_admin_genericblogsmanager_right_comment_limited'] = 'Edition limit&eacute;e des commentaires';
$this->trads['mod_admin_genericblogsmanager_right_comment_global'] = 'Edition globale des commentaires';
$this->trads['mod_admin_genericblogsmanager_right_tag_limited'] = 'Edition limit&eacute;e des tags';
$this->trads['mod_admin_genericblogsmanager_right_tag_global'] = 'Edition globale des tags';

/* editor modes */
$this->trads['mod_admin_genericblogsmanager_config_newseditormode_0'] = 'Texte';
$this->trads['mod_admin_genericblogsmanager_config_newseditormode_1'] = 'HTML Simplifi&eacute;';
$this->trads['mod_admin_genericblogsmanager_config_newseditormode_2'] = 'HTML Avanc&eacute;';
$this->trads['mod_admin_genericblogsmanager_config_newseditormode_3'] = 'HTML Complet';

/* comment status modes */
$this->trads['mod_admin_genericblogsmanager_comment_statusmode_0'] = 'En attente de validation';
$this->trads['mod_admin_genericblogsmanager_comment_statusmode_1'] = 'Valid&eacute;, en ligne';
$this->trads['mod_admin_genericblogsmanager_comment_statusmode_2'] = 'Refus&eacute;';

/* comment validation modes */
$this->trads['mod_admin_genericblogsmanager_config_commentsvalidationmode_1'] = 'Automatique';
$this->trads['mod_admin_genericblogsmanager_config_commentsvalidationmode_0'] = 'Administrative';

/* document shared mode */
$this->trads['mod_admin_genericblogsmanager_config_newsdocumentmode_0'] = 'Total';
$this->trads['mod_admin_genericblogsmanager_config_newsdocumentmode_1'] = 'Limit&eacute;';
$this->trads['mod_admin_genericblogsmanager_config_newsdocumentmode_2'] = 'Aucun';

/* main interface / tabs */
$this->trads['mod_admin_genericblogsmanager_tabconfig'] = 'Configuration';
$this->trads['mod_admin_genericblogsmanager_tabnews'] = 'Actualit&eacute;s';
$this->trads['mod_admin_genericblogsmanager_tablinks'] = 'Liens';
$this->trads['mod_admin_genericblogsmanager_tabtags'] = 'Tags';

/* main interface / configuration tab */
$this->trads['mod_admin_genericblogsmanager_config_links_title'] = 'Configuration relative aux liens';
$this->trads['mod_admin_genericblogsmanager_config_links_maxcount'] = 'Nombre de liens autoris&eacute;s par bloggueur : ';

$this->trads['mod_admin_genericblogsmanager_config_news_title'] = 'Configuration relative aux actualit&eacute;s';
$this->trads['mod_admin_genericblogsmanager_config_news_editormode'] = 'Edition du contenu : ';
$this->trads['mod_admin_genericblogsmanager_config_news_allowvideo'] = 'Permettre l\'insertion d\'un lien vid&eacute;o : ';
$this->trads['mod_admin_genericblogsmanager_config_news_documentmode'] = 'Partage de documents : ';

$this->trads['mod_admin_genericblogsmanager_config_comments_title'] = 'Configuration relative aux commentaires';
$this->trads['mod_admin_genericblogsmanager_config_comments_validationmode'] = 'Validation : ';

/* main interface / configuration tab messages */
$this->trads['mod_admin_genericblogsmanager_message_saveconfig_done'] = 'Sauvegarde de la configuration en cours...';
$this->trads['mod_admin_genericblogsmanager_message_saveconfig_failed'] = 'Une erreur est survenue lors de la sauvegarde de la configuration.';

/* main interface / links tab */
$this->trads['mod_admin_genericblogsmanager_links_title'] = 'Titre';
$this->trads['mod_admin_genericblogsmanager_links_url'] = 'URL';
$this->trads['mod_admin_genericblogsmanager_links_author'] = 'Auteur';
$this->trads['mod_admin_genericblogsmanager_links_view'] = 'Ouvrir le lien';
$this->trads['mod_admin_genericblogsmanager_links_edit'] = 'Editer le lien';
$this->trads['mod_admin_genericblogsmanager_links_delete'] = 'Supprimer le lien';
$this->trads['mod_admin_genericblogsmanager_links_add'] = 'Ajouter un lien';
$this->trads['mod_admin_genericblogsmanager_links_deletemessage'] = 'Etes vous s&ucirc;r de vouloir supprimer ce lien ?';
$this->trads['mod_admin_genericblogsmanager_links_maxlinkcountreached'] = 'Vous avez atteint le nombre maximum de lien(s) autoris&eacute;(s).';

/* main interface / links tab messages */
$this->trads['mod_admin_genericblogsmanager_message_deletelink_done'] = 'Suppression du lien en cours...';
$this->trads['mod_admin_genericblogsmanager_message_deletelink_failed'] = 'Une erreur est survenue lors de la suppression du lien.';

/* main interface / tags tab */
$this->trads['mod_admin_genericblogsmanager_tags_title'] = 'Tag';
$this->trads['mod_admin_genericblogsmanager_tags_counter'] = 'Utilis&eacute;';
$this->trads['mod_admin_genericblogsmanager_tags_add'] = 'Ajouter un tag';
$this->trads['mod_admin_genericblogsmanager_tags_save'] = 'Enregistrer le tag';
$this->trads['mod_admin_genericblogsmanager_tags_canceledition'] = 'Annuler la modification';
$this->trads['mod_admin_genericblogsmanager_tags_edit'] = 'Editer le tag';
$this->trads['mod_admin_genericblogsmanager_tags_delete'] = 'Supprimer le tag';
$this->trads['mod_admin_genericblogsmanager_tags_deletemessage'] = 'Etes vous s&ucirc;r de vouloir supprimer ce tag ? Cela affectera toutes les actualit&eacute;s l\'utilisant.';

/* main interface / tags tab messages */
$this->trads['mod_admin_genericblogsmanager_message_savetag_done'] = 'Sauvegarde du tag en cours...';
$this->trads['mod_admin_genericblogsmanager_message_savetag_failed'] = 'Une erreur est survenue lors de la sauvegarde du tag.';
$this->trads['mod_admin_genericblogsmanager_message_deletetag_done'] = 'Suppression du tag en cours...';
$this->trads['mod_admin_genericblogsmanager_message_deletetag_failed'] = 'Une erreur est survenue lors de la suppression du tag.';

/* main interface / news tab */
$this->trads['mod_admin_genericblogsmanager_news_title'] = 'Titre';
$this->trads['mod_admin_genericblogsmanager_news_date'] = 'Date';
$this->trads['mod_admin_genericblogsmanager_news_author'] = 'Auteur';
$this->trads['mod_admin_genericblogsmanager_news_comment'] = 'Comm.';
$this->trads['mod_admin_genericblogsmanager_news_add'] = 'Ajouter une actualit&eacute;';
$this->trads['mod_admin_genericblogsmanager_news_edit'] = 'Editer l\'actualit&eacute;';
$this->trads['mod_admin_genericblogsmanager_news_editcomments'] = 'Mod&eacute;rer les commentaires';
$this->trads['mod_admin_genericblogsmanager_news_delete'] = 'Supprimer l\'actualit&eacute;';
$this->trads['mod_admin_genericblogsmanager_news_deletemessage'] = 'Etes vous s&ucirc;r de vouloir supprimer cette actualit&eacute; ? ';
$this->trads['mod_admin_genericblogsmanager_news_listpage'] = 'Page';
$this->trads['mod_admin_genericblogsmanager_news_listunread'] = 'Avec commentaires non lus seulement';

/* edit link interface */
$this->trads['mod_admin_genericblogsmanager_editlink_editortitle'] = ' : Editer un lien';
$this->trads['mod_admin_genericblogsmanager_editlink_createobject'] = 'Nouveau lien';
$this->trads['mod_admin_genericblogsmanager_editlink_objectid'] = 'Lien n&deg;%s';
$this->trads['mod_admin_genericblogsmanager_editlink_title'] = 'Titre : ';
$this->trads['mod_admin_genericblogsmanager_editlink_url'] = 'URL : ';
$this->trads['mod_admin_genericblogsmanager_editlink_author'] = 'Auteur : ';
$this->trads['mod_admin_genericblogsmanager_editlink_ndate'] = 'Cr&eacute;&eacute; le : ';

/* edit link messages */
$this->trads['mod_admin_genericblogsmanager_message_savelink_done'] = 'Sauvegarde du lien en cours...';
$this->trads['mod_admin_genericblogsmanager_message_savelink_failed'] = 'Une erreur est survenue lors de la sauvegarde du lien.';
$this->trads['mod_admin_genericblogsmanager_message_savelink_notdone'] = 'Le lien n\'a pas &eacute;t&eacute; enregistr&eacute;.';

/* edit news tabs */
$this->trads['mod_admin_genericblogsmanager_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_admin_genericblogsmanager_tabcontent'] = 'Contenu';

/* edit news interface */
$this->trads['mod_admin_genericblogsmanager_editnews_editortitle'] = ' : Editer une actualit&eacute;';
$this->trads['mod_admin_genericblogsmanager_editnews_createobject'] = 'Nouvelle actualit&eacute;';
$this->trads['mod_admin_genericblogsmanager_editnews_objectid'] = 'Actualit&eacute; n&deg;%s';
$this->trads['mod_admin_genericblogsmanager_editnews_title'] = 'Titre : ';
$this->trads['mod_admin_genericblogsmanager_editnews_author'] = 'Auteur : ';
$this->trads['mod_admin_genericblogsmanager_editnews_ndate'] = 'Date : ';
$this->trads['mod_admin_genericblogsmanager_editnews_videolink'] = 'Lien vid&eacute;o : ';
$this->trads['mod_admin_genericblogsmanager_editnews_content'] = 'Contenu : ';
$this->trads['mod_admin_genericblogsmanager_editnews_active'] = 'Activ&eacute;e : ';
$this->trads['mod_admin_genericblogsmanager_editnews_taglist'] = 'Tags : ';
$this->trads['mod_admin_genericblogsmanager_editnews_selecttag'] = 'S&eacute;lectionner un tag ';
$this->trads['mod_admin_genericblogsmanager_editnews_newtag'] = 'Ajouter un tag ';
$this->trads['mod_admin_genericblogsmanager_editnews_addthistag'] = 'Ajouter ce tag ';

/* edit news messages */
$this->trads['mod_admin_genericblogsmanager_message_savenews_done'] = 'Sauvegarde de l\'actualit&eacute; en cours...';
$this->trads['mod_admin_genericblogsmanager_message_savenews_failed'] = 'Une erreur est survenue lors de la sauvegarde de l\'actualit&eacute;.';

/* view comments interface */
$this->trads['mod_admin_genericblogsmanager_viewcomments_listtitle'] = ' : Liste des commentaires';
$this->trads['mod_admin_genericblogsmanager_viewcomments_newscomments'] = 'Les commentaires de la news "%2$s" (id : %1$s)';

$this->trads['mod_admin_genericblogsmanager_site_comment_headerfull'] = 'Message post&eacute; par <a href="%3$s" target="_blank" class="%4$s">%1$s</a>, le %2$s : ';
$this->trads['mod_admin_genericblogsmanager_site_comment_headerlight'] = 'Message post&eacute; par %1$s, le %2$s : ';

$this->trads['mod_admin_genericblogsmanager_viewcomments_editcomment'] = 'Editer le commentaire';
$this->trads['mod_admin_genericblogsmanager_viewcomments_deletecomment'] = 'Supprimer le commentaire';
$this->trads['mod_admin_genericblogsmanager_viewcomments_updatecommentstatus'] = 'Mettre &agrave; jour le status du commentaire';
$this->trads['mod_admin_genericblogsmanager_comment_deletemessage'] = 'Etes-vous s&ucirc;r de vouloir supprimer ce commentaire ? Cette action est irreversible.';

/* edit comment interface */
$this->trads['mod_admin_genericblogsmanager_editcomment_editortitle'] = ' : Editer un commentaire';
$this->trads['mod_admin_genericblogsmanager_editcomment_objectid'] = 'Commentaire n&deg;%s';
$this->trads['mod_admin_genericblogsmanager_editcomment_parentnews'] = 'Pour l\'actualit&eacute; : ';
$this->trads['mod_admin_genericblogsmanager_editcomment_date'] = 'Ecrit le : ';
$this->trads['mod_admin_genericblogsmanager_editcomment_ipaddress'] = 'depuis l\'adresse IP : ';
$this->trads['mod_admin_genericblogsmanager_editcomment_status'] = 'Etat : ';
$this->trads['mod_admin_genericblogsmanager_editcomment_author'] = 'Auteur : ';
$this->trads['mod_admin_genericblogsmanager_editcomment_email'] = 'E-mail : ';
$this->trads['mod_admin_genericblogsmanager_editcomment_website'] = 'Site web : ';
$this->trads['mod_admin_genericblogsmanager_editcomment_title'] = 'Titre : ';
$this->trads['mod_admin_genericblogsmanager_editcomment_content'] = 'Contenu : ';


/* view comments & edit comment interfaces messages */
$this->trads['mod_admin_genericblogsmanager_message_savecomment_done'] = 'Sauvegarde du commentaire en cours...';
$this->trads['mod_admin_genericblogsmanager_message_savecomment_failed'] = 'Une erreur est survenue lors de la sauvegarde du commentaire.';
$this->trads['mod_admin_genericblogsmanager_message_deletecomment_done'] = 'Suppression du commentaire en cours...';
$this->trads['mod_admin_genericblogsmanager_message_deletecomment_failed'] = 'Une erreur est survenue lors de la suppression du commentaire.';
$this->trads['mod_admin_genericblogsmanager_message_updatecomment_done'] = 'Mise &agrave; jour du commentaire en cours...';
$this->trads['mod_admin_genericblogsmanager_message_updatecomment_failed'] = 'Une erreur est survenue lors de la mise &agrave; jour du commentaire.';

/* comment save failed errors */
$this->trads['mod_admin_genericblogsmanager_savecommentfailed_internalerror'] = 'Une erreur est survenue lors de l\'enregistrement du commentaire';
$this->trads['mod_admin_genericblogsmanager_savecommentfailed_emptycontent'] = 'Le contenu du commentaire ne peut &ecirc;tre vide.';
$this->trads['mod_admin_genericblogsmanager_savecommentfailed_emptyauthor'] = 'Le pseudo est obligatoire.';
$this->trads['mod_admin_genericblogsmanager_savecommentfailed_invalidemail'] = 'L\'email est obligatoire et doit &ecirc;tre valide.';

?>
