<?php
/**
 * @brief Content_GenericLegalMentions Module site conditions, french sub layout.
 * @details Plugin / Module layout
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Jan 2020
 * @date Modification: Feb 2020
 * @copyright 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
?>
<div id="LM-Conditions" class="anchor" title="2. Conditions g&eacute;n&eacute;rales d'utilisation du site et des services propos&eacute;s"></div>

<h2 class="eTitle2">
    2. Conditions g&eacute;n&eacute;rales d'utilisation du site et des services propos&eacute;s
</h2>

<p class="eContent1">
    Les pr&eacute;sentes mentions ont pour objet de d&eacute;finir les modalit&eacute;s selon lesquelles <?= $this->contentItem->get_editorFullName(); ?> met &agrave; la disposition des internautes son <span class="eContent2">Site</span> internet <?= $this->contentItem->get_websiteURL(); ?> et les conditions selon lesquelles les <span class="eContent2">Internautes</span> acc&egrave;dent et utilisent ce site internet.
</p>

<p class="eContent1">
    L'utilisation du site <?= $this->contentItem->get_websiteURL(); ?> implique l'acceptation pleine et enti&egrave;re des conditions g&eacute;n&eacute;rales d'utilisation ci-apr&egrave;s d&eacute;crites. Ces conditions d'utilisation sont susceptibles d'&ecirc;tre modifi&eacute;es ou compl&eacute;t&eacute;es &agrave; tout moment, les <span class="eContent2">Utilisateurs</span> du <span class="eContent2">Site</span> <?= $this->contentItem->get_websiteURL(); ?> sont donc invit&eacute;s &agrave; les consulter de mani&egrave;re r&eacute;guli&egrave;re.
</p>

<p class="eContent1">
    L'acc&egrave;s et l'utilisation du site <?= $this->contentItem->get_websiteURL(); ?> entra&icirc;nent votre adh&eacute;sion aux pr&eacute;sentes mentions l&eacute;gales. Si vous n'&ecirc;tes pas en accord avec les clauses &eacute;nonc&eacute;es ci-apr&egrave;s, il vous est conseill&eacute; de ne pas utiliser ce <span class="eContent2">Site</span>.
</p>

<p class="eContent1">
    Ce site internet est normalement accessible &agrave; tout moment aux <span class="eContent2">Utilisateurs</span>. Une interruption pour raison de maintenance technique peut &ecirc;tre toutefois d&eacute;cid&eacute;e par <?= $this->contentItem->vars['owner_name']; ?>, qui s'efforcera alors de communiquer pr&eacute;alablement aux <span class="eContent2">Utilisateurs</span> les dates et heures de l'intervention. Le site web <?= $this->contentItem->get_websiteURL(); ?> est mis &agrave; jour r&eacute;guli&egrave;rement par <?= $this->contentItem->get_editorFullName(); ?><?php if ($this->contentItem->has_content('creator_name')) : ?> et son <span class="eContent2">Prestataire</span><?php endif; ?>.
</p>

<p class="eContent1">
    De la m&ecirc;me façon, les mentions l&eacute;gales peuvent &ecirc;tre modifi&eacute;es &agrave; tout moment : elles s'imposent n&eacute;anmoins &agrave; l'<span class="eContent2">Utilisateur</span> qui est invit&eacute; &agrave; s'y r&eacute;f&eacute;rer le plus souvent possible afin d'en prendre connaissance.
</p>

<p class="eContent1">
    &nbsp;
</p>
