<?php
/**
 * @brief Content_GenericLegalMentions Module site copyright, french sub layout.
 * @details Plugin / Module layout
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Jan 2020
 * @date Modification: Feb 2020
 * @copyright 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
?>
<div id="LM-Copyright" class="anchor" title="5. Propri&eacute;t&eacute; intellectuelle et contrefa&ccedil;ons"></div>

<h2 class="eTitle2">
    5. Propri&eacute;t&eacute; intellectuelle et contrefa&ccedil;ons
</h2>

<p class="eContent1">
    Le <span class="eContent2">Site</span>  constitue une &oelig;uvre de l'esprit prot&eacute;g&eacute;e par les dispositions du Code de la Propri&eacute;t&eacute; Intellectuelle et des R&eacute;glementations Internationales applicables. L'<span class="eContent2">Internaute</span> ne peut en aucune mani&egrave;re r&eacute;utiliser, c&eacute;der ou exploiter pour son propre compte tout ou partie des &eacute;l&eacute;ments ou travaux du <span class="eContent2">Site</span>.
</p>

<p class="eContent1">
    <?= ucfirst($this->contentItem->get_editorFullName()); ?> est propri&eacute;taire des droits de propri&eacute;t&eacute; intellectuelle et d&eacute;tient les droits d'usage sur tous les &eacute;l&eacute;ments accessibles sur le site internet, notamment les textes, images, graphismes, logos, vid&eacute;os, icônes, sons et code source. Toute reproduction, repr&eacute;sentation, modification, publication, adaptation de tout ou partie des &eacute;l&eacute;ments du site, quel que soit le moyen ou le proc&eacute;d&eacute; utilis&eacute;, est interdite, sauf autorisation &eacute;crite pr&eacute;alable de <?= $this->contentItem->get_editorFullName(); ?>.
</p>

<p class="eContent1">
    Toute exploitation non autoris&eacute;e du site ou de l'un des &eacute;l&eacute;ments qu'il contient sera consid&eacute;r&eacute;e comme constitutive d'une contrefa&ccedil;on et poursuivie conform&eacute;ment aux dispositions des articles L.335-2 et suivants du Code de Propri&eacute;t&eacute; Intellectuelle.
</p>

<p class="eContent1">
    &nbsp;
</p>
