<?php
/**
 * @brief Content_GenericLegalMentions Module site limitations, french sub layout.
 * @details Plugin / Module layout
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Jan 2020
 * @date Modification: Feb 2020
 * @copyright 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
?>
<div id="LM-Limitations" class="anchor" title="4. Limitations contractuelles sur les donn&eacute;es techniques"></div>

<h2 class="eTitle2">
    4. Limitations contractuelles sur les donn&eacute;es techniques
</h2>

<p class="eContent1">
    Le site utilise la technologie JavaScript. Le <span class="eContent2">Site</span> internet ne pourra &ecirc;tre tenu responsable de dommages mat&eacute;riels li&eacute;s &agrave; l'utilisation du site. De plus, l'<span class="eContent2">Utilisateur</span> du site s'engage &agrave; acc&eacute;der au site en utilisant un mat&eacute;riel r&eacute;cent, ne contenant pas de virus et avec un navigateur de derni&egrave;re g&eacute;n&eacute;ration mis-&agrave;-jour. Le <span class="eContent2">Site</span> est h&eacute;berg&eacute; chez un prestataire sur le territoire de l'Union Europ&eacute;enne conform&eacute;ment aux dispositions du R&egrave;glement G&eacute;n&eacute;ral sur la Protection des Donn&eacute;es (RGPD : n&deg; 2016-679).
</p>

<p class="eContent1">
    L'objectif est d'apporter une prestation qui assure le meilleur taux d'accessibilit&eacute;. L'h&eacute;bergeur assure la continuit&eacute; de son service 24 heures sur 24, tous les jours de l'ann&eacute;e. Il se r&eacute;serve n&eacute;anmoins la possibilit&eacute; d'interrompre le service d'h&eacute;bergement pour les dur&eacute;es les plus courtes possibles notamment &agrave; des fins de maintenance, d'am&eacute;lioration de ses infrastructures, de d&eacute;faillance de ses infrastructures ou si les prestations et services g&eacute;n&egrave;rent un trafic r&eacute;put&eacute; anormal.
</p>

<p class="eContent1">
     <?= ucfirst($this->contentItem->get_editorFullName()); ?> et l'h&eacute;bergeur ne pourront &ecirc;tre tenus responsables en cas de dysfonctionnement du r&eacute;seau Internet, des lignes t&eacute;l&eacute;phoniques ou du mat&eacute;riel informatique et de t&eacute;l&eacute;phonie li&eacute; notamment &agrave; l'encombrement du r&eacute;seau emp&ecirc;chant l'acc&egrave;s au serveur.
</p>

<p class="eContent1">
    &nbsp;
</p>
