<?php
/**
 * @brief Content_GenericLegalMentions Module site lins, french sub layout.
 * @details Plugin / Module layout
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Jan 2020
 * @date Modification: Feb 2020
 * @copyright 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
?>
<div id="LM-Links" class="anchor" title="11. Liens"></div>

<h2 class="eTitle2">
    11. Liens
</h2>

<p class="eContent1">
    Le <span class="eContent2">Site</span> <?= $this->contentItem->get_websiteURL(); ?> peut contenir des liens vers des sites internet externes, ind&eacute;pendants de <?= $this->contentItem->get_editorFullName(); ?>, et disposant de mentions l&eacute;gales sp&eacute;cifiques. <?= ucfirst($this->contentItem->get_editorFullName()); ?> n'a aucun contr&ocirc;le sur la gestion de ces sites et d&eacute;cline toute responsabilit&eacute; sur les contenus de leurs pages. La visite de ces sites, ind&eacute;pendants de <?= $this->contentItem->get_editorFullName(); ?>, se fait sous la seule responsabilit&eacute; de l'<span class="eContent2">Utilisateur</span>.
</p>

<p class="eContent1">
    &nbsp;
</p>
