<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a
 * Object Version	: 1.0
 * Object Type	        : Plugin / Module Layout
 * Create Date	       	: Jul 2008
 * Last Modif Date	: Jul 2008
 * 
 * Content_SimpleText Module site layout : without box
*/
?>
<h1 class="eTitle1">
<?= $this->get_translation('site_title'); ?>
</h1>
<?=$this->sitemap;?>