<?php
/**
 * @brief Admin_PluginManager Module help french structure
 * @details Plugin / Module layout
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Fev 2007
 * @date Modification: Nov 2020
 * @copyright 2007 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->help = array(
    'main'  => array(
        'html'  => 'desc.html.inc'
    ),
);
?>
