<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Dictionnary
 * Creation Date	: Feb 2016
 * Last Modif Date	: Feb 2016
 *
 * ReCaptcha language french dictionnary
 */

$this->trads['input_recaptcha_error_captcha_missing'] = 'Captcha manquant, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_missing_input_secret'] = 'Configuration du Captcha erron&eacute;e, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_invalid_input_secret'] = 'Configuration du Captcha erron&eacute;e, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_missing_input_response'] = 'Merci de cliquer le Captcha pour v&eacute;rifier que vous &ecirc;tes bien un humain.';
$this->trads['input_recaptcha_error_invalid_input_response'] = 'Configuration du Captcha erron&eacute;e,  impossible de valider le formulaire.';
?>