<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0.1
 * Object Type      : Plugin / Input Dictionnary
 * Creation Date	: Feb 2016
 * Last Modif Date	: Jun 2018
 *
 * ReCaptcha language french dictionnary
 */

/* errors */
$this->trads['input_recaptcha_error_captcha_missing'] = 'Captcha manquant, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_missing_input_secret'] = 'Configuration du Captcha erron&eacute;e, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_invalid_input_secret'] = 'Configuration du Captcha erron&eacute;e, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_missing_input_response'] = 'Merci de cliquer le Captcha pour v&eacute;rifier que vous &ecirc;tes bien un humain.';
$this->trads['input_recaptcha_error_invalid_input_response'] = 'Configuration du Captcha erron&eacute;e, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_timeout_or_duplicate'] = 'D&eacute;lai d&eacute;pass&eacute; ou captcha dupliqu&eacute;.';

/* configuration */
$this->trads['input_recaptcha_formitem_publickey'] = 'Cl&eacute; publique : ';
$this->trads['input_recaptcha_formitem_privatekey'] = 'Cl&eacute; priv&eacute;e : ';
?>