<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Dictionnary
 * Creation Date	: Mar 2016
 * Last Modif Date	: Mar 2016
 *
 * ReCaptcha language english  dictionnary
 */

/* errors */
$this->trads['input_recaptcha_error_captcha_missing'] = 'Missing captcha, we can\'t validate the form.';
$this->trads['input_recaptcha_error_missing_input_secret'] = 'Captcha configuration error, we can\'t validate the form.';
$this->trads['input_recaptcha_error_invalid_input_secret'] = 'Captcha configuration error, we can\'t validate the form.';
$this->trads['input_recaptcha_error_missing_input_response'] = 'Please confirm you are a real human, by clicking the captcha box.';
$this->trads['input_recaptcha_error_invalid_input_response'] = 'Captcha configuration error, we can\'t validate the form.';

/* configuration */
$this->trads['input_recaptcha_formitem_publickey'] = 'Public key: ';
$this->trads['input_recaptcha_formitem_privatekey'] = 'Private key: ';
?>