<?php
/**
 * @brief ReCaptcha Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/ReCaptcha/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Mar 2016
 * @date Modification: Jul 2018
 * @copyright 2016 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* errors */
$this->trads['input_recaptcha_error_captcha_missing'] = 'Captcha manquant, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_missing_input_secret'] = 'Configuration du Captcha erron&eacute;e, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_invalid_input_secret'] = 'Configuration du Captcha erron&eacute;e, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_missing_input_response'] = 'Merci de cliquer le Captcha pour v&eacute;rifier que vous &ecirc;tes bien un humain.';
$this->trads['input_recaptcha_error_invalid_input_response'] = 'Configuration du Captcha erron&eacute;e, impossible de valider le formulaire.';
$this->trads['input_recaptcha_error_timeout_or_duplicate'] = 'D&eacute;lai d&eacute;pass&eacute; ou captcha dupliqu&eacute;.';

/* configuration */
$this->trads['input_recaptcha_formitem_publickey'] = 'Cl&eacute; publique : ';
$this->trads['input_recaptcha_formitem_privatekey'] = 'Cl&eacute; priv&eacute;e : ';
?>
