<?php
/**
 * @brief Content_GenericGlossaryViewer module, french dictionnary.
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: May 2010
 * @date Modification: Jan 2020
 * @copyright 2010 - 2020 Ideogram Design
 */
$this->trads['mod_content_genericglossaryviewer_title'] = 'Affichage du lexique';
$this->trads['mod_content_genericglossaryviewer_desc'] = '';

/* layout list */
$this->trads['mod_content_genericglossaryviewer_layout_nobox'] = 'Sans cadre';

/* gpc source list */
$this->trads['mod_content_genericglossaryviewer_gpc_name'] = 'Contr&ocirc;leur';

/* page mode list */
$this->trads['mod_content_genericglossaryviewer_configpagemode_bypage'] = 'Par page';
$this->trads['mod_content_genericglossaryviewer_configpagemode_byletter'] = 'Par lettre';
$this->trads['mod_content_genericglossaryviewer_configpagemode_bygroup1'] = 'Par groupe (A-L / M-Z)';
$this->trads['mod_content_genericglossaryviewer_configpagemode_bygroup2'] = 'Par groupe (A-G / H-Q / R-Z)';
$this->trads['mod_content_genericglossaryviewer_configpagemode_bygroup3'] = 'Par groupe (A-D / E-L / M-S / T-Z)';

/* admin */
$this->trads['mod_content_genericglossaryviewer_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericglossaryviewer_tabcontent'] = 'Introduction';
$this->trads['mod_content_genericglossaryviewer_formitem_layout'] = 'Affichage : ';
$this->trads['mod_content_genericglossaryviewer_formitem_category'] = 'Cat&eacute;gorie : ';
$this->trads['mod_content_genericglossaryviewer_formitem_pagemode'] = 'Mode de liste : ';
$this->trads['mod_content_genericglossaryviewer_formitem_wordbypage'] = 'Mots par page : ';
$this->trads['mod_content_genericglossaryviewer_formitem_gpcsource'] = 'Design sp&eacute;cifi&eacute; par : ';
$this->trads['mod_content_genericglossaryviewer_formitem_displayed_categories'] = 'Cat&eacute;gories affich&eacute;es : ';
$this->trads['mod_content_genericglossaryviewer_categories_all'] = 'Toutes';

/* save */
$this->trads['mod_content_genericglossaryviewer_savedone'] = 'Sauvegarde en cours...';
?>
