<?php
/**
 * @brief ScelliusPayment Input english dictionary
 * @details Plugin / Input Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Aug 2021
 * @date Modification: Aug 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* Mode values */
$this->trads['input_scelliuspayment_mode_test'] = 'Test';
$this->trads['input_scelliuspayment_mode_production'] = 'Live';

/* Configuration */
$this->trads['input_scelliuspayment_formtitle_operation'] = 'Operation';
$this->trads['input_scelliuspayment_formitem_mode'] = 'Mode: ';

$this->trads['input_scelliuspayment_formtitle_bankkeys'] = 'Bank keys';
$this->trads['input_scelliuspayment_formitem_test'] = 'Test: ';
$this->trads['input_scelliuspayment_formitem_live'] = 'Live: ';

$this->trads['input_scelliuspayment_formtitle_bankconfiguration'] = 'Bank configuration';
$this->trads['input_scelliuspayment_formitem_site'] = 'Shop: ';
$this->trads['input_scelliuspayment_formitem_hashmode'] = 'Hash: ';

/* Site */
$this->trads['input_scelliuspayment_redirectobankmessage'] = 'You will be redirected to the banking service.';
$this->trads['input_scelliuspayment_redirectobankmessage2'] = 'If not, <a href="%s" class="%s">follow this link</a>.';
?>
