<?php
/**
 * @brief ScelliusPayment Input french dictionary
 * @details Plugin / Input Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Aug 2021
 * @date Modification: Aug 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* Mode values */
$this->trads['input_scelliuspayment_mode_test'] = 'Test';
$this->trads['input_scelliuspayment_mode_production'] = 'Production';

/* Configuration */
$this->trads['input_scelliuspayment_formtitle_operation'] = 'Fonctionnement';
$this->trads['input_scelliuspayment_formitem_mode'] = 'Mode : ';

$this->trads['input_scelliuspayment_formtitle_bankkeys'] = 'Cl&eacute;s bancaires';
$this->trads['input_scelliuspayment_formitem_test'] = 'Test : ';
$this->trads['input_scelliuspayment_formitem_live'] = 'Live : ';

$this->trads['input_scelliuspayment_formtitle_bankconfiguration'] = 'Configuration bancaire';
$this->trads['input_scelliuspayment_formitem_site'] = 'Boutique : ';
$this->trads['input_scelliuspayment_formitem_hashmode'] = 'Chiffrement : ';

/* Site */
$this->trads['input_scelliuspayment_redirectobankmessage'] = 'Vous allez &ecirc;tre redirig&eacute; vers le service bancaire.';
$this->trads['input_scelliuspayment_redirectobankmessage2'] = 'Si ce n\'est pas le cas, <a href="%s" class="%s">cliquez ici</a>.';
?>
