<?php
/**
 * @brief GenericVCardHandler Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/GenericVCardHandler/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Nov 2014
 * @date Modification: Jul 2018
 * @copyright 2014 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
/* CaMykS error generic message */
$this->trads['input_genericvcardhandler_fatalerror_title'] = 'Gestionnaire de vCard';
$this->trads['input_genericvcardhandler_fatalerror_desc'] = 'Une erreur est survenue : ';
$this->trads['input_genericvcardhandler_fatalerror_genendig'] = 'Si le probl&egrave;me persiste, merci de contacter l\'administrateur du site.';

/* specific error messages */
$this->trads['input_genericvcardhandler_fatalerror_noknownaction'] = 'L\'action "%s" est ind&eacute;termin&eacute;e.';
$this->trads['input_genericvcardhandler_fatalerror_loadingfailed'] = 'Les vCards version "%s" ne sont pas prises en charge.';
$this->trads['input_genericvcardhandler_fatalerror_cannotdetectvcardversion'] = 'Impossible de d&eacute;tecter le format de la vCard.';
$this->trads['input_genericvcardhandler_fatalerror_cardreadingfailed'] = 'Impossible de lire la vCard.';
$this->trads['input_genericvcardhandler_fatalerror_multiplecontactsnotallowed'] = 'La vCard contient plus d\'un contact.';
$this->trads['input_genericvcardhandler_fatalerror_emptyfile'] = 'Le fichier est vide.';
$this->trads['input_genericvcardhandler_fatalerror_openfilefailed'] = 'Une erreur est survenue lors de l\'ouverture du fichier.';
?>
