<?php
/**
 * @brief Admin_ContentPage Module english dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.2.1
 * @date Creation: Sep 2009
 * @date Modification: Jan 2021
 * @copyright 2009 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_contentpage_title'] = 'Page Manager';
$this->trads['mod_admin_contentpage_desc'] = 'Manager website pages';

/* global */
$this->trads['mod_admin_contentpage_pagetitle'] = 'Page';
$this->trads['mod_admin_contentpage_page'] = 'Page';
$this->trads['mod_admin_contentpage_pages'] = 'Pages';

/* rights */
$this->trads['mod_admin_contentpage_rights_modify_root'] = 'Modify page tree root';
$this->trads['mod_admin_contentpage_rights_modify_rights'] = 'Modify page rights';
$this->trads['mod_admin_contentpage_rights_modify_structure'] = 'Modify page tree';
$this->trads['mod_admin_contentpage_rights_modify_models'] = 'Modify models';
$this->trads['mod_admin_contentpage_rights_overwrite_models'] = 'Overwrite models';
$this->trads['mod_admin_contentpage_rights_putinline'] = 'Put inline';
$this->trads['mod_admin_contentpage_rights_configuration'] = 'Configuration';

/* configuration */
$this->trads['mod_admin_contentpage_configuration'] = 'Configuration';
$this->trads['mod_admin_contentpage_select_sitepage'] = 'Select site page';
$this->trads['mod_admin_contentpage_page_notfound'] = 'Page not found';

/* configuration - navigations */
$this->trads['mod_admin_contentpage_formtitle_navigations'] = 'Navigations';
$this->trads['mod_admin_contentpage_formitem_main'] = 'Primary: ';
$this->trads['mod_admin_contentpage_formitem_alt'] = 'Secondary: ';
$this->trads['mod_admin_contentpage_navigation_none'] = 'None';
$this->trads['mod_admin_contentpage_add_new_navigation'] = 'Add a navigation';
$this->trads['mod_admin_contentpage_remove_navigation'] = 'Delete navigation';
$this->trads['mod_admin_contentpage_name'] = 'Name';

/* configuration - key pages */
$this->trads['mod_admin_contentpage_formtitle_keypages'] = 'Key pages';
$this->trads['mod_admin_contentpage_keypage_none'] = 'None';
$this->trads['mod_admin_contentpage_add_new_keypage'] = 'Add a key page';
$this->trads['mod_admin_contentpage_remove_keypage'] = 'Delete key page';
$this->trads['mod_admin_contentpage_key'] = 'Key';

/* configuration - actions */
$this->trads['mod_admin_contentpage_formtitle_actions'] = 'Actions';
$this->trads['mod_admin_contentpage_formitem_w3cvalidator'] = 'W3C validation: ';

/* configuration - 404 fallback */
$this->trads['mod_admin_contentpage_formtitle_pagesnotfound'] = 'Pages not found';
$this->trads['mod_admin_contentpage_formitem_404fallback'] = 'Fallback: ';
$this->trads['mod_admin_contentpage_config_404fallback_homedisplay'] = 'Display home page';
$this->trads['mod_admin_contentpage_config_404fallback_homeredirect'] = 'Redirect to home page';
$this->trads['mod_admin_contentpage_config_404fallback_pagedisplay'] = 'Display website page';
$this->trads['mod_admin_contentpage_config_404fallback_pageredirect'] = 'Redirect to website page';
$this->trads['mod_admin_contentpage_config_404fallback_error404display'] = 'Display "Error 404" page';
$this->trads['mod_admin_contentpage_config_404fallback_error404redirect'] = 'Redirect to "Error 404" page';
$this->trads['mod_admin_contentpage_formitem_file'] = 'File: ';
$this->trads['mod_admin_contentpage_formitem_page'] = 'Page: ';
$this->trads['mod_admin_contentpage_formitem_send404header'] = 'Send 404 header: ';
$this->trads['mod_admin_contentpage_config_w3cvalidator_disabled'] = 'Disabled';
$this->trads['mod_admin_contentpage_config_w3cvalidator_enabled'] = 'Enabled';

/* configuration - site */
$this->trads['mod_admin_contentpage_formtitle_sitetags'] = 'Header tags';
$this->trads['mod_admin_contentpage_formitem_ogmeta'] = 'Open Graph metas: ';
$this->trads['mod_admin_contentpage_config_ogmeta_disabled'] = 'Disabled';
$this->trads['mod_admin_contentpage_config_ogmeta_enabled'] = 'Enabled';
$this->trads['mod_admin_contentpage_formitem_hreflang'] = 'Hreflang metas: ';
$this->trads['mod_admin_contentpage_config_hreflang_disabled'] = 'Disabled';
$this->trads['mod_admin_contentpage_config_hreflang_enabled'] = 'Enabled';

/* finder page */
$this->trads['mod_admin_contentpage_is_homepage'] = 'Homepage';
$this->trads['mod_admin_contentpage_level'] = 'Level %s';
$this->trads['mod_admin_contentpage_altercolumn'] = 'Actions';
$this->trads['mod_admin_contentpage_deletepagemessage'] = 'Are you sur to want to delete this page ? This action is irreversible';
$this->trads['mod_admin_contentpage_movepagemessage'] = 'Are you sur to want to move the page here?';
$this->trads['mod_admin_contentpage_movepagefailedmessage'] = 'Page can\'t be moved here.';

/* page action layered menu */
$this->trads['mod_admin_contentpage_w3c_validation'] = 'W3C Validation';
$this->trads['mod_admin_contentpage_move'] = 'Move';
$this->trads['mod_admin_contentpage_move_up'] = 'Move up';
$this->trads['mod_admin_contentpage_move_down'] = 'Move down';

/* column action layered menu */
$this->trads['mod_admin_contentpage_paste_moved_page'] = 'Paste';
$this->trads['mod_admin_contentpage_newpage'] = 'Insert page';

/* main menu */
$this->trads['mod_admin_contentpage_newmodel'] = 'Add a model';
$this->trads['mod_admin_contentpage_modelobject'] = 'Model "%s"';
$this->trads['mod_admin_contentpage_editmodel'] = 'Modify';
$this->trads['mod_admin_contentpage_deletemodel'] = 'Delete';
$this->trads['mod_admin_contentpage_deletemodelmessage'] = 'Are you sur to want to delete this model ? This action is irreversible.';

/* edit page : tabs */
$this->trads['mod_admin_contentpage_tabgeneral'] = 'Properties';
$this->trads['mod_admin_contentpage_tabcontent'] = 'Content';
$this->trads['mod_admin_contentpage_tabmetas'] = 'Metas';


/* edit page : types */
$this->trads['mod_admin_contentpage_type_page'] = 'Page';
$this->trads['mod_admin_contentpage_type_model'] = 'Model';

/* edit page : properties tab */
$this->trads['mod_admin_contentpage_formitem_actived'] = 'Actived: ';
$this->trads['mod_admin_contentpage_formitem_ishomepage'] = 'Website home: ';
$this->trads['mod_admin_contentpage_defaultfromsite'] = 'Default (site)';
$this->trads['mod_admin_contentpage_formtitle_searchenginebot'] = 'Search engine bots';
$this->trads['mod_admin_contentpage_formitem_contentindexing'] = 'Content indexing: ';
$this->trads['mod_admin_contentpage_formitem_linkfollowup'] = 'Links following: ';
$this->trads['mod_admin_contentpage_formtitle_admindata'] = 'Admin information';
$this->trads['mod_admin_contentpage_formitem_owner'] = 'Owner: ';
$this->trads['mod_admin_contentpage_formitem_editorgroup'] = 'Editing group: ';
$this->trads['mod_admin_contentpage_formitem_validatorgroup'] = 'Validating group : ';
$this->trads['mod_admin_contentpage_formitem_creation_date'] = 'Creation date: ';
$this->trads['mod_admin_contentpage_formitem_modification_date'] = 'Modification date: ';
$this->trads['mod_admin_contentpage_formitem_wfstatus'] = 'State: ';
$this->trads['mod_admin_contentpage_formitem_wfversionx'] = 'Version %s: ';

/* edit page : metas tab */
$this->trads['mod_admin_contentpage_metacontent'] = 'Value';
$this->trads['mod_admin_contentpage_metalanguage'] = 'Language';
$this->trads['mod_admin_contentpage_metalanguage_all'] = 'All';
$this->trads['mod_admin_contentpage_metamethod'] = 'Method';
$this->trads['mod_admin_contentpage_metamethod_hidden'] = 'Hidden';
$this->trads['mod_admin_contentpage_metamethod_name'] = 'Meta "name"';
$this->trads['mod_admin_contentpage_metamethod_http'] = 'Meta "http-equiv"';
$this->trads['mod_admin_contentpage_metamethod_linkrel'] = 'Link "rel"';

/* edit page : content tab */
$this->trads['mod_admin_contentpage_none'] = 'None';
$this->trads['mod_admin_contentpage_defaultfrompage'] = 'Default (page)';
$this->trads['mod_admin_contentpage_no_content'] = 'No editable content';
$this->trads['mod_admin_contentpage_new_content'] = 'New content';
$this->trads['mod_admin_contentpage_formitem_model'] = 'Page model: ';
$this->trads['mod_admin_contentpage_formitem_theme'] = 'Theme: ';
$this->trads['mod_admin_contentpage_formitem_template'] = 'Template: ';
$this->trads['mod_admin_contentpage_formitem_modules'] = 'Modules: ';
$this->trads['mod_admin_contentpage_formitem_module'] = 'Module: ';
$this->trads['mod_admin_contentpage_formitem_content'] = 'Content: ';
$this->trads['mod_admin_contentpage_blockx'] = 'Block &#35;%s';
$this->trads['mod_admin_contentpage_edit_module'] = 'Valid page and edit this content';

/* edit page : localized data tabs */
$this->trads['mod_admin_contentpage_formitem_pagetitle'] = 'Page title: ';
$this->trads['mod_admin_contentpage_formitem_pageshorttitle'] = 'Short title: ';
$this->trads['mod_admin_contentpage_formitem_keywords'] = 'Keywords: ';

/* save page */
$this->trads['mod_admin_contentpage_save'] = 'Page save in progress...';
$this->trads['mod_admin_contentpage_savefailed'] = 'An error has occured while saving the page.';

/* move page */
$this->trads['mod_admin_contentpage_pagemoved'] = 'Page move in progress...';

/* delete page */
$this->trads['mod_admin_contentpage_deletepage'] = 'Page delete in progress...';
$this->trads['mod_admin_contentpage_deletepagefailed_haschildren'] = 'Page %s can\'t be deleted, because it contains sub pages.';
$this->trads['mod_admin_contentpage_modifypageerror'] = 'An error as occured while editing this page.';

/* save config messages */
$this->trads['mod_admin_contentpage_config_saved'] = 'Configuration saved.';
$this->trads['mod_admin_contentpage_config_notsaved'] = 'An error has occured while saving the configuration.';


/* statistics */
$this->trads['mod_admin_contentpage_stat_sitepage'] = 'Viewed pages';
$this->trads['mod_admin_contentpage_stat_sitepage_main'] = 'viewed page(s)';
$this->trads['mod_admin_contentpage_stat_sitepage_data1'] = 'Parameters';
$this->trads['mod_admin_contentpage_stat_sitepage_data2'] = 'Languages';
$this->trads['mod_admin_contentpage_stat_visits'] = 'Visits';
$this->trads['mod_admin_contentpage_stat_visits_main'] = 'Visit(s)';
$this->trads['mod_admin_contentpage_stat_firstpage'] = 'Viewed first pages';
$this->trads['mod_admin_contentpage_stat_firstpage_main'] = 'viewed first page(s)';
$this->trads['mod_admin_contentpage_stat_firstpage_data1'] = 'Parameters';
$this->trads['mod_admin_contentpage_stat_firstpage_data2'] = 'Languages';
$this->trads['mod_admin_contentpage_stat_referer'] = 'Referer websites';
$this->trads['mod_admin_contentpage_stat_referer_main'] = 'visit(s) from an other one';
?>
