<?php
/*
 * CaMykS Engine
 * Developed by            : camyks.net
 * Author                  : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version          : 1.0a
 * Object Version          : 1.0
 * Object Type             : Plugin / Template layout
 * Create Date             : Sep 2005
 * Last Modif Date         : Jun 2008
 *
 * DefaultPage HTML layout
 */
global $camyks;
?>
<div id="pageMain">
<?=$this->display_module(0)?>
</div>
