<?php
/**
 * @brief LimonetikPayment Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Oct 2020
 * @date Modification: Oct 2020
 * @copyright 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* Mode value list */
$this->trads['input_limonetikpayment_mode_test'] = 'Test';
$this->trads['input_limonetikpayment_mode_live'] = 'Production';

/* configuration */
$this->trads['input_limonetikpayment_formtitle_operation'] = 'Fonctionnement';
$this->trads['input_limonetikpayment_formitem_mode'] = 'Mode : ';
$this->trads['input_limonetikpayment_formtitle_authenticating'] = 'Authentification';
$this->trads['input_limonetikpayment_formitem_apikey'] = 'Cl&eacute; API : ';
$this->trads['input_limonetikpayment_formitem_merchandid'] = 'ID marchand : ';
$this->trads['input_limonetikpayment_formitem_payments'] = 'Paiements disponibles : ';

/* available payments */
$this->trads['input_limonetikpayment_payment_creditcard'] = 'Carte de cr&eacute;dit';
$this->trads['input_limonetikpayment_payment_conecs'] = 'Carte titre restaurant via Conecs';

/* site */
$this->trads['input_limonetikpayment_anerroroccured'] = 'Une erreur est survenue.';
$this->trads['input_limonetikpayment_back'] = 'Retour';
?>
