<?php
/**
 * @brief SmartGallery Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/SmartGallery/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jul 2007
 * @date Modification: Jul 2018
 * @copyright 2007 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* sliding methods */
$this->trads['input_smartgallery_slidingmethod_page'] = 'Par page';
$this->trads['input_smartgallery_slidingmethod_one'] = 'Par image';

/* themes */
$this->trads['input_smartgallery_theme_itunes'] = 'iTunes';
$this->trads['input_smartgallery_theme_safari'] = 'Safari';
$this->trads['input_smartgallery_theme_custom'] = 'Custom';
?>
