<?php
/**
 * @brief StripePayment Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: May 2020
 * @date Modification: May 2020
 * @copyright 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* running mode values */
$this->trads['input_stripepayment_runningmode_test'] = 'Test';
$this->trads['input_stripepayment_runningmode_production'] = 'Production';

/* mode values */
$this->trads['input_stripepayment_insertmode_internal'] = 'Internal';
$this->trads['input_stripepayment_insertmode_external'] = 'External';

/* configuration */
$this->trads['input_stripepayment_formtitle_operation'] = 'Operation';
$this->trads['input_stripepayment_formitem_runningmode'] = 'Operation mode : ';
$this->trads['input_stripepayment_formitem_insertmode'] = 'Insert mode: ';
$this->trads['input_stripepayment_formtitle_authentication_test'] = 'Authentication - Test mode';
$this->trads['input_stripepayment_formtitle_authentication_production'] = 'Authentication - Production mode';
$this->trads['input_stripepayment_formitem_apikey_public'] = 'Public API key: ';
$this->trads['input_stripepayment_formitem_apikey_private'] = 'Private API key: ';

/* site */
$this->trads['input_stripepayment_redirectobankmessage'] = 'You will be redirected to the banking service.';
$this->trads['input_stripepayment_redirectobankmessage2'] = 'If not, <a href="%s" class="%s">click here</a>.';
?>
