<?php
/**
 * @brief PaylinePayment input, french dictionary
 * @details Plugin / Input Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Apr 2026
 * @date Modification: Apr 2026
 * @copyright 2026 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* Mark: Mode values */
$this->trads['input_paylinepayment_runningmode_homologation'] = 'Homologation (Test)';
$this->trads['input_paylinepayment_runningmode_production'] = 'Production';

/* Mark: Configuration */
$this->trads['input_paylinepayment_formtitle_operation'] = 'Fonctionnement';
$this->trads['input_paylinepayment_formitem_runningmode'] = 'Mode : ';

$this->trads['input_paylinepayment_formtitle_authentication'] = 'D&eacute;tails d\'authentification';
$this->trads['input_paylinepayment_formitem_merchant_id'] = 'ID Commer&ccedil;ant : ';
$this->trads['input_paylinepayment_formitem_access_key'] = 'Cl&eacute; d\'acc&egrave;s : ';
$this->trads['input_paylinepayment_formitem_contract_number'] = 'Num&eacute;ro de Contrat : ';

/* Mark: Site */
$this->trads['input_paylinepayment_redirectobankmessage'] = 'Vous allez &ecirc;tre redirig&eacute; vers le service bancaire.';
$this->trads['input_paylinepayment_redirectobankmessage2'] = 'Si ce n\'est pas le cas, <a href="%s" class="%s">cliquez ici</a>.';

$this->trads['input_paylinepayment_error_occured_while_connecting_bank'] = 'Une erreur est survenue lors de la connexion &agrave; la banque.';
$this->trads['input_paylinepayment_error_sorry'] = 'Nous sommes d&eacute;sol&eacute;s de ne pouvoir donner suite &agrave; votre demande.';
$this->trads['input_paylinepayment_error_retry_later'] = 'Veuillez r&eacute;essayer plus tard ou nous contacter.';
$this->trads['input_paylinepayment_action_back'] = 'Retour';
?>

