<?php
/**
 * @brief SyntaxColoringEngine Input layout
 * @details Plugin / Input layout
 * @file plugin/input/SyntaxColoringEngine/html/input.html.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: May 2007
 * @date Modification: Jul 2018
 * @copyright 2007 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * @cond Exclude
 */
?>
<div>
    <?= $this->content; ?>
</div>
<?php
/**
 * @endcond Exclude
 */
?>
