<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Jun 2005
 * Last Modif Date	: Mar 2007
 *
 * Admin_MyAccount language dictionnary : French 
 */
$this->trads['mod_admin_myaccount_title'] = 'Mon compte';
$this->trads['mod_admin_myaccount_desc'] = 'Gestion de votre compte';

/* admin message */
$this->trads['mod_admin_myaccount_savedone'] = 'Votre compte est en cours de sauvegarde...';
$this->trads['mod_admin_myaccount_savefailed'] = 'La modification de votre compte a &eacute;chou&eacute;.';

/* write mode  */
$this->trads['mod_admin_myaccount_formitem_changepwd'] = 'Changer de mot de passe : ';

/* save errors */
$this->trads['mod_admin_myaccount_erroremptymail'] = 'L\'e-mail ne doit pas &ecirc;tre vide.';
$this->trads['mod_admin_myaccount_errorbadmail'] = 'L\'e-mail doit &ecirc;tre valide.';
$this->trads['mod_admin_myaccount_erroremptypwd'] = 'Le mot de passe ne doit pas &ecirc;tre vide.';
$this->trads['mod_admin_myaccount_errorshortpwd'] = 'Le mot de passe doit avoir une longueur sup&eacute;rieure &agrave; 3 caract&egrave;res.';
$this->trads['mod_admin_myaccount_errorconfpwd'] = 'Le mot de passe ne se confirme pas';
?>