<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Module Dictionnary
 * Creation Date    : Nov 2010
 * Last Modif Date  : Nov 2010
 *
 * Admin_GenericContactFormManager french dictionnary
 */
$this->trads['mod_admin_genericcontactformmanager_title'] = 'Formulaires de contact';
$this->trads['mod_admin_genericcontactformmanager_desc'] = 'Gestion des requ&ecirc;tes des visiteurs';
$this->trads['mod_admin_genericcontactformmanager_desc1'] = '1 requ&ecirc;te en attente!';
$this->trads['mod_admin_genericcontactformmanager_descx'] = '%s requ&ecirc;tes en attente!';

/* rights */
$this->trads['mod_admin_genericcontactformmanager_rights_editform'] = 'Edition des requ&ecirc;tes';
$this->trads['mod_admin_genericcontactformmanager_rights_editsubjects'] = 'Edition des objets';
$this->trads['mod_admin_genericcontactformmanager_rights_editconfig'] = 'Configuration';

/* messages status values */
$this->trads['mod_admin_genericcontactformmanager_messagesstatus_all'] = 'Tous';
$this->trads['mod_admin_genericcontactformmanager_messagesstatus_disabled'] = 'D&eacute;sactiv&eacute;s';
$this->trads['mod_admin_genericcontactformmanager_messagesstatus_enabled'] = 'Activ&eacute;s';
$this->trads['mod_admin_genericcontactformmanager_messagesstatus_pending'] = 'En attente';

/* message status values */
$this->trads['mod_admin_genericcontactformmanager_messagestatus_disabled'] = 'D&eacute;sactiv&eacute;';
$this->trads['mod_admin_genericcontactformmanager_messagestatus_enabled'] = 'Activ&eacute;';
$this->trads['mod_admin_genericcontactformmanager_messagestatus_pending'] = 'En attente';

/* config message validation values */
$this->trads['mod_admin_genericcontactformmanager_configmessagevalidation_auto'] = 'Automatique';
$this->trads['mod_admin_genericcontactformmanager_configmessagevalidation_admin'] = 'Administrative';

/* config notification status values */
$this->trads['mod_admin_genericcontactformmanager_confignotifstatus_disabled'] = 'D&eacute;sactiv&eacute;es';
$this->trads['mod_admin_genericcontactformmanager_confignotifstatus_enabled'] = 'Activ&eacute;es';

/* config notification recipient values */
$this->trads['mod_admin_genericcontactformmanager_confignotifrecipient_none'] = 'Aucun';

/* config statistic status values */
$this->trads['mod_admin_genericcontactformmanager_configstatstatus_disabled'] = 'D&eacute;sactiv&eacute;es';
$this->trads['mod_admin_genericcontactformmanager_configstatstatus_enabled'] = 'Activ&eacute;es';

/* admin main */
$this->trads['mod_admin_genericcontactformmanager_tabrequests'] = 'Requ&ecirc;tes';
$this->trads['mod_admin_genericcontactformmanager_tabsubjects'] = 'Sujets';
$this->trads['mod_admin_genericcontactformmanager_tabconfig'] = 'Configuration';

$this->trads['mod_admin_genericcontactformmanager_itempage'] = 'Page : ';
$this->trads['mod_admin_genericcontactformmanager_header_author'] = 'Auteur';
$this->trads['mod_admin_genericcontactformmanager_header_date'] = 'Date';

$this->trads['mod_admin_genericcontactformmanager_viewrequest'] = 'Voir cette requ&ecirc;te';
$this->trads['mod_admin_genericcontactformmanager_editrequest'] = 'Editer cette requ&ecirc;te';
$this->trads['mod_admin_genericcontactformmanager_deleterequest'] = 'Supprimer cette requ&ecirc;te';

/* admin edit / view config */
$this->trads['mod_admin_genericcontactformmanager_title_config'] = 'Configuration';
$this->trads['mod_admin_genericcontactformmanager_formtitle_messages'] = 'Messages';
$this->trads['mod_admin_genericcontactformmanager_formitem_validation'] = 'Validation : ';
$this->trads['mod_admin_genericcontactformmanager_formtitle_notifications'] = 'Notifications';
$this->trads['mod_admin_genericcontactformmanager_formitem_sender'] = 'E-mail d\'envoi : ';
$this->trads['mod_admin_genericcontactformmanager_formitem_recipients'] = 'Destinataires : ';

$this->trads['mod_admin_genericcontactformmanager_formtitle_statistics'] = 'Statistiques';

/* admin edit / view request */
$this->trads['mod_admin_genericcontactformmanager_title_requestid'] = 'Requ&ecirc;te n&deg;%s';
$this->trads['mod_admin_genericcontactformmanager_title_newrequest'] = 'Nouvelle requ&ecirc;te';
$this->trads['mod_admin_genericcontactformmanager_formitem_author'] = 'Auteur : ';
$this->trads['mod_admin_genericcontactformmanager_formitem_message'] = 'Message : ';

/* admin delete request */
$this->trads['mod_admin_genericcontactformmanager_deleterequestmessage'] = 'Etes vous s&ucirc;r de vouloir supprimer cette requ&ecirc;te ? Cette action est irr&eacute;versible.';
$this->trads['mod_admin_genericcontactformmanager_request_deleted'] = 'La requ&ecirc;te est en cours de suppression...';
$this->trads['mod_admin_genericcontactformmanager_message_notdeleted'] = 'Une erreur est survenue lors de la suppression de la requ&ecirc;te.';

/* admin save message */
$this->trads['mod_admin_genericcontactformmanager_message_saved'] = 'Le message est en cours de sauvegarde...';
$this->trads['mod_admin_genericcontactformmanager_message_notsaved'] = 'Une erreur est survenue lors de la sauvegarde du message.';

/* admin save config */
$this->trads['mod_admin_genericcontactformmanager_config_saved'] = 'La configuration est en cours de sauvegarde...';
$this->trads['mod_admin_genericcontactformmanager_config_notsaved'] = 'Une erreur est survenue lors de la sauvegarde de la configuration.';

/* notification */
$this->trads['mod_admin_genericcontactformmanager_notification_emailsubject'] = 'Une requ&ecirc;te vient d\'&ecirc;tre envoy&eacute;e.';
$this->trads['mod_admin_genericcontactformmanager_notification_emailcontent1'] = 'Une nouvelle requ&ecirc;te vient d\'&ecirc;tre envoy&eacute;e sur le  site internet <a href="%1$s">%2$s</a>.';
$this->trads['mod_admin_genericcontactformmanager_notification_emailsign'] = 'Webmaster';

/* site error message */
$this->trads['mod_admin_genericcontactformmanager_message_saveerror_authorempty'] = 'Merci d\'indiquer qui vous &ecirc;tes.';
$this->trads['mod_admin_genericcontactformmanager_message_saveerror_messageempty'] = 'Merci d\'ins&eacute;rer votre message.';
$this->trads['mod_admin_genericcontactformmanager_message_saveerror_emailempty'] = 'Merci d\'indiquer votre e-mail.';
$this->trads['mod_admin_genericcontactformmanager_message_saveerror_emailinvalid'] = 'Merci d\'indiquer un e-mail valide';

/* statistics */
$this->trads['mod_admin_genericcontactformmanager_stat_contactform_msg'] = 'Fomulaires de contact';
$this->trads['mod_admin_genericcontactformmanager_stat_contactform_msg_main'] = 'requ&ecirc;te(s) envoy&eacute;e(s).';
?>