<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Jul 2007
 * Last Modif Date	: Jul 2007
 *
 * Content_SimpleImage french dictionnary
*/
$this->trads['mod_content_simpleimage_title'] = 'Image Simple';
$this->trads['mod_content_simpleimage_desc'] = 'Affiche une image et sa description';

/* admin tabs */
$this->trads['mod_content_simpleimage_tabgeneral'] = 'G&eacute;n&eacute;ral';

/* layouts */
$this->trads['mod_content_simpleimage_layout'] = 'Layout';
$this->trads['mod_content_simpleimage_layout_text'] = 'Texte seul';
$this->trads['mod_content_simpleimage_layout_textbox'] = 'Encadr&eacute;(type %s)';
$this->trads['mod_content_simpleimage_layout_textmixtbox'] = 'Encadr&eacute;(mixte)';

/* admin interface */
$this->trads['mod_content_simpleimage_description'] = 'Description';
$this->trads['mod_content_simpleimage_image'] = 'Image';
$this->trads['mod_content_simpleimage_genericinfo'] = 'Informations g&eacute;n&eacute;rales.';
$this->trads['mod_content_simpleimage_localeinfo'] = 'Informations localis&eacute;es pour la langue "%s".';
$this->trads['mod_content_simpleimage_noimage'] = 'Aucune';
$this->trads['mod_content_simpleimage_maxfilesize'] = 'Taille max. : %s';
?>
