<?php
/**
 * @brief ReCaptcha Input layout
 * @details Plugin / Input layout
 * @file plugin/input/ReCaptcha/html/input_captcha.html.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Feb 2016
 * @date Modification: Jul 2018
 * @copyright 2016 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * @cond Exclude
 */
?>
<div class="g-recaptcha" data-sitekey="<?=$this->params['publicKey'];?>"></div>
<?php
/**
 * @endcond Exclude
 */
?>
