<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <jb.lebrun@ideogram-design.fr>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Engine / Dictionnary
 * Creation Date    : Jul 2017
 * Last Modif Date  : Jul 2017
 *
 * Canadian states german dictionnary
*/

$this->trads['canadianstate_ab'] = 'Alberta';
$this->trads['canadianstate_bc'] = 'British Columbia';
$this->trads['canadianstate_ipe'] = 'Prince Edward Island';
$this->trads['canadianstate_mb'] = 'Manitoba';
$this->trads['canadianstate_nb'] = 'New Brunswick';
$this->trads['canadianstate_ns'] = 'Nova Scotia';
$this->trads['canadianstate_on'] = 'Ontario';
$this->trads['canadianstate_qc'] = 'Qu&eacute;bec';
$this->trads['canadianstate_sk'] = 'Saskatchewan';
$this->trads['canadianstate_nl'] = 'Neufundland und Labrador';
$this->trads['canadianstate_nu'] = 'Nuvanut';
$this->trads['canadianstate_nt'] = 'Nordwest-Territorien';
$this->trads['canadianstate_yt'] = 'Yukon';