<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <jb.lebrun@ideogram-design.fr>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Engine / Dictionnary
 * Creation Date    : Jul 2017
 * Last Modif Date  : Jul 2017
 *
 * Canadian states portuguese dictionnary
*/

$this->trads['canadianstate_ab'] = 'Alberta';
$this->trads['canadianstate_bc'] = 'Col&uacute;mbia Brit&acirc;nica';
$this->trads['canadianstate_ipe'] = 'Ilha do Príncipe Eduardo';
$this->trads['canadianstate_mb'] = 'Manitoba';
$this->trads['canadianstate_nb'] = 'Nova Brunswick';
$this->trads['canadianstate_ns'] = 'Nova Esc&oacute;cia';
$this->trads['canadianstate_on'] = 'Ont&aacute;rio';
$this->trads['canadianstate_qc'] = 'Qu&eacute;bec';
$this->trads['canadianstate_sk'] = 'Saskatchewan';
$this->trads['canadianstate_nl'] = 'Terra Nova e Labrador';
$this->trads['canadianstate_nu'] = 'Nuvanut';
$this->trads['canadianstate_nt'] = 'Territ&oacute;rios do Noroeste';
$this->trads['canadianstate_yt'] = 'Yukon';