<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <jb.lebrun@ideogram-design.fr>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Engine / Dictionnary
 * Creation Date    : Jul 2017
 * Last Modif Date  : Jul 2017
 *
 * Canadian states spanish dictionnary
*/

$this->trads['canadianstate_ab'] = 'Alberta';
$this->trads['canadianstate_bc'] = 'Columbia Brit&aacute;nica';
$this->trads['canadianstate_ipe'] = 'Isla del Pr&iacute;ncipe Eduardo';
$this->trads['canadianstate_mb'] = 'Manitoba';
$this->trads['canadianstate_nb'] = 'Nuevo Brunswick';
$this->trads['canadianstate_ns'] = 'Nueva Escocia';
$this->trads['canadianstate_on'] = 'Ontario';
$this->trads['canadianstate_qc'] = 'Quebec';
$this->trads['canadianstate_sk'] = 'Saskatchewan';
$this->trads['canadianstate_nl'] = 'Terranova y Labrador';
$this->trads['canadianstate_nu'] = 'Nuvanut';
$this->trads['canadianstate_nt'] = 'Territorios del Noroeste';
$this->trads['canadianstate_yt'] = 'Yuk&oacute;n';