<?php
/**
 * @brief Canadian states portuguese dictionnary
 * @details Engine / Dictionnary
 * @file engine/locale/canadianstates/translation_pt.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jul 2017
 * @date Modification: Apr 2018
 * @copyright 2017 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['canadianstate_ab'] = 'Alberta';
$this->trads['canadianstate_bc'] = 'Col&uacute;mbia Brit&acirc;nica';
$this->trads['canadianstate_ipe'] = 'Ilha do Príncipe Eduardo';
$this->trads['canadianstate_mb'] = 'Manitoba';
$this->trads['canadianstate_nb'] = 'Nova Brunswick';
$this->trads['canadianstate_ns'] = 'Nova Esc&oacute;cia';
$this->trads['canadianstate_on'] = 'Ont&aacute;rio';
$this->trads['canadianstate_qc'] = 'Qu&eacute;bec';
$this->trads['canadianstate_sk'] = 'Saskatchewan';
$this->trads['canadianstate_nl'] = 'Terra Nova e Labrador';
$this->trads['canadianstate_nu'] = 'Nuvanut';
$this->trads['canadianstate_nt'] = 'Territ&oacute;rios do Noroeste';
$this->trads['canadianstate_yt'] = 'Yukon';
?>