<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <jb.lebrun@ideogram-design.fr>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Engine / Dictionnary
 * Creation Date    : Jul 2017
 * Last Modif Date  : Jul 2017
 *
 * Canadian states french dictionnary
*/

$this->trads['canadianstate_ab'] = 'Alberta';
$this->trads['canadianstate_bc'] = 'Colombie-Britannique';
$this->trads['canadianstate_ipe'] = '&Icirc;le-du-Prince-Edouard';
$this->trads['canadianstate_mb'] = 'Manitoba';
$this->trads['canadianstate_nb'] = 'Nouveau-Brunswick';
$this->trads['canadianstate_ns'] = 'Nouvelle-Ecosse';
$this->trads['canadianstate_on'] = 'Ontario';
$this->trads['canadianstate_qc'] = 'Qu&eacute;bec';
$this->trads['canadianstate_sk'] = 'Saskatchewan';
$this->trads['canadianstate_nl'] = 'Terre-Neuve-et-Labrador';
$this->trads['canadianstate_nu'] = 'Nuvanut';
$this->trads['canadianstate_nt'] = 'Territoires du Nord-Ouest';
$this->trads['canadianstate_yt'] = 'Yukon';