<?php
/**
 * @brief Canadian states spanish dictionnary
 * @details Engine / Dictionnary
 * @file engine/locale/canadianstates/translation_es.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jul 2017
 * @date Modification: Apr 2018
 * @copyright 2017 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

$this->trads['canadianstate_ab'] = 'Alberta';
$this->trads['canadianstate_bc'] = 'Columbia Brit&aacute;nica';
$this->trads['canadianstate_ipe'] = 'Isla del Pr&iacute;ncipe Eduardo';
$this->trads['canadianstate_mb'] = 'Manitoba';
$this->trads['canadianstate_nb'] = 'Nuevo Brunswick';
$this->trads['canadianstate_ns'] = 'Nueva Escocia';
$this->trads['canadianstate_on'] = 'Ontario';
$this->trads['canadianstate_qc'] = 'Quebec';
$this->trads['canadianstate_sk'] = 'Saskatchewan';
$this->trads['canadianstate_nl'] = 'Terranova y Labrador';
$this->trads['canadianstate_nu'] = 'Nuvanut';
$this->trads['canadianstate_nt'] = 'Territorios del Noroeste';
$this->trads['canadianstate_yt'] = 'Yuk&oacute;n';
?>