<?php
/**
 * @brief Admin_MyMessages Module french dictionnary
 * @details Plugin / Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jun 2007
 * @date Modification: Jan 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_admin_mymessages_title'] = 'Mes messages';
$this->trads['mod_admin_mymessages_desc'] = '';
$this->trads['mod_admin_mymessages_desc_'] = 'Vous avez %s nouveau(x) message(s).';

/* admin messages */
$this->trads['mod_admin_mymessages_back'] = 'Retour';
$this->trads['mod_admin_mymessages_pmsent'] = 'Message priv&eacute; envoy&eacute;.';
$this->trads['mod_admin_mymessages_touser_doesnt_exists'] = 'Le destinataire n\'existe pas. V&eacute;rifier l\'&eacute;criture exacte de son pseudo ( attention aux majuscules ).';
$this->trads['mod_admin_mymessages_touser_receivedboxfull'] = 'La boite de r&eacute;ception du destinataire est pleine. Il devra la vider un peu avant de pouvoir recevoir de nouveaux messages.';
$this->trads['mod_admin_mymessages_tobox_messages_updated'] = 'Les messages s&eacute;lectionn&eacute;s de votre "Boite de r&eacute;ception" ont &eacute;t&eacute; mis &agrave; jour.';
$this->trads['mod_admin_mymessages_frombox_messages_updated'] = 'Les messages s&eacute;lectionn&eacute;s parmi vos "Messages envoy&eacute;s" ont &eacute;t&eacute; mis &agrave; jour.';

/* admin tabs */
$this->trads['mod_admin_mymessages_tabreceivedbox'] = 'Boite de r&eacute;ception';
$this->trads['mod_admin_mymessages_tabsentbox'] = 'Messages envoy&eacute;s';
$this->trads['mod_admin_mymessages_tabwritemessage'] = 'Ecrire un message';

/* admin write form */
$this->trads['mod_admin_mymessages_receiptuser'] = 'Indiquez le destinataire';
$this->trads['mod_admin_mymessages_favoriteuser'] = 'parmi vos favoris';
$this->trads['mod_admin_mymessages_userlogin'] = 'ou par son pseudo';
$this->trads['mod_admin_mymessages_pm_title'] = 'Titre';
$this->trads['mod_admin_mymessages_pm_content'] = 'Message';
$this->trads['mod_admin_mymessages_send'] = 'Envoyer';
$this->trads['mod_admin_mymessages_sentboxisfull'] = 'Vous ne pouvez plus envoyer de message';
$this->trads['mod_admin_mymessages_sentboxisfull2'] = 'Vous avez atteint le quota maximum de "Messages envoy&eacute;s" sauvegard&eacute;s. Pour envoyer de nouveau un message, supprimez vos vieux messages dans "Messages envoy&eacute;s".';
$this->trads['mod_admin_mymessages_saveinsentbox'] = 'Enregistrer dans le message dans vos "Messages envoy&eacute;s"?';

/* box */
$this->trads['mod_admin_mymessages_delete'] = 'Effacer';
$this->trads['mod_admin_mymessages_setasread'] = 'Marqu&eacute;s comme lus';
$this->trads['mod_admin_mymessages_setasunread'] = 'Marqu&eacute;s comme non lus';
$this->trads['mod_admin_mymessages_selectedmessages'] = ' les messages s&eacute;lectionn&eacute;s';
$this->trads['mod_admin_mymessages_xmessagesofy'] = '%s messages sur %s';
$this->trads['mod_admin_mymessages_xmessageofy'] = '%s message sur %s';
$this->trads['mod_admin_mymessages_from'] = 'Exp&eacute;diteur';
$this->trads['mod_admin_mymessages_to'] = 'Destinataire';
$this->trads['mod_admin_mymessages_date'] = 'Date d\'envoi';
$this->trads['mod_admin_mymessages_ok'] = 'OK';

/* read message */
$this->trads['mod_admin_mymessages_readto'] = 'Message pour %s, &eacute;crit le %s.';
$this->trads['mod_admin_mymessages_readfrom'] = 'Message de %s, &eacute;crit le %s.';
$this->trads['mod_admin_mymessages_answer'] = 'R&eacute;pondre';
?>
