<?php
/*
 * CaMykS Engine
 * Developed by	       	: camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CamykS Version   	: 1.0a
 * Object Version       : 1.0
 * Object Type          : Plugin / Module Dictionnary
 * Create Date		: Jun 2007
 * Last Modif Date	: Jun 2007
 *
 * Admin_MyMessages english dictionnary
 */
$this->trads['mod_admin_mymessages_title'] = 'Private messages';
$this->trads['mod_admin_mymessages_desc'] = '';
$this->trads['mod_admin_mymessages_desc_'] = 'You have %s new messages(s).';

/* admin messages */
$this->trads['mod_admin_mymessages_back'] = 'Back';
$this->trads['mod_admin_mymessages_pmsent'] = 'Private message sent.';
$this->trads['mod_admin_mymessages_touser_doesnt_exists'] = 'Recipient doesn\'t exists. Check recipient value, including uppercase characters.';
$this->trads['mod_admin_mymessages_touser_receivedboxfull'] = 'Recipient in-box is full. Your message cannot be post.';
$this->trads['mod_admin_mymessages_tobox_messages_updated'] = 'Selected in-box messages are updated.';
$this->trads['mod_admin_mymessages_frombox_messages_updated'] = 'Selected send-box messages are updated.';

/* admin tabs */
$this->trads['mod_admin_mymessages_tabreceivedbox'] = 'In-box';
$this->trads['mod_admin_mymessages_tabsentbox'] = 'Send-box';
$this->trads['mod_admin_mymessages_tabwritemessage'] = 'Send a message';

/* admin write form */
$this->trads['mod_admin_mymessages_receiptuser'] = 'Recipient user';
$this->trads['mod_admin_mymessages_favoriteuser'] = 'from your favorites';
$this->trads['mod_admin_mymessages_userlogin'] = 'by its login';
$this->trads['mod_admin_mymessages_pm_title'] = 'Titte';
$this->trads['mod_admin_mymessages_pm_content'] = 'Message';
$this->trads['mod_admin_mymessages_send'] = 'Send';
$this->trads['mod_admin_mymessages_sentboxisfull'] = 'You cannot send this message.';
$this->trads['mod_admin_mymessages_sentboxisfull2'] = 'Your send-box is full. Delete old messages before sending some other messages.';
$this->trads['mod_admin_mymessages_saveinsentbox'] = 'Save this message into your send-box?';

/* box */
$this->trads['mod_admin_mymessages_delete'] = 'Delete';
$this->trads['mod_admin_mymessages_setasread'] = 'Mark as read';
$this->trads['mod_admin_mymessages_setasunread'] = 'Mark as unread';
$this->trads['mod_admin_mymessages_selectedmessages'] = ' the selected messages';
$this->trads['mod_admin_mymessages_xmessagesofy'] = '%s messages on %s';
$this->trads['mod_admin_mymessages_xmessageofy'] = '%s message on %s';
$this->trads['mod_admin_mymessages_from'] = 'Sender';
$this->trads['mod_admin_mymessages_to'] = 'Recipient';
$this->trads['mod_admin_mymessages_date'] = 'Send date';
$this->trads['mod_admin_mymessages_ok'] = 'OK';

/* read message */
$this->trads['mod_admin_mymessages_readto'] = 'Message for %s, written on %s.';
$this->trads['mod_admin_mymessages_readfrom'] = 'Message de %s, written on %s.';
$this->trads['mod_admin_mymessages_answer'] = 'Answer';
?>