<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	    : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Layout
 * Creation Date    : Feb 2010
 * Last Modif Date  : Feb 2010
 * 
 * ContentAnchorMenu layout
*/
?>
<div id="<?=$this->params['name'];?>" class="<?=$this->params['menuClass'];?>" style="display:none;">
</div>