<?php
/**
 * @brief Content_GenericLegalMentions Module english dictionnary.
 * @details Plugin, Module Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Apr 2021
 * @date Modification: Apr 2021
 * @copyright 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericlegalmentions_title'] = 'Legal mentions';
$this->trads['mod_content_genericlegalmentions_desc'] = 'Displays legal mentions.';

/* owner type values */
$this->trads['mod_content_genericlegalmentions_ownertype_company'] = 'Company';
$this->trads['mod_content_genericlegalmentions_ownertype_association'] = 'Association';
$this->trads['mod_content_genericlegalmentions_ownertype_publicestablishment'] = 'Public establishment';
$this->trads['mod_content_genericlegalmentions_ownertype_individual'] = 'Individual';

/* owner displayed values */
$this->trads['mod_content_genericlegalmentions_ownertype_thecompany'] = 'the company';
$this->trads['mod_content_genericlegalmentions_ownertype_theassociation'] = 'the association';
$this->trads['mod_content_genericlegalmentions_ownertype_thepublicestablishment'] = 'the public establishment';

/* admin tabs */
$this->trads['mod_content_genericlegalmentions_tabowner'] = 'Owner';
$this->trads['mod_content_genericlegalmentions_tabcreator'] = 'Creator';
$this->trads['mod_content_genericlegalmentions_tabwebmasterdpo'] = 'Webmaster &amp; DPO';
$this->trads['mod_content_genericlegalmentions_tabhost'] = 'Hosting company';
$this->trads['mod_content_genericlegalmentions_tabadditionalcontent'] = 'Additional content';

/* admin - properties tab */
$this->trads['mod_content_genericlegalmentions_formitem_lastupdate'] = 'Last update: ';
$this->trads['mod_content_genericlegalmentions_formtitle_page'] = 'Page';
$this->trads['mod_content_genericlegalmentions_defineaslegalmentionsdefaultpage'] = 'Define as "Legal mentions" default page';

/* admin - owner tab */
$this->trads['mod_content_genericlegalmentions_formtitle_manager'] = 'Manager';
$this->trads['mod_content_genericlegalmentions_formtitle_contacts'] = 'Contacts';
$this->trads['mod_content_genericlegalmentions_formtitle_details'] = 'D&eacute;tails';
$this->trads['mod_content_genericlegalmentions_formitem_legalform'] = 'Legal form: ';
$this->trads['mod_content_genericlegalmentions_formitem_capital'] = 'Share capital: ';
$this->trads['mod_content_genericlegalmentions_formitem_vat'] = 'VAT #: ';
$this->trads['mod_content_genericlegalmentions_formitem_siret'] = 'SIRET: ';
$this->trads['mod_content_genericlegalmentions_formitem_registerednumber'] = 'Record #: ';
$this->trads['mod_content_genericlegalmentions_formitem_at'] = ' in ';
$this->trads['mod_content_genericlegalmentions_formitem_naf'] = 'NAF code: ';

$this->trads['mod_content_genericlegalmentions_formtitle_legal'] = 'L&eacute;gal';
$this->trads['mod_content_genericlegalmentions_formitem_tribunal'] = 'Court: ';

/* admin - webmaster / dpo tab */
$this->trads['mod_content_genericlegalmentions_formtitle_webmaster'] = 'Webmaster';
$this->trads['mod_content_genericlegalmentions_formtitle_dpo'] = 'Data Protection Officer';
?>
