<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <jb.lebrun@ideogram-design.fr>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Engine / Dictionnary
 * Creation Date    : Jul 2017
 * Last Modif Date  : Jul 2017
 *
 * USA states spainish dictionnary
*/

$this->trads['usastate_al'] = 'Alabama';
$this->trads['usastate_ak'] = 'Alaska';
$this->trads['usastate_az'] = 'Arizona';
$this->trads['usastate_ar'] = 'Arkansas';
$this->trads['usastate_ca'] = 'California';
$this->trads['usastate_nc'] = 'Carolina del Norte';
$this->trads['usastate_sc'] = 'Carolina del Sur';
$this->trads['usastate_co'] = 'Colorado';
$this->trads['usastate_ct'] = 'Connecticut';
$this->trads['usastate_nd'] = 'Dakota del Norte';
$this->trads['usastate_sd'] = 'Dakota del Sur';
$this->trads['usastate_de'] = 'Delaware';
$this->trads['usastate_fl'] = 'Florida';
$this->trads['usastate_ga'] = 'Georgia';
$this->trads['usastate_hi'] = 'Haw&aacute;i';
$this->trads['usastate_id'] = 'Idaho';
$this->trads['usastate_il'] = 'Illinois';
$this->trads['usastate_in'] = 'Indiana';
$this->trads['usastate_ia'] = 'Iowa';
$this->trads['usastate_ks'] = 'Kansas';
$this->trads['usastate_ky'] = 'Kentucky';
$this->trads['usastate_la'] = 'Luisiana';
$this->trads['usastate_me'] = 'Maine';
$this->trads['usastate_md'] = 'Maryland';
$this->trads['usastate_ma'] = 'Massachusetts';
$this->trads['usastate_mi'] = 'M&iacute;chigan';
$this->trads['usastate_mn'] = 'Minnesota';
$this->trads['usastate_ms'] = 'Misisipi';
$this->trads['usastate_mo'] = 'Misuri';
$this->trads['usastate_mt'] = 'Montana';
$this->trads['usastate_ne'] = 'Nebraska';
$this->trads['usastate_nv'] = 'Nevada';
$this->trads['usastate_nh'] = 'Nueva Hampshire';
$this->trads['usastate_nj'] = 'Nueva Jersey';
$this->trads['usastate_nm'] = 'Nueva M&eacute;xico';
$this->trads['usastate_ny'] = 'Nueva York';
$this->trads['usastate_oh'] = 'Ohio';
$this->trads['usastate_ok'] = 'Oklahoma';
$this->trads['usastate_or'] = 'Oreg&oacute;n';
$this->trads['usastate_pa'] = 'Pensilvania';
$this->trads['usastate_ri'] = 'Rhode Island';
$this->trads['usastate_tn'] = 'Tennessee';
$this->trads['usastate_tx'] = 'Texas';
$this->trads['usastate_ut'] = 'Utah';
$this->trads['usastate_vt'] = 'Vermont';
$this->trads['usastate_va'] = 'Virginia';
$this->trads['usastate_wv'] = 'Virginia Occidental';
$this->trads['usastate_wa'] = 'Washington';
$this->trads['usastate_wi'] = 'Wisconsin';
$this->trads['usastate_wy'] = 'Wyoming';