<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <jb.lebrun@ideogram-design.fr>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Engine / Dictionnary
 * Creation Date    : Jul 2017
 * Last Modif Date  : Jul 2017
 *
 * USA states portuguese dictionnary
*/

$this->trads['usastate_al'] = 'Alabama';
$this->trads['usastate_ak'] = 'Alasca';
$this->trads['usastate_az'] = 'Arizona';
$this->trads['usastate_ar'] = 'Arcansas';
$this->trads['usastate_ca'] = 'Calif&oacute;rnia';
$this->trads['usastate_nc'] = 'Carolina do Norte';
$this->trads['usastate_sc'] = 'Carolina do Sul';
$this->trads['usastate_co'] = 'Colorado';
$this->trads['usastate_ct'] = 'Conecticute';
$this->trads['usastate_nd'] = 'Dacota do Norte';
$this->trads['usastate_sd'] = 'Dacota do Sul';
$this->trads['usastate_de'] = 'Delaware';
$this->trads['usastate_fl'] = 'Fl&oacute;rida';
$this->trads['usastate_ga'] = 'Ge&oacute;rgia';
$this->trads['usastate_hi'] = 'Havai';
$this->trads['usastate_id'] = 'Idaho';
$this->trads['usastate_il'] = 'Illin&oacute;is';
$this->trads['usastate_in'] = 'Indiana';
$this->trads['usastate_ia'] = 'Iowa';
$this->trads['usastate_ks'] = 'Cansas';
$this->trads['usastate_ky'] = 'Kentucky';
$this->trads['usastate_la'] = 'Luisiana';
$this->trads['usastate_me'] = 'Maine';
$this->trads['usastate_md'] = 'Maril&acirc;ndia';
$this->trads['usastate_ma'] = 'Massachusetts';
$this->trads['usastate_mi'] = 'M&iacute;chigan';
$this->trads['usastate_mn'] = 'Minesota';
$this->trads['usastate_ms'] = 'Mississ&iacute;pi';
$this->trads['usastate_mo'] = 'Miss&uacute;ri';
$this->trads['usastate_mt'] = 'Montana';
$this->trads['usastate_ne'] = 'Nebrasca';
$this->trads['usastate_nv'] = 'Nevada';
$this->trads['usastate_nh'] = 'Nova Hampshire';
$this->trads['usastate_nj'] = 'Nova J&eacute;rsei';
$this->trads['usastate_nm'] = 'Nova M&eacute;xico';
$this->trads['usastate_ny'] = 'Nova lorque';
$this->trads['usastate_oh'] = 'Ohio';
$this->trads['usastate_ok'] = 'Oclaoma';
$this->trads['usastate_or'] = '&Oacute;regon';
$this->trads['usastate_pa'] = 'Pensilv&acirc;nia';
$this->trads['usastate_ri'] = 'Ilha de Rodes';
$this->trads['usastate_tn'] = 'Tenessi';
$this->trads['usastate_tx'] = 'Texas';
$this->trads['usastate_ut'] = 'Ut&aacute;';
$this->trads['usastate_vt'] = 'Vermonte';
$this->trads['usastate_va'] = 'Virg&iacute;nia';
$this->trads['usastate_wv'] = 'Virg&iacute;nia Occidentale';
$this->trads['usastate_wa'] = 'Washington';
$this->trads['usastate_wi'] = 'Wisconsin';
$this->trads['usastate_wy'] = 'Wyoming';