<?php
/*
 * CaMykS Engine
 * Developed by     : camyks.net
 * Author           : CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0b
 * Object Version   : 1.0
 * Object Type      : Plugin / Module Dictionnary
 * Creation Date    : Apr 2011
 * Last Modif Date  : Apr 2011
 *
 * MultiSelectionList french dictionnary
*/
$this->trads['input_multiselectionlist_listtitle'] = 'El&eacute;ments';
$this->trads['input_multiselectionlist_selectiontitle'] = 'S&eacute;lectionn&eacute;s';
?>
