<?php
/**
 * @brief MultiSelectionList Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/MultiSelectionList/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Apr 2011
 * @date Modification: Apr 2018
 * @copyright 2011 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['input_multiselectionlist_listtitle'] = 'El&eacute;ments';
$this->trads['input_multiselectionlist_selectiontitle'] = 'S&eacute;lectionn&eacute;s';
?>
