<?php
/**
 * @brief Content_GenericBlogsViewer module, french dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Apr 2008
 * @date Modification: Jul 2021
 * @copyright 2008 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericblogsviewer_title'] = 'Affichage des blogs';
$this->trads['mod_content_genericblogsviewer_desc'] = '';

/* layout list */
$this->trads['mod_content_genericblogsviewer_layout_item_box'] = 'Encadr&eacute;';
$this->trads['mod_content_genericblogsviewer_layout_list_box'] = 'Encadr&eacute;';

/* generic status list */
$this->trads['mod_content_genericblogsviewer_status_enabled'] = 'Activ&eacute;';
$this->trads['mod_content_genericblogsviewer_status_disabled'] = 'D&eacute;sactiv&eacute;';

/* tool */
$this->trads['mod_content_genericblogsviewer_gpc_name'] = 'Contr&ocirc;leur';

/* admin mode */
$this->trads['mod_content_genericblogsviewer_title_globalsettings'] = 'Param&egrave;tres globaux';
$this->trads['mod_content_genericblogsviewer_title_listsettings'] = 'Param&egrave;tres de l\'affichage list&eacute;';
$this->trads['mod_content_genericblogsviewer_title_itemsettings'] = 'Param&egrave;tres de l\'affichage d\'une actualit&eacute;';
$this->trads['mod_content_genericblogsviewer_title_panelsettings'] = 'Param&egrave;tres du panneau d\'informations';
$this->trads['mod_content_genericblogsviewer_title_commentsettings'] = 'Param&egrave;tres des commentaires';
$this->trads['mod_content_genericblogsviewer_formtitle_socialnetworksharingpanel'] = 'Partage sur les r&eacute;seaux sociaux';
$this->trads['mod_content_genericblogsviewer_formtitle_genericpagecontroller'] = 'Contr&ocirc;leur de page g&eacute;n&eacute;rique';
$this->trads['mod_content_genericblogsviewer_formitem_gpcsource'] = 'Design sp&eacute;cifi&eacute; par : ';

$this->trads['mod_content_genericblogsviewer_itemauthors'] = 'Auteurs affich&eacute;s : ';
$this->trads['mod_content_genericblogsviewer_itemactiverss'] = 'Activer le flux RSS : ';
$this->trads['mod_content_genericblogsviewer_itemlistcount'] = 'Nombre d\'actualit&eacute;s affich&eacute;es : ';
$this->trads['mod_content_genericblogsviewer_itemlistlayout'] = 'Affichage : ';
$this->trads['mod_content_genericblogsviewer_itemlistpanel'] = 'Afficher le panneau d\'informations : ';
$this->trads['mod_content_genericblogsviewer_itemitemlayout'] = 'Affichage : ';
$this->trads['mod_content_genericblogsviewer_itemitempanel'] = 'Afficher le panneau d\'informations : ';
$this->trads['mod_content_genericblogsviewer_itempanelinsert'] = 'Insertion de texte :';
$this->trads['mod_content_genericblogsviewer_itemcommentmessage'] = 'Message en-t&ecirc;te : ';

$this->trads['mod_content_genericblogsviewer_authors_all'] = 'Tous';

$this->trads['mod_content_genericblogsviewer_savedone'] = 'Enregistrement en cours...';
$this->trads['mod_content_genericblogsviewer_savefailed'] = 'Une erreur est survenue lors de l\'enregistrement des donn&eacute;es.';

/* site mode */
$this->trads['mod_content_genericblogsviewer_site_title_separator'] = ' : ';
$this->trads['mod_content_genericblogsviewer_site_back'] = 'Retour au blog';

$this->trads['mod_content_genericblogsviewer_site_comments_title'] = 'Les %s commentaires : ';
$this->trads['mod_content_genericblogsviewer_site_comment_title'] = 'Le commentaire : ';
$this->trads['mod_content_genericblogsviewer_site_nocomment_title'] = 'Aucun commentaire pour le moment';

$this->trads['mod_content_genericblogsviewer_site_comment_headerfull'] = 'Message post&eacute; par <a href="%3$s" target="_blank" class="%4$s">%1$s</a>, le %2$s : ';
$this->trads['mod_content_genericblogsviewer_site_comment_headerlight'] = 'Message post&eacute; par %1$s, le %2$s : ';

$this->trads['mod_content_genericblogsviewer_site_comment_add'] = 'Ajouter votre commentaire : ';
$this->trads['mod_content_genericblogsviewer_site_comment_mandatory'] = ' (obligatoire)';
$this->trads['mod_content_genericblogsviewer_site_comment_yourname'] = 'Votre nom : ';
$this->trads['mod_content_genericblogsviewer_site_comment_youremail'] = 'Votre e-mail : ';
$this->trads['mod_content_genericblogsviewer_site_comment_yourwebsite'] = 'Site Web : ';
$this->trads['mod_content_genericblogsviewer_site_comment_yourcommtitle'] = 'Titre : ';

$this->trads['mod_content_genericblogsviewer_site_comment_send'] = 'Envoyer mon commentaire';

$this->trads['mod_content_genericblogsviewer_site_comment_saved'] = 'Votre commentaire a &eacute;t&eacute; enregistr&eacute;.';
$this->trads['mod_content_genericblogsviewer_site_comment_savedneedvalidation'] = 'Un administrateur validera votre message, il apparaitra alors sur le site.';

$this->trads['mod_content_genericblogsviewer_site_nocomment'] = 'Soyez le premier &agrave; ajouter un commentaire!';
$this->trads['mod_content_genericblogsviewer_site_1comment'] = 'Lire le commentaire.';
$this->trads['mod_content_genericblogsviewer_site_xcomments'] = 'Lire les %s commentaires.';

$this->trads['mod_content_genericblogsviewer_published_by_into'] = 'Publi&eacute; par %s dans %s.';
$this->trads['mod_content_genericblogsviewer_published_by'] = 'Publi&eacute; par %s';
$this->trads['mod_content_genericblogsviewer_published_into'] = 'Publi&eacute; into %s';


$this->trads['mod_content_genericblogsviewer_site_currentpage'] = 'Page %s';
$this->trads['mod_content_genericblogsviewer_site_nextpage'] = 'R&eacute;centes &gt;&gt;';
$this->trads['mod_content_genericblogsviewer_site_previouspage'] = '&lt;&lt; Archives';

$this->trads['mod_content_genericblogsviewer_site_shareon'] = 'Partager sur :&nbsp;';

/* site mode : panel */
$this->trads['mod_content_genericblogsviewer_panel_authors'] = 'Par auteurs : ';
$this->trads['mod_content_genericblogsviewer_panel_tags'] = 'Par tags : ';
$this->trads['mod_content_genericblogsviewer_panel_links'] = 'Les liens : ';

/* rss */
$this->trads['mod_content_genericblogsviewer_rss_title0'] = 'Blog de %1$s';
$this->trads['mod_content_genericblogsviewer_rss_title1'] = 'Blog de %2$s sur %1$s';
$this->trads['mod_content_genericblogsviewer_rss_titlex'] = 'Blog de %1$s';
$this->trads['mod_content_genericblogsviewer_rss_description'] = '%s en RSS';
?>
