<?php
/**
 * @brief PayBoxPayment Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/PayBoxPayment/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jul 2018
 * @date Modification: Jan 2020
 * @copyright 2018 - 2020 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* mode values */
$this->trads['input_payboxpayment_mode_test'] = 'Test';
$this->trads['input_payboxpayment_mode_live'] = 'Live';

/* configurtion */
$this->trads['input_payboxpayment_formtitle_operation'] = 'Operation';
$this->trads['input_payboxpayment_formitem_mode'] = 'Mode: ';

$this->trads['input_payboxpayment_formtitle_bankkeys'] = 'Bank keys';
$this->trads['input_payboxpayment_formitem_test'] = 'Test: ';
$this->trads['input_payboxpayment_formitem_live'] = 'Live: ';

$this->trads['input_payboxpayment_formtitle_bankconfiguration'] = 'Bank configuration';
$this->trads['input_payboxpayment_formitem_site'] = 'Site: ';
$this->trads['input_payboxpayment_formitem_rang'] = 'Rank: ';
$this->trads['input_payboxpayment_formitem_identifiant'] = 'Login: ';

/* site */
$this->trads['input_payzenpayment_redirectobankmessage'] = 'You will be redirected to the banking service.';
$this->trads['input_payzenpayment_redirectobankmessage2'] = 'If not, <a href="%s" class="%s">click here</a>.';
?>
