<?php
/**
 * @brief PayBoxPayment Input french dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/PayBoxPayment/locale/translation_fr.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: Jul 2018
 * @date Modification: Jul 2018
 * @copyright 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* mode values */
$this->trads['input_payboxpayment_mode_test'] = 'Test';
$this->trads['input_payboxpayment_mode_live'] = 'Live';

/* configurtion */
$this->trads['input_payboxpayment_formtitle_operation'] = 'Fonctionnement';
$this->trads['input_payboxpayment_formitem_mode'] = 'Mode : ';
 
$this->trads['input_payboxpayment_formtitle_bankkeys'] = 'Cl&eacute;s bancaires';
$this->trads['input_payboxpayment_formitem_test'] = 'Test : ';
$this->trads['input_payboxpayment_formitem_live'] = 'Live : ';
 
$this->trads['input_payboxpayment_formtitle_bankconfiguration'] = 'Configuration bancaire';
$this->trads['input_payboxpayment_formitem_site'] = 'Site : ';
$this->trads['input_payboxpayment_formitem_rang'] = 'Rang : ';
$this->trads['input_payboxpayment_formitem_identifiant'] = 'Identifiant : ';
?>