<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   	: 1.0a
 * Object Version	: 1.0
 * Object Type          : Plugin / Module Help File
 * Creation Date	: May 2008
 * Last Modif Date	: May 2008
 *
 * Admin_MyAccount module help
*/
?>
<p class="content1">
  Permet de g&eacute;rer votre compte administrateur.
</p>
<p class="content1">
  Vous devez avoir les autorisations pour modifier votre compte.<br/>
  Si ce n'est pas le cas, contactez votre webmaster pour effectuer les modifications.
</p>
<p class="content1">
  L'identifiant n'est pas modifiable. L'email est obligatoire.
</p>