<?php
/**
 * @brief Content_GenericQuickMessage Module french dictionary.
 * @details Plugin, Module dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Nov 2007
 * @date Modification: Jul 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericquickmessage_title'] = 'Messages Rapides';
$this->trads['mod_content_genericquickmessage_desc'] = 'Affiche des messages laiss&eacute;s par les utilisateurs du site';

/* global */
$this->trads['mod_content_genericquickmessage_liststatusvalue0'] = 'Ferm&eacute;';
$this->trads['mod_content_genericquickmessage_liststatusvalue1'] = 'Utilisateurs enregistr&eacute;s uniquement';
$this->trads['mod_content_genericquickmessage_liststatusvalue2'] = 'Tout les utilisateurs autoris&eacute;s';

$this->trads['mod_content_genericquickmessage_listvalidationvalue0'] = 'Aucune';
$this->trads['mod_content_genericquickmessage_listvalidationvalue1'] = 'Administrative';

$this->trads['mod_content_genericquickmessage_itemstatusvalue0'] = 'Rejet&eacute;';
$this->trads['mod_content_genericquickmessage_itemstatusvalue1'] = 'En attente';
$this->trads['mod_content_genericquickmessage_itemstatusvalue2'] = 'Valid&eacute;';
/* admin */
$this->trads['mod_content_genericquickmessage_tabgeneral'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericquickmessage_tabmessages'] = 'Messages';

/* list object tab */
$this->trads['mod_content_genericquickmessage_state'] = 'Etat';
$this->trads['mod_content_genericquickmessage_listvalidation'] = 'Validation';
$this->trads['mod_content_genericquickmessage_listnotification'] = 'Notification de nouveaux messages ( en cas de validation administrative )';
$this->trads['mod_content_genericquickmessage_displayedmessages'] = 'Message affich&eacute;s';

/* item list tab */
$this->trads['mod_content_genericquickmessage_display'] = 'Afficher';
$this->trads['mod_content_genericquickmessage_from'] = 'les';
$this->trads['mod_content_genericquickmessage_fromend'] = 'derniers messages';
$this->trads['mod_content_genericquickmessage_fromstatus'] = ' dont le status est ';
$this->trads['mod_content_genericquickmessage_x'] = ' %s ';
$this->trads['mod_content_genericquickmessage_xtoy'] = ' %s &agrave; %s ';
$this->trads['mod_content_genericquickmessage_all'] = 'Tous ';

$this->trads['mod_content_genericquickmessage_number'] = '#';
$this->trads['mod_content_genericquickmessage_date'] = 'Date';
$this->trads['mod_content_genericquickmessage_messageauthor'] = 'Auteur';

/* item edit tab */
$this->trads['mod_content_genericquickmessage_itemid'] = 'Message n&deg;%s';
$this->trads['mod_content_genericquickmessage_messageemail'] = 'Email';

/* site */
$this->trads['mod_content_genericquickmessage_site_title'] = 'Messages';
$this->trads['mod_content_genericquickmessage_yourname'] = 'Votre nom';
$this->trads['mod_content_genericquickmessage_yourmail'] = 'Votre email';
$this->trads['mod_content_genericquickmessage_messagetitle'] = 'Titre';
$this->trads['mod_content_genericquickmessage_messagecontent'] = 'Message';
$this->trads['mod_content_genericquickmessage_addmessage'] = 'Envoyer';
$this->trads['mod_content_genericquickmessage_message_saved'] = 'Votre message a &eacute;t&eacute; enregistr&eacute;.';
$this->trads['mod_content_genericquickmessage_message_savedadmin'] = 'Votre message a &eacute;t&eacute; enregistr&eacute;.<br/> Il ne sera affich&eacute; apr&egrave;s validation par un administrateur du site.';
$this->trads['mod_content_genericquickmessage_message_notsaved'] = 'Votre message n\'a pas &eacute;t&eacute; enregistr&eacute;.';
$this->trads['mod_content_genericquickmessage_message_closed'] = 'L\'ajout de nouveau message est actuellement d&eacute;sactiv&eacute;.';
$this->trads['mod_content_genericquickmessage_message_registered'] = 'Vous devez &ecirc;tre enregistr&eacute; et connect&eacute; pour poster un message.';
$this->trads['mod_content_genericquickmessage_byauthor'] = 'Par %s';
$this->trads['mod_content_genericquickmessage_ondate'] = 'Le %s';
$this->trads['mod_content_genericquickmessage_postamessage'] = '&gt; Poster un message';
$this->trads['mod_content_genericquickmessage_back'] = '&gt; Retour aux messages';
?>
