<?php
/**
 * @brief Content_GenericFaq module, french dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1.1
 * @date Creation: Apr 2007
 * @date Modification: May 2021
 * @copyright 2007 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_genericfaq_title'] = 'Foire aux questions';
$this->trads['mod_content_genericfaq_desc'] = 'Affiche des FaQs';

/* message  */
$this->trads['mod_content_genericfaq_listsaved'] = 'Les propri&eacute;t&eacute;s de la liste de FAQ ont &eacute;t&eacute; sauvegard&eacute;es.';
$this->trads['mod_content_genericfaq_itemsaved'] = 'La FAQ a &eacute;t&eacute; sauvegard&eacute;.';
$this->trads['mod_content_genericfaq_listnotsaved'] = 'Les propri&eacute;t&eacute;s de la liste de FAQ n\'ont pas &eacute;t&eacute; sauvegard&eacute;es.';
$this->trads['mod_content_genericfaq_itemnotsaved'] = 'La FAQ n\'a pas &eacute;t&eacute; sauvegard&eacute;.';

/* admin : edit list / tabs */
$this->trads['mod_content_genericfaq_tabproperties'] = 'Propri&eacute;t&eacute;s';
$this->trads['mod_content_genericfaq_tabitems'] = 'Contenu';

/* admin : edit list / list form */
$this->trads['mod_content_genericfaq_name'] = 'Nom';
$this->trads['mod_content_genericfaq_count_list'] = 'Nombre de questions affich&eacute;es';
$this->trads['mod_content_genericfaq_layout_list'] = 'Layout pour la liste';
$this->trads['mod_content_genericfaq_box_list'] = 'Cadre - Liste simple';
$this->trads['mod_content_genericfaq_box_listindex'] = 'Cadre - Liste index&eacute;e';
$this->trads['mod_content_genericfaq_box_listprefix'] = 'Cadre - Liste pr&eacute;fix&eacute;e';
$this->trads['mod_content_genericfaq_title_mode'] = 'Ins&eacute;rez un titre';
$this->trads['mod_content_genericfaq_title_none'] = 'Aucun';
$this->trads['mod_content_genericfaq_title_text'] = 'Format texte';
$this->trads['mod_content_genericfaq_title_image'] = 'Format image';
$this->trads['mod_content_genericfaq_title_localizedtext'] = 'Format texte localis&eacute;';
$this->trads['mod_content_genericfaq_title_localizedimage'] = 'Format image localis&eacute;e';
$this->trads['mod_content_genericfaq_title_title'] = 'Titre';

/* admin : edit list / list faq */
$this->trads['mod_content_genericfaq_newitem'] = '+ Cr&eacute;er une nouvelle question';
$this->trads['mod_content_genericfaq_status'] = 'Etat';
$this->trads['mod_content_genericfaq_faqtitle'] = 'Question';
$this->trads['mod_content_genericfaq_language'] = 'Langue';
$this->trads['mod_content_genericfaq_previous'] = '&lt;&lt; Plus r&eacute;centes';
$this->trads['mod_content_genericfaq_next'] = 'Plus anciennes &gt;&gt;';
$this->trads['mod_content_genericfaq_faqscount'] = '%s questions';
$this->trads['mod_content_genericfaq_js_delete'] = 'Etes vous sur de vouloir supprimer cette question?';

/* admin : edit item / list form */
$this->trads['mod_content_genericfaq_editanitem'] = 'Editer une question';
$this->trads['mod_content_genericfaq_content'] = 'R&eacute;ponse';
$this->trads['mod_content_genericfaq_inedition'] = 'En cours d\'&eacute;dition';
$this->trads['mod_content_genericfaq_inline'] = 'En ligne';
$this->trads['mod_content_genericfaq_edit'] = 'Modifier';

/* site : display */
$this->trads['mod_content_genericfaq_site_title'] = 'Foire aux questions';
$this->trads['mod_content_genericfaq_previousfaqs'] = 'Questions pr&eacute;c&eacute;dentes';
$this->trads['mod_content_genericfaq_nextfaqs'] = 'Questions suivantes';
$this->trads['mod_content_genericfaq_page'] = 'Page %s';
$this->trads['mod_content_genericfaq_question'] = 'Question %s : ';
?>
