<?php
/**
 * @brief AdvancedSMTPSettings Input, french dictionary.
 * @details Plugin / Input Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Jan 2026
 * @date Modification: Jan 2026
 * @copyright 2026 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* Configuration */
$this->trads['input_advancedsmtpsettings_formtitle_pluginparams'] = 'Param&egrave;tres du plugin';
$this->trads['input_advancedsmtpsettings_formitem_execution'] = 'Insertion : ';
$this->trads['input_advancedsmtpsettings_formitem_emaillibrary'] = 'Librairie e-mail : ';

$this->trads['input_advancedsmtpsettings_formtitle_smtpparams'] = 'Param&egrave;tres SMTP';
$this->trads['input_advancedsmtpsettings_formitem_host'] = 'H&ocirc;te : ';
$this->trads['input_advancedsmtpsettings_formitem_port'] = 'Port : ';
$this->trads['input_advancedsmtpsettings_formitem_secure'] = 'S&eacute;curit&eacute; : ';
$this->trads['input_advancedsmtpsettings_formitem_authentication'] = 'Authentification : ';

$this->trads['input_advancedsmtpsettings_formtitle_basicauthenticationparams'] = 'Param&egrave;tres d\'authentification basique';
$this->trads['input_advancedsmtpsettings_formitem_username'] = 'Nom d\'utilisateur : ';
$this->trads['input_advancedsmtpsettings_formitem_password'] = 'Mot de passe : ';

$this->trads['input_advancedsmtpsettings_formtitle_xoauth2authenticationparams'] = 'Param&egrave;tres d\'authentification XOAUTH2';
$this->trads['input_advancedsmtpsettings_formitem_provider'] = 'Fournisseur : ';
$this->trads['input_advancedsmtpsettings_formitem_email'] = 'Email : ';
$this->trads['input_advancedsmtpsettings_formitem_clientid'] = 'ID Client : ';
$this->trads['input_advancedsmtpsettings_formitem_tenantid'] = 'ID Tenant : ';
$this->trads['input_advancedsmtpsettings_formitem_clientsecret'] = 'Secret client : ';
$this->trads['input_advancedsmtpsettings_formitem_refreshtoken'] = 'Jeton : ';
$this->trads['input_advancedsmtpsettings_formitem_refreshtokenexpiracydate'] = 'Date d\'expiration : ';

$this->trads['input_advancedsmtpsettings_getnewtoken'] = 'Obtenir un nouveau jeton';

/* Configuration - Plugin insertion values */
$this->trads['input_advancedsmtpsettings_plugininsertion_ondemand'] = 'A la demande';
$this->trads['input_advancedsmtpsettings_plugininsertion_onpageload'] = 'Automatique';

/* Configuration - Plugin email library values */
$this->trads['input_advancedsmtpsettings_pluginemaillibrary_auto'] = 'Auto';

/* Configuration - SMTP Secure values */
$this->trads['input_advancedsmtpsettings_smtpsecure_none'] = 'Aucune';

/* Configuration - SMTP Secure values */
$this->trads['input_advancedsmtpsettings_smtpauth_none'] = 'Aucune';
$this->trads['input_advancedsmtpsettings_smtpauth_basic'] = 'Basique';
$this->trads['input_advancedsmtpsettings_smtpauth_xoauth2'] = 'XOAUTH2';

/* Refresh token request errors */
$this->trads['input_advancedsmtpsettings_refreshtokenupdated'] = 'Jeton mis &agrave; jour.';
$this->trads['input_advancedsmtpsettings_error_invalidstate'] = '&Eacute;tat invalide.';
$this->trads['input_advancedsmtpsettings_error_providermissing'] = 'Aucun fournisseur indiqu&eacute;.';
$this->trads['input_advancedsmtpsettings_error_configsavefailed'] = 'Une erreur est survenue lors de la sauvegarde de la configuration.';
?>
