<?php
/**
 * @brief Tool_InfoBar Module no admin user logged layout
 * @details Plugin / Module Layout
 * @file plugin/module/Tool_InfoBar/html/adminnobody.html.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Oct 2005
 * @date Modification: May 2019
 * @copyright 2005 - 2019 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
?>
<?= $this->theme->get_barLeft('width:700px;'); ?>
    <div>
        &nbsp;
    </div>
<?= $this->theme->get_barRight(); ?>
