<?php
/*
 * CaMykS Engine
 * Developed by		: camyks.net
 * Author		: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version	: 1.0a
 * Object Version	: 1.0
 * Object Type	        : Plugin / Module Layout
 * Create Date	       	: Oct 2005
 * Last Modif Date	: Mar 2007
 *
 * Admin_InfoBar Module Admin Layout : main
 */
?>
<?=$this->theme->get_barLeft('width:700px;')?>
<div>
&nbsp;
</div>
<?=$this->theme->get_barRight()?>