<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Dictionnary
 * Create Date		: May 2017
 * Last Modif Date	: May 2017
 *
 * CookieAgreementMessage language dictionnary : English 
 */

$this->trads['input_cookieagreementmessage_defaultmessage'] = 'Cookies ensure the well functionning of our services. By continuing, you accept their use on our website.';
$this->trads['input_cookieagreementmessage_about'] = 'Read more';
$this->trads['input_cookieagreementmessage_accept'] = 'Accept';

$this->trads['input_cookieagreementmessage_aboutcookieurl'] = 'https://en.wikipedia.org/wiki/HTTP_cookie';
?>
