<?php
/**
 * @brief CookieAgreementMessage Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.1.0.1
 * @date Creation: May 2017
 * @date Modification: Mar 2021
 * @copyright 2017 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* insertion values */
$this->trads['input_cookieagreementmessage_insertion_manual'] = 'Manually';
$this->trads['input_cookieagreementmessage_insertion_automatic'] = 'Automatic';

/* style source values */
$this->trads['input_cookieagreementmessage_stylesource_plugin'] = 'Plugin';
$this->trads['input_cookieagreementmessage_stylesource_theme'] = 'Theme';

/* location values */
$this->trads['input_cookieagreementmessage_location_top'] = 'Top';
$this->trads['input_cookieagreementmessage_location_topleft'] = 'Top / Left';
$this->trads['input_cookieagreementmessage_location_topright'] = 'Top / Right';
$this->trads['input_cookieagreementmessage_location_bottom'] = 'Bottom';
$this->trads['input_cookieagreementmessage_location_bottomleft'] = 'Bottom / Left';
$this->trads['input_cookieagreementmessage_location_bottomright'] = 'Bottom / Right';
$this->trads['input_cookieagreementmessage_location_centered'] = 'Centered';

/* edit / view config */
$this->trads['input_cookieagreementmessage_formitem_insertion'] = 'Insertion: ';
$this->trads['input_cookieagreementmessage_formitem_stylesource'] = 'Styles source: ';
$this->trads['input_cookieagreementmessage_formitem_aboutcookielink'] = 'About link: ';
$this->trads['input_cookieagreementmessage_formitem_remindttl'] = 'Cookie time-to-live: ';
$this->trads['input_cookieagreementmessage_formdesc_remindttl'] = 'day(s)';
$this->trads['input_cookieagreementmessage_formitem_popuplocation'] = 'Popup location: ';
$this->trads['input_cookieagreementmessage_formitem_message'] = 'Message: ';

$this->trads['input_cookieagreementmessage_config_nolink'] = 'None';
$this->trads['input_cookieagreementmessage_config_automaticlink'] = 'Automatic';
$this->trads['input_cookieagreementmessage_config_customlink'] = 'Personnalised';

$this->trads['input_cookieagreementmessage_config_automaticmessage'] = 'Automatic';

/* popup message contents */
$this->trads['input_cookieagreementmessage_defaultmessage'] = 'This site uses cookies to ensure its proper functioning. It also uses cookies from third party services to provide advanced functionality. At any time, you can choose which services you wish to activate or decide to withdraw your consent.';
$this->trads['input_cookieagreementmessage_minimise_panel'] = 'Close panel';
$this->trads['input_cookieagreementmessage_open_panel'] = 'Open cookie management panel';
$this->trads['input_cookieagreementmessage_manage_cookies'] = 'Customise accepted services';
$this->trads['input_cookieagreementmessage_manage_cookies_desc'] = 'You are free to choose which services you wish to enable. By authorising these third party services, you agree to the deposit and reading of cookies and the use of tracking technologies necessary for their proper functioning. By withdrawing your consent for some of these services, some website features may no longer function.';
$this->trads['input_cookieagreementmessage_about'] = 'Read more';
$this->trads['input_cookieagreementmessage_acceptall'] = 'Accept all';
$this->trads['input_cookieagreementmessage_refuseall'] = 'Refuse all';
$this->trads['input_cookieagreementmessage_personalise'] = 'Manage';
$this->trads['input_cookieagreementmessage_refresh_page'] = 'Reload page';
$this->trads['input_cookieagreementmessage_accept'] = 'Accept';
$this->trads['input_cookieagreementmessage_refuse'] = 'Refuse';
$this->trads['input_cookieagreementmessage_ismandatory'] = 'Mandatory';
$this->trads['input_cookieagreementmessage_formitem_usage'] = 'Usage: ';
$this->trads['input_cookieagreementmessage_formitem_duration'] = 'Time to live: ';

/* Navigation cookie data */
$this->trads['input_cookieagreementmessage_navigationcookie_title'] = 'Website navigation';
$this->trads['input_cookieagreementmessage_navigationcookie_purpose'] = 'The site writes a session cookie to enable it to function properly and to help with navigation. It cannot be deactivated.';
$this->trads['input_cookieagreementmessage_navigationcookie_usage'] = '1 cookie, records the session identifier.';
$this->trads['input_cookieagreementmessage_navigationcookie_duration'] = 'The cookie is present during the entire session on the site. It becomes obsolete after %s minutes of inactivity. ';

/* Unavailable service message */
$this->trads['input_cookieagreementmessage_message_unavailable_title'] = 'Unavailable feature';
$this->trads['input_cookieagreementmessage_message_unavailable_content'] = 'To be able to use this feature, you should enable the __SERVICE__ service in the cookie manager, and then consent to the use of their cookies.';

/* default url for about cookies link */
$this->trads['input_cookieagreementmessage_aboutcookieurl'] = 'https://en.wikipedia.org/wiki/HTTP_cookie';
?>
