<?php
/**
 * @brief CookieAgreementMessage Input english dictionnary
 * @details Plugin / Input Dictionnary
 * @file plugin/input/CookieAgreementMessage/locale/translation_en.php.inc
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0
 * @date Creation: May 2017
 * @date Modification: Apr 2018
 * @copyright 2017 - 2018 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/* insertion values */
$this->trads['input_cookieagreementmessage_insertion_manual'] = 'Manually';
$this->trads['input_cookieagreementmessage_insertion_automatic'] = 'Automatic';

/* style source values */
$this->trads['input_cookieagreementmessage_stylesource_plugin'] = 'Plugin';
$this->trads['input_cookieagreementmessage_stylesource_theme'] = 'Theme';
 	
/* location values */
$this->trads['input_cookieagreementmessage_location_top'] = 'Top';
$this->trads['input_cookieagreementmessage_location_topleft'] = 'Top / Left';
$this->trads['input_cookieagreementmessage_location_topright'] = 'Top / Right';
$this->trads['input_cookieagreementmessage_location_bottom'] = 'Bottom';
$this->trads['input_cookieagreementmessage_location_bottomleft'] = 'Bottom / Left';
$this->trads['input_cookieagreementmessage_location_bottomright'] = 'Bottom / Right';

/* edit / view config */
$this->trads['input_cookieagreementmessage_formitem_insertion'] = 'Insertion: ';
$this->trads['input_cookieagreementmessage_formitem_stylesource'] = 'Styles source: ';
$this->trads['input_cookieagreementmessage_formitem_aboutcookielink'] = 'About link: ';
$this->trads['input_cookieagreementmessage_formitem_remindttl'] = 'Cookie time-to-live: ';
$this->trads['input_cookieagreementmessage_formdesc_remindttl'] = 'day(s)';
$this->trads['input_cookieagreementmessage_formitem_popuplocation'] = 'Popup location: ';
$this->trads['input_cookieagreementmessage_formitem_message'] = 'Message: ';

$this->trads['input_cookieagreementmessage_config_nolink'] = 'Aucun';
$this->trads['input_cookieagreementmessage_config_automaticlink'] = 'Automatic';
$this->trads['input_cookieagreementmessage_config_customlink'] = 'Personnalised';

$this->trads['input_cookieagreementmessage_config_automaticmessage'] = 'Automatic';

/* popup message contents */
$this->trads['input_cookieagreementmessage_defaultmessage'] = 'Cookies ensure the well functionning of our services. By continuing, you accept their use on our website.';
$this->trads['input_cookieagreementmessage_about'] = 'Read more';
$this->trads['input_cookieagreementmessage_accept'] = 'Accept';

/* default url for about cookies link */
$this->trads['input_cookieagreementmessage_aboutcookieurl'] = 'https://en.wikipedia.org/wiki/HTTP_cookie';
?>