<?php
/*
 * CaMykS Engine
 * Developed by	    : camyks.net
 * Author	       	: CaMykS Team <camyks.contact@gmail.com>
 * CaMykS Version   : 1.0
 * Object Version   : 1.0
 * Object Type      : Plugin / Input Dictionnary
 * Create Date		: May 2017
 * Last Modif Date	: May 2017
 *
 * CookieAgreementMessage language dictionnary : French 
 */

$this->trads['input_cookieagreementmessage_defaultmessage'] = 'Les cookies assurent le bon fonctionnement de nos services. En continuant, vous acceptez leur utilisation sur notre site internet.';
$this->trads['input_cookieagreementmessage_about'] = 'En savoir plus';
$this->trads['input_cookieagreementmessage_accept'] = 'Accepter';

$this->trads['input_cookieagreementmessage_aboutcookieurl'] = 'https://fr.wikipedia.org/wiki/Cookie_(informatique)';
?>
