<?php
/**
 * @brief Content_GoogleMapsViewer module, french dictionary.
 * @details Plugin / Module Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.1
 * @date Creation: Jul 2008
 * @date Modification: Jul 2021
 * @copyright 2008 - 2021 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['mod_content_googlemapsviewer_title'] = 'Affichage d\'une carte Google Maps';
$this->trads['mod_content_googlemapsviewer_desc'] = '';

/* list layouts */
$this->trads['mod_content_googlemapsviewer_layout_classic'] = 'Classique';
$this->trads['mod_content_googlemapsviewer_layout_boxed'] = 'Encadr&eacute;';

/* admin mode */
$this->trads['mod_content_googlemapsviewer_tab_properties'] = 'Propri&eacute;t&eacute;s';

$this->trads['mod_content_googlemapsviewer_title_globalsettings'] = 'Param&egrave;tres globaux';
$this->trads['mod_content_googlemapsviewer_title_mapsettings'] = 'Param&egrave;tres de la carte Google Maps';
$this->trads['mod_content_googlemapsviewer_title_linksettings'] = 'Param&egrave;tres du lien Google Maps';

/* global settings */
$this->trads['mod_content_googlemapsviewer_itemname'] = 'Nom : ';
$this->trads['mod_content_googlemapsviewer_itemlayout'] = 'Layout : ';

/* link settings */
$this->trads['mod_content_googlemapsviewer_itemlinkenabled'] = 'Activ&eacute;';
$this->trads['mod_content_googlemapsviewer_itemlinkclass'] = 'Classe CSS : ';
$this->trads['mod_content_googlemapsviewer_itemlinkclass_specific'] = 'Styles sp&eacute;cifiques';
$this->trads['mod_content_googlemapsviewer_itemlinkcolor'] = 'Couleur : ';
$this->trads['mod_content_googlemapsviewer_itemlinksize'] = 'Taille : ';
$this->trads['mod_content_googlemapsviewer_itemlinkbold'] = 'Gras : ';
$this->trads['mod_content_googlemapsviewer_itemlinkitalic'] = 'Italique : ';
$this->trads['mod_content_googlemapsviewer_itemlinkunderline'] = 'Soulign&eacute; : ';

/* map settings */
$this->trads['mod_content_googlemapsviewer_itemmapsourceimport'] = 'Copiez-collez le code fournit par Google dans l\'espace ci-dessous:';
$this->trads['mod_content_googlemapsviewer_itemmapbaseurl'] = 'Base de l\'URL : ';
$this->trads['mod_content_googlemapsviewer_itemmapzoom'] = 'Zoom : ';
$this->trads['mod_content_googlemapsviewer_itemmapzoommin'] = '1 - Le + &eacute;loign&eacute;';
$this->trads['mod_content_googlemapsviewer_itemmapzoommax'] = '16 - Le + proche';
$this->trads['mod_content_googlemapsviewer_itemmapcode'] = 'Code : ';
$this->trads['mod_content_googlemapsviewer_itemmapwidth'] = 'Largeur : ';
$this->trads['mod_content_googlemapsviewer_itemmapheight'] = 'Hauteur : ';
$this->trads['mod_content_googlemapsviewer_resetmapparameters'] = 'Supprimer les param&egrave;tres de la carte.';
$this->trads['mod_content_googlemapsviewer_admin_googleaccess'] = '&gt;&gt; Ouvrir l\'interface Google Maps';

/* localised items */
$this->trads['mod_content_googlemapsviewer_itemtitle'] = 'Titre : ';
$this->trads['mod_content_googlemapsviewer_itemdescription'] = 'Description : ';

/* JS messages */
$this->trads['mod_content_googlemapsviewer_js_invalidcode'] = 'Le code ins&eacute;r&eacute; semble invalide.';
$this->trads['mod_content_googlemapsviewer_js_resetmap'] = 'Etes vous s&ucirc;r de vouloir supprimer les param&egrave;tres de la carte?';

/* admin message */
$this->trads['mod_content_googlemapsviewer_savedone'] = 'Enregistrement en cours...';
$this->trads['mod_content_googlemapsviewer_savefailed'] = 'Une erreur est survenue lors de l\'enregistrement des donn&eacute;es.';

/* site */
$this->trads['mod_content_googlemapsviewer_site_viewlargermap'] = 'Agrandir le plan';
?>
