<?php
/**
 * @brief DemoPayment input, french dictionary.
 * @details Plugin / Input Dictionary
 * @author CaMykS Team <camyks.contact@gmail.com>
 * @version 1.0.0
 * @date Creation: Mar 2024
 * @date Modification: Mar 2024
 * @copyright 2024 CaMykS Team
 * @note This program is distributed as is - WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */
$this->trads['input_demopayment_creditcard'] = 'Carte de cr&eacute;dit (Fictive)';
$this->trads['input_demopayment_submitpayment'] = 'Valider le paiement';
$this->trads['input_demopayment_creditcard_desc'] = 'R&egrave;glement par carte de cr&eacute;dit en ligne. <br /> Cette m&eacute;thode de paiement permet de tester les commandes sans paiement r&eacute;el.';
?>
